; Image data excluding pattern tables. Generated by convert.py.

image_count equ 54

image_ptrs
	dw img0_ptrs, img1_ptrs, img2_ptrs, img3_ptrs, img4_ptrs
	dw img5_ptrs, img6_ptrs, img7_ptrs, img8_ptrs, img9_ptrs
	dw img10_ptrs, img11_ptrs, img12_ptrs, img13_ptrs, img14_ptrs
	dw img15_ptrs, img16_ptrs, img17_ptrs, img18_ptrs, img19_ptrs
	dw img20_ptrs, img21_ptrs, img22_ptrs, img23_ptrs, img24_ptrs
	dw img25_ptrs, img26_ptrs, img27_ptrs, img28_ptrs, img29_ptrs
	dw img30_ptrs, img31_ptrs, img32_ptrs, img33_ptrs, img34_ptrs
	dw img35_ptrs, img36_ptrs, img37_ptrs, img38_ptrs, img39_ptrs
	dw img40_ptrs, img41_ptrs, img42_ptrs, img43_ptrs, img44_ptrs
	dw img45_ptrs, img46_ptrs, img47_ptrs, img48_ptrs, img49_ptrs
	dw img50_ptrs, img51_ptrs, img52_ptrs, img53_ptrs

img0_ptrs
	dw img0_nt_at0, img0_nt_at1, img0_nt_at2, img0_nt_at3
	dw img0_nt_at4, img0_nt_at5, img0_pt, img0_pal
	dw img0_txt
img1_ptrs
	dw img1_nt_at0, img1_nt_at1, img1_nt_at2, img1_nt_at3
	dw img1_nt_at4, img1_nt_at5, img1_pt, img1_pal
	dw img1_txt
img2_ptrs
	dw img2_nt_at0, img2_nt_at1, img2_nt_at2, img2_nt_at3
	dw img2_nt_at4, img2_nt_at5, img2_pt, img2_pal
	dw img2_txt
img3_ptrs
	dw img3_nt_at0, img3_nt_at1, img3_nt_at2, img3_nt_at3
	dw img3_nt_at4, img3_nt_at5, img3_pt, img3_pal
	dw img3_txt
img4_ptrs
	dw img4_nt_at0, img4_nt_at1, img4_nt_at2, img4_nt_at3
	dw img4_nt_at4, img4_nt_at5, img4_pt, img4_pal
	dw img4_txt
img5_ptrs
	dw img5_nt_at0, img5_nt_at1, img5_nt_at2, img5_nt_at3
	dw img5_nt_at4, img5_nt_at5, img5_pt, img5_pal
	dw img5_txt
img6_ptrs
	dw img6_nt_at0, img6_nt_at1, img6_nt_at2, img6_nt_at3
	dw img6_nt_at4, img6_nt_at5, img6_pt, img6_pal
	dw img6_txt
img7_ptrs
	dw img7_nt_at0, img7_nt_at1, img7_nt_at2, img7_nt_at3
	dw img7_nt_at4, img7_nt_at5, img7_pt, img7_pal
	dw img7_txt
img8_ptrs
	dw img8_nt_at0, img8_nt_at1, img8_nt_at2, img8_nt_at3
	dw img8_nt_at4, img8_nt_at5, img8_pt, img8_pal
	dw img8_txt
img9_ptrs
	dw img9_nt_at0, img9_nt_at1, img9_nt_at2, img9_nt_at3
	dw img9_nt_at4, img9_nt_at5, img9_pt, img9_pal
	dw img9_txt
img10_ptrs
	dw img10_nt_at0, img10_nt_at1, img10_nt_at2, img10_nt_at3
	dw img10_nt_at4, img10_nt_at5, img10_pt, img10_pal
	dw img10_txt
img11_ptrs
	dw img11_nt_at0, img11_nt_at1, img11_nt_at2, img11_nt_at3
	dw img11_nt_at4, img11_nt_at5, img11_pt, img11_pal
	dw img11_txt
img12_ptrs
	dw img12_nt_at0, img12_nt_at1, img12_nt_at2, img12_nt_at3
	dw img12_nt_at4, img12_nt_at5, img12_pt, img12_pal
	dw img12_txt
img13_ptrs
	dw img13_nt_at0, img13_nt_at1, img13_nt_at2, img13_nt_at3
	dw img13_nt_at4, img13_nt_at5, img13_pt, img13_pal
	dw img13_txt
img14_ptrs
	dw img14_nt_at0, img14_nt_at1, img14_nt_at2, img14_nt_at3
	dw img14_nt_at4, img14_nt_at5, img14_pt, img14_pal
	dw img14_txt
img15_ptrs
	dw img15_nt_at0, img15_nt_at1, img15_nt_at2, img15_nt_at3
	dw img15_nt_at4, img15_nt_at5, img15_pt, img15_pal
	dw img15_txt
img16_ptrs
	dw img16_nt_at0, img16_nt_at1, img16_nt_at2, img16_nt_at3
	dw img16_nt_at4, img16_nt_at5, img16_pt, img16_pal
	dw img16_txt
img17_ptrs
	dw img17_nt_at0, img17_nt_at1, img17_nt_at2, img17_nt_at3
	dw img17_nt_at4, img17_nt_at5, img17_pt, img17_pal
	dw img17_txt
img18_ptrs
	dw img18_nt_at0, img18_nt_at1, img18_nt_at2, img18_nt_at3
	dw img18_nt_at4, img18_nt_at5, img18_pt, img18_pal
	dw img18_txt
img19_ptrs
	dw img19_nt_at0, img19_nt_at1, img19_nt_at2, img19_nt_at3
	dw img19_nt_at4, img19_nt_at5, img19_pt, img19_pal
	dw img19_txt
img20_ptrs
	dw img20_nt_at0, img20_nt_at1, img20_nt_at2, img20_nt_at3
	dw img20_nt_at4, img20_nt_at5, img20_pt, img20_pal
	dw img20_txt
img21_ptrs
	dw img21_nt_at0, img21_nt_at1, img21_nt_at2, img21_nt_at3
	dw img21_nt_at4, img21_nt_at5, img21_pt, img21_pal
	dw img21_txt
img22_ptrs
	dw img22_nt_at0, img22_nt_at1, img22_nt_at2, img22_nt_at3
	dw img22_nt_at4, img22_nt_at5, img22_pt, img22_pal
	dw img22_txt
img23_ptrs
	dw img23_nt_at0, img23_nt_at1, img23_nt_at2, img23_nt_at3
	dw img23_nt_at4, img23_nt_at5, img23_pt, img23_pal
	dw img23_txt
img24_ptrs
	dw img24_nt_at0, img24_nt_at1, img24_nt_at2, img24_nt_at3
	dw img24_nt_at4, img24_nt_at5, img24_pt, img24_pal
	dw img24_txt
img25_ptrs
	dw img25_nt_at0, img25_nt_at1, img25_nt_at2, img25_nt_at3
	dw img25_nt_at4, img25_nt_at5, img25_pt, img25_pal
	dw img25_txt
img26_ptrs
	dw img26_nt_at0, img26_nt_at1, img26_nt_at2, img26_nt_at3
	dw img26_nt_at4, img26_nt_at5, img26_pt, img26_pal
	dw img26_txt
img27_ptrs
	dw img27_nt_at0, img27_nt_at1, img27_nt_at2, img27_nt_at3
	dw img27_nt_at4, img27_nt_at5, img27_pt, img27_pal
	dw img27_txt
img28_ptrs
	dw img28_nt_at0, img28_nt_at1, img28_nt_at2, img28_nt_at3
	dw img28_nt_at4, img28_nt_at5, img28_pt, img28_pal
	dw img28_txt
img29_ptrs
	dw img29_nt_at0, img29_nt_at1, img29_nt_at2, img29_nt_at3
	dw img29_nt_at4, img29_nt_at5, img29_pt, img29_pal
	dw img29_txt
img30_ptrs
	dw img30_nt_at0, img30_nt_at1, img30_nt_at2, img30_nt_at3
	dw img30_nt_at4, img30_nt_at5, img30_pt, img30_pal
	dw img30_txt
img31_ptrs
	dw img31_nt_at0, img31_nt_at1, img31_nt_at2, img31_nt_at3
	dw img31_nt_at4, img31_nt_at5, img31_pt, img31_pal
	dw img31_txt
img32_ptrs
	dw img32_nt_at0, img32_nt_at1, img32_nt_at2, img32_nt_at3
	dw img32_nt_at4, img32_nt_at5, img32_pt, img32_pal
	dw img32_txt
img33_ptrs
	dw img33_nt_at0, img33_nt_at1, img33_nt_at2, img33_nt_at3
	dw img33_nt_at4, img33_nt_at5, img33_pt, img33_pal
	dw img33_txt
img34_ptrs
	dw img34_nt_at0, img34_nt_at1, img34_nt_at2, img34_nt_at3
	dw img34_nt_at4, img34_nt_at5, img34_pt, img34_pal
	dw img34_txt
img35_ptrs
	dw img35_nt_at0, img35_nt_at1, img35_nt_at2, img35_nt_at3
	dw img35_nt_at4, img35_nt_at5, img35_pt, img35_pal
	dw img35_txt
img36_ptrs
	dw img36_nt_at0, img36_nt_at1, img36_nt_at2, img36_nt_at3
	dw img36_nt_at4, img36_nt_at5, img36_pt, img36_pal
	dw img36_txt
img37_ptrs
	dw img37_nt_at0, img37_nt_at1, img37_nt_at2, img37_nt_at3
	dw img37_nt_at4, img37_nt_at5, img37_pt, img37_pal
	dw img37_txt
img38_ptrs
	dw img38_nt_at0, img38_nt_at1, img38_nt_at2, img38_nt_at3
	dw img38_nt_at4, img38_nt_at5, img38_pt, img38_pal
	dw img38_txt
img39_ptrs
	dw img39_nt_at0, img39_nt_at1, img39_nt_at2, img39_nt_at3
	dw img39_nt_at4, img39_nt_at5, img39_pt, img39_pal
	dw img39_txt
img40_ptrs
	dw img40_nt_at0, img40_nt_at1, img40_nt_at2, img40_nt_at3
	dw img40_nt_at4, img40_nt_at5, img40_pt, img40_pal
	dw img40_txt
img41_ptrs
	dw img41_nt_at0, img41_nt_at1, img41_nt_at2, img41_nt_at3
	dw img41_nt_at4, img41_nt_at5, img41_pt, img41_pal
	dw img41_txt
img42_ptrs
	dw img42_nt_at0, img42_nt_at1, img42_nt_at2, img42_nt_at3
	dw img42_nt_at4, img42_nt_at5, img42_pt, img42_pal
	dw img42_txt
img43_ptrs
	dw img43_nt_at0, img43_nt_at1, img43_nt_at2, img43_nt_at3
	dw img43_nt_at4, img43_nt_at5, img43_pt, img43_pal
	dw img43_txt
img44_ptrs
	dw img44_nt_at0, img44_nt_at1, img44_nt_at2, img44_nt_at3
	dw img44_nt_at4, img44_nt_at5, img44_pt, img44_pal
	dw img44_txt
img45_ptrs
	dw img45_nt_at0, img45_nt_at1, img45_nt_at2, img45_nt_at3
	dw img45_nt_at4, img45_nt_at5, img45_pt, img45_pal
	dw img45_txt
img46_ptrs
	dw img46_nt_at0, img46_nt_at1, img46_nt_at2, img46_nt_at3
	dw img46_nt_at4, img46_nt_at5, img46_pt, img46_pal
	dw img46_txt
img47_ptrs
	dw img47_nt_at0, img47_nt_at1, img47_nt_at2, img47_nt_at3
	dw img47_nt_at4, img47_nt_at5, img47_pt, img47_pal
	dw img47_txt
img48_ptrs
	dw img48_nt_at0, img48_nt_at1, img48_nt_at2, img48_nt_at3
	dw img48_nt_at4, img48_nt_at5, img48_pt, img48_pal
	dw img48_txt
img49_ptrs
	dw img49_nt_at0, img49_nt_at1, img49_nt_at2, img49_nt_at3
	dw img49_nt_at4, img49_nt_at5, img49_pt, img49_pal
	dw img49_txt
img50_ptrs
	dw img50_nt_at0, img50_nt_at1, img50_nt_at2, img50_nt_at3
	dw img50_nt_at4, img50_nt_at5, img50_pt, img50_pal
	dw img50_txt
img51_ptrs
	dw img51_nt_at0, img51_nt_at1, img51_nt_at2, img51_nt_at3
	dw img51_nt_at4, img51_nt_at5, img51_pt, img51_pal
	dw img51_txt
img52_ptrs
	dw img52_nt_at0, img52_nt_at1, img52_nt_at2, img52_nt_at3
	dw img52_nt_at4, img52_nt_at5, img52_pt, img52_pal
	dw img52_txt
img53_ptrs
	dw img53_nt_at0, img53_nt_at1, img53_nt_at2, img53_nt_at3
	dw img53_nt_at4, img53_nt_at5, img53_pt, img53_pal
	dw img53_txt

	; title_screen
img0_nt_at0
	hex 01 26 817d 817e 817b 04 812a 812b 8110 812c 811c 8126 13
	hex 8171 8103 817c 04 811e 19 8103 1f 8103 8142 814a 02 00
img0_nt_at1
	hex 01 8160 8143 8241 8142 814a 02 8160 8143 8241 8142 814a 0d
	hex 8103 8202 02 8602 02 8602 0d 8103 02 8148 8161 8149 8162
	hex 8170 8175 816a 8156 8169 8158 13 8103 02 8148 8165 8148 8164
	hex 8170 8175 815c 8159 8166 8157 13 8103 10 00
img0_nt_at2
	hex 01 0f 8103 1f 8103 04 817a 8177 815a 01 8150 8156 8151
	hex 8155 13 8103 04 8179 8176 815b 8140 8168 815a 815d 8159 13
	hex 8103 1c 00
img0_nt_at3
	hex 01 03 8103 1f 8103 04 8145 815e 8172 8173 8147 815f 814b
	hex 8146 02 8154 8167 0f 8103 04 8144 8163 8174 8178 814e 814f
	hex 814c 8152 02 814d 8153 0f 8103 8602 02 8602 02 8202 0d
	hex 8103 816f 816d 826b 816c 816e 02 00
img0_nt_at4
	hex 01 816f 816d 826b 816c 816e 02 816f 816d 0d 8103 1f 8103
	hex 06 811a 01 8127 8129 8128 8122 8108 8125 8123 8124 0f 8103
	hex 06 8121 01 8113 8131 8130 8120 13 8103 06 8138 01 8137
	hex 8135 8133 812d 8136 8134 06 00
img0_nt_at5
	hex 01 0b 8103 02 813b 8132 813d 813c 8116 01 8114 810e 8105
	hex 810c 810d 8104 8139 812e 812f 813e 813f 813a 0b 8103 02 811f
	hex 811d 8115 8119 811b 01 810f 8112 811f 8117 8119 8111 8118 8106
	hex 8109 810a 810b 8107 04 9200 8140 8100 8140 8500 8159 815d 8157
	hex 8155 8111 8300 8155 815b 815d 8155 8111 8300 8105 814f 8109 814d
	hex 01 9100 00
img0_pt
	db 7
img0_pal
	hex 0f213013 0f30150f 0f30270f 0f301912
img0_txt
	db 13
	hex ee e3 ee e6 df 00 00 ed dd ec df df e8

	; agender
img1_nt_at0
	hex 00 60 a004 8c01 00
img1_nt_at1
	hex 01 34 a01c b803 00
img1_nt_at2
	hex 03 28 a02b c002 8426 00
img1_nt_at3
	hex 26 1c e003 9021 00
img1_nt_at4
	hex 21 10 c001 a00b 9c00 00
img1_nt_at5
	hex 00 7f 05 00
img1_pt
	db 0
img1_pal
	hex 0f002930 0f0f0f0f 0f0f0f0f 0f0f0f0f
img1_txt
	db 7
	hex db e1 df e8 de df ec

	; andro-_gyne
img2_nt_at0
	hex 02 0a 8116 8a01 8120 8a03 0a 8116 8a01 8120 8a03 0a 8116
	hex 8a01 8120 8a03 0a 8116 8a01 8120 8a03 0a 8116 8101 00
img2_nt_at1
	hex 01 09 8120 8a03 8a02 8116 0a 8120 8a03 8a02 8116 0a 8120
	hex 8a03 8a02 8116 0a 8120 8a03 8a02 8116 0a 8120 8203 00
img2_nt_at2
	hex 03 08 8a02 8116 8a01 8120 0a 8a02 8116 8a01 8120 0a 8a02
	hex 8116 8a01 8120 0a 8a02 8116 8a01 8120 0a 8402 00
img2_nt_at3
	hex 02 06 8116 8a01 8120 8a03 0a 8116 8a01 8120 8a03 0a 8116
	hex 8a01 8120 8a03 0a 8116 8a01 8120 8a03 0a 8116 8501 00
img2_nt_at4
	hex 01 05 8120 8a03 8a02 8116 0a 8120 8a03 8a02 8116 0a 8120
	hex 8a03 8a02 8116 0a 8120 8a03 8a02 8116 0a 8120 8603 00
img2_nt_at5
	hex 03 04 8a02 8116 8a01 8120 0a 8a02 8116 8a01 8120 0a c000
	hex 00
img2_pt
	db 0
img2_pal
	hex 0f13152c 0f0f0f0f 0f0f0f0f 0f0f0f0f
img2_txt
	db 14
	hex db e8 de ec e9 d0 00 00 00 00 e1 f3 e8 df

	; a-_romantic
img3_nt_at0
	hex 01 7f 01 8c12 00
img3_nt_at1
	hex 12 14 f802 00
img3_nt_at2
	hex 02 08 a027 e403 00
img3_nt_at3
	hex 03 1c a022 d001 00
img3_nt_at4
	hex 01 30 a009 bc00 00
img3_nt_at5
	hex 00 4c 8850 8855 28 00
img3_pt
	db 0
img3_pal
	hex 0f002930 0f1a290f 0f0f0f0f 0f0f0f0f
img3_txt
	db 10
	hex db d0 ec e9 e7 db e8 ee e3 dd

	; a-_romantic_asexual
img4_nt_at0
	hex 01 7f 01 8c12 00
img4_nt_at1
	hex 12 14 f802 00
img4_nt_at2
	hex 02 08 a027 e403 00
img4_nt_at3
	hex 03 1c a02c d002 00
img4_nt_at4
	hex 02 30 a018 bc01 00
img4_nt_at5
	hex 00 c401 08 8850 9055 20 00
img4_pt
	db 0
img4_pal
	hex 0f0c2130 0f172830 0f0f0f0f 0f0f0f0f
img4_txt
	db 18
	hex db d0 ec e9 e7 db e8 ee e3 dd 00 db ed df f2 ef db e6

	; asexual
img5_nt_at0
	hex 00 7f 0d 00
img5_nt_at1
	hex 00 34 d801 00
img5_nt_at2
	hex 01 68 a403 00
img5_nt_at3
	hex 03 7f 0d 00
img5_nt_at4
	hex 03 10 fc02 00
img5_nt_at5
	hex 02 44 c000 00
img5_pt
	db 0
img5_pal
	hex 0f001430 0f0f0f0f 0f0f0f0f 0f0f0f0f
img5_txt
	db 7
	hex db ed df f2 ef db e6

	; asexual_furry1
img6_nt_at0
	hex 00 7f 0d 00
img6_nt_at1
	hex 00 34 8d01 815c 8152 8153 8156 8150 8159 9901 8157 8137 01
	hex 8126 8140 01 811f 8155 9801 8145 02 8121 8139 02 812a 8401
	hex 00
img6_nt_at2
	hex 00 9201 815c 8158 8142 02 8124 813c 02 8128 815b 8159 9401
	hex 8138 01 812f 8111 8107 812c 8146 810b 810e 812d 01 8120 9401
	hex 02 8123 8101 815f 814f 814d 815e 8101 813b 02 9401 8114 02
	hex 8161 8141 02 8127 8160 02 8113 8e01 00
img6_nt_at3
	hex 01 06 813d 8105 8116 8149 8400 8133 8118 8104 8125 15 8148
	hex 8132 8600 8130 812e 16 814a 8800 8134 16 814b 8110 8600 810d
	hex 8136 17 8144 8112 8108 8117 00
img6_nt_at4
	hex 01 8119 810c 810f 8129 7f 09 00
img6_nt_at5
	hex 55 c401 a000 8850 03 8151 8154 03 88aa 880a 00
img6_pt
	db 3
img6_pal
	hex 0f000f0f 0f300f0f 0f140f0f 0f0f0f0f
img6_txt
	db 15
	hex db ed df f2 ef db e6 00 00 e0 ef ec ec f3 d2

	; asexual_furry2
img7_nt_at0
	hex 00 6c 8105 8109 810d 8201 8112 810b 8107 16 8104 810c 00
img7_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 8111 8106 9300 8108 8110
	hex 8141 8168 01 81cf 02 81cd 01 8197 8146 8115 810a 8900 08
	hex 81f3 81e5 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f 81db
	hex 81f1 10 81e7 814a 02 81a4 8201 815c 818b 8201 8179 02 814d
	hex 81dd 0f 81a5 812d 8172 02 8191 8201 8154 8183 8201 8162 02
	hex 81a0 812f 00
img7_nt_at2
	hex 02 817a 0e 8190 8157 01 81bf 81b8 8193 8201 815d 818c 8201
	hex 8164 81bd 81ba 01 8186 8161 0e 817e 816b 01 8182 8101 8174
	hex 8135 812e 816c 819b 8130 8131 816d 8101 8153 01 819a 814f 0e
	hex 8101 8171 01 8201 815b 01 81c7 81ad 81a9 81c4 01 818a 8201
	hex 01 819f 8101 07 8801 817c 01 813b 8201 81d0 8192 8201 8163
	hex 81ce 8201 8139 01 81a7 8c01 00
img7_nt_at3
	hex 01 04 8170 8102 818d 8124 813f 81a3 04 8178 8144 8121 815e
	hex 8102 819e 10 816a 8202 81a1 8176 06 8175 8173 8202 8199 10
	hex 8152 81c5 8102 81a6 08 817b 8102 81c8 8181 11 816f 8102 81a8
	hex 8129 06 8126 817d 8102 819d 13 81ac 8102 8188 812b 8120 8133
	hex 00
img7_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 8a01 09 8187 812a 81ab 81ca
	hex 06 81cc 81af 8127 8158 13 8196 8136 815a 81b3 81c3 81c9 81cb
	hex 81c6 81b6 8189 8132 8167 16 814e 8138 8125 8201 8122 8134 814b
	hex 28 00
img7_nt_at5
	hex 00 c402 18 8255 04 8255 8205 04 8205 18 00
img7_pt
	db 2
img7_pal
	hex 0f301400 0f30000f 0f0f0f0f 0f0f0f0f
img7_txt
	db 15
	hex db ed df f2 ef db e6 00 00 e0 ef ec ec f3 d3

	; autism
img8_nt_at0
	hex 01 7f 0d 00
img8_nt_at1
	hex 01 5b 8110 8120 8127 8126 8114 08 8113 8121 8127 8125 8111
	hex 0d 811e 8148 8402 813a 811a 04 8115 8137 8402 00
img8_nt_at2
	hex 01 8165 8123 0c 8150 81a4 8187 817a 817b 818a 81a3 8175 8131
	hex 02 812d 8157 81a4 818b 8180 817a 8184 81a3 816d 0b 8135 8102
	hex 8173 04 8152 8190 8103 81d8 8136 8102 8193 816f 04 8155 8102
	hex 8138 0a 8145 8102 815e 05 813d 81e5 81cb 8102 8189 815c 05
	hex 8144 8102 8161 0a 8145 8102 815e 05 8110 8142 8102 81b7 81a9
	hex 8111 05 8140 8102 8161 09 00
img8_nt_at3
	hex 01 01 813f 8102 8162 04 8118 8147 8102 8182 81aa 8103 8164
	hex 811d 04 8146 8102 815d 0b 817f 8179 8132 8112 8116 812f 815b
	hex 81a0 8176 02 8158 819d 8179 8133 811b 8112 812e 815b 8183 0c
	hex 8143 8191 8402 8192 8167 04 814a 818e 8402 8194 8160 0d 813d
	hex 817c 818c 8188 816e 08 8151 8185 818c 8181 815c 17 00
img8_nt_at4
	hex 01 7f 0d 00
img8_nt_at5
	hex 00 c401 19 8188 8122 01 8150 81dd 8133 02 81aa 01 8154
	hex 8115 01 81ff 02 8188 8166 8105 01 81cc 8133 11 00
img8_pt
	db 4
img8_pal
	hex 0f37270f 0f372127 0f37250f 0f37290f
img8_txt
	db 6
	hex db ef ee e3 ed e7

	; autism_hstripes
img9_nt_at0
	hex 01 60 a02c 8c02 00
img9_nt_at1
	hex 01 b402 a0ac 07 8110 8120 8127 8126 8114 08 8113 8121 8127
	hex 8125 8111 0d 811e 8148 8402 813a 811a 04 8115 8137 8402 00
img9_nt_at2
	hex 01 8165 8123 0c 8150 81a4 8187 817a 817b 818a 81a3 8175 8131
	hex 02 812d 8157 81a4 818b 8180 817a 8184 81a3 816d 0b 8135 8102
	hex 8173 04 8152 8190 8102 8139 8136 8102 8193 816f 04 8155 8102
	hex 8138 0a 8145 8102 815e 05 813d 8186 8202 8189 815c 05 8144
	hex 8102 8161 0a 8145 8102 815e 05 8110 8142 8202 815f 8111 05
	hex 8140 8102 8161 09 00
img9_nt_at3
	hex 01 01 813f 8102 8162 04 8118 8147 8102 8182 817e 8102 8164
	hex 811d 04 8146 8102 815d 0b 817f 8179 8132 8112 8116 812f 815b
	hex 81a0 8176 02 8158 819d 8179 8133 811b 8112 812e 815b 8183 0c
	hex 8143 8191 8402 8192 8167 04 814a 818e 8402 8194 8160 0d 813d
	hex 817c 818c 8188 816e 08 8151 8185 818c 8181 815c 07 90a6 00
img9_nt_at4
	hex a6 10 c002 a095 9c01 00
img9_nt_at5
	hex 01 44 9800 9055 88a5 88ff 880f 00
img9_pt
	db 4
img9_pal
	hex 0f16260f 0f283026 0f28302a 0f1a2a0f
img9_txt
	db 14
	hex db ef ee e3 ed e7 e2 ed ee ec e3 ea df ed

	; autism_vstripes
img10_nt_at0
	hex 01 0a 8145 8102 09 81a8 14 8145 8102 09 81a8 14 8145
	hex 8102 09 81a8 14 8145 8102 09 81a8 14 8145 8102 00
img10_nt_at1
	hex 01 09 81a8 14 8145 8102 09 81a8 14 81a7 8103 09 81a8
	hex 11 8110 8120 8127 81da 81d3 08 8113 81db 8127 8125 8111 0d
	hex 811e 8148 8402 813a 811a 04 8115 8137 8402 00
img10_nt_at2
	hex 01 8165 8123 0c 8150 81a4 8187 817a 81e0 81b1 81a3 8175 8131
	hex 02 812d 8157 81a4 818b 81e3 817a 8184 81a3 816d 0b 8135 8102
	hex 8173 02 8145 8102 8152 8190 8102 8139 8136 8102 8193 816f 01
	hex 81a8 02 8155 8102 8138 0a 8145 8102 815e 02 8145 8102 01
	hex 813d 8186 8202 8189 815c 02 81a8 02 8144 8102 8161 0a 8145
	hex 8102 815e 02 8145 8102 01 8110 8142 8202 815f 8111 02 81a8
	hex 02 8140 8102 8161 09 00
img10_nt_at3
	hex 01 01 813f 8102 8162 02 8145 8102 8118 8147 8102 8182 817e
	hex 8102 8164 811d 01 81a8 02 8146 8102 815d 0b 817f 8179 8132
	hex 8112 81d9 81cf 815b 81a0 8176 02 8158 819d 8179 8133 81dc 8112
	hex 812e 815b 8183 0c 8143 8191 8402 8192 8167 04 814a 818e 8402
	hex 8194 8160 0d 813d 817c 818c 81e2 81bd 08 8151 81e1 818c 8181
	hex 815c 11 81a7 8103 04 00
img10_nt_at4
	hex 01 05 81a8 14 8145 8102 09 81a8 14 8145 8102 09 81a8
	hex 14 8145 8102 09 81a8 14 8145 8102 09 81a8 06 00
img10_nt_at5
	hex 00 8e01 8145 8102 8901 81a8 9401 8145 8102 8901 81a8 8a01 0a
	hex 81c0 8250 8190 82a0 02 81cc 8255 8199 82aa 03 8255 8199 82aa
	hex 02 81cc 8255 8199 82aa 03 8255 8199 82aa 02 81cc 8255 8199
	hex 82aa 02 810c 8205 8109 820a 00
img10_pt
	db 4
img10_pal
	hex 0f16301a 0f1a3012 0f12300f 0f161a0f
img10_txt
	db 14
	hex db ef ee e3 ed e7 f0 ed ee ec e3 ea df ed

	; bear
img11_nt_at0
	hex 00 a501 8138 8135 8133 9d01 8119 02 8124 812c 812e 8137 9401
	hex 826a 81f0 01 81ef 81ee 81e9 813c 81ea 81ed 01 810d 81f2 936a
	hex 8301 810a 01 8112 8128 8127 8129 811c 8104 01 00
img11_nt_at1
	hex 00 8114 8139 9501 8121 8109 810f 03 8110 811d 810b 811e 810c
	hex 812b 9101 835b 8130 81f1 81ec 07 81e8 81eb 915b 8302 813f 01
	hex 814a 8140 05 813e 8143 9502 8146 813b 8142 8149 03 813a 8141
	hex 8145 8b02 00
img11_nt_at2
	hex 00 8b02 814b 8148 814c 8147 02 813d 8144 9502 83e6 81f5 01
	hex 81f4 81f6 01 814e 81f3 96e6 8403 814f 8150 8153 814d 8151 9e03
	hex 8152 9803 84e7 00
img11_nt_at3
	hex e7 1c e002 90c1 00
img11_nt_at4
	hex c1 10 c001 a032 9c00 00
img11_nt_at5
	hex 00 4c 88a0 880a 08 8850 9055 08 00
img11_pt
	db 6
img11_pal
	hex 0f172737 0f003037 0f07170f 0f0f0f0f
img11_txt
	db 4
	hex dc df db ec

	; bigender
img12_nt_at0
	hex 01 60 a014 8c02 00
img12_nt_at1
	hex 02 34 a025 a003 18 00
img12_nt_at2
	hex 02 28 a018 c001 8412 00
img12_nt_at3
	hex 12 1c c002 a003 9029 00
img12_nt_at4
	hex 29 10 c002 a01a 9c01 00
img12_nt_at5
	hex 00 c401 08 8850 8855 88a5 88aa 880a 10 00
img12_pt
	db 0
img12_pal
	hex 0f112133 0f142433 0f30330f 0f0f0f0f
img12_txt
	db 8
	hex dc e3 e1 df e8 de df ec

	; bisexual
img13_nt_at0
	hex 03 7f 0d 00
img13_nt_at1
	hex 03 7f 0d 00
img13_nt_at2
	hex 03 08 a02d e402 00
img13_nt_at3
	hex 02 1c a019 d001 00
img13_nt_at4
	hex 01 7f 0d 00
img13_nt_at5
	hex 01 44 c000 00
img13_pt
	db 0
img13_pal
	hex 0f121315 0f0f0f0f 0f0f0f0f 0f0f0f0f
img13_txt
	db 8
	hex dc e3 ed df f2 ef db e6

	; bisexual_furry1
img14_nt_at0
	hex 01 7f 0d 00
img14_nt_at1
	hex 00 c101 815c 8152 8153 8156 8150 8159 9901 8157 8137 01 8126
	hex 8140 01 811f 8155 8c01 8c02 8175 02 8167 8171 02 816c 8402
	hex 00
img14_nt_at2
	hex 00 8802 8a97 81a9 81a6 81a5 02 819c 81a4 02 819d 81a8 81a7
	hex 8a97 8a01 8138 01 812f 8111 8107 812c 8146 810b 810e 812d 01
	hex 8120 9401 02 8123 8101 815f 814f 814d 815e 8101 813b 02 9401
	hex 8114 02 8161 8141 02 8127 8160 02 8113 8e01 00
img14_nt_at3
	hex 01 06 813d 8105 8116 8149 8400 8133 8118 8104 8125 0a 8b86
	hex 81a2 81a1 8600 81a0 819f 8b86 8b02 8176 8800 816e 8b02 0b 814b
	hex 8110 8600 810d 8136 17 8144 8112 8108 8117 00
img14_nt_at4
	hex 01 8119 810c 810f 8129 7f 09 00
img14_nt_at5
	hex fa c401 9800 8850 8855 03 81f2 81f8 03 88ff 880f 00
img14_pt
	db 3
img14_pal
	hex 0f150f0f 0f13150f 0f13120f 0f120f0f
img14_txt
	db 16
	hex dc e3 ed df f2 ef db e6 00 00 e0 ef ec ec f3 d2

	; bisexual_furry2
img15_nt_at0
	hex 02 6c 81be 81b5 8198 8201 8169 81b2 81b9 16 81f2 81ec 00
img15_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 81e2 81f0 13 81b7 81e5
	hex 8141 8168 01 81cf 02 81cd 01 8197 8146 81db 81b4 11 81f3
	hex 81e5 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f 81db 81f1
	hex 10 81e7 814a 02 81a4 8201 815c 818b 8201 8179 02 814d 81dd
	hex 08 8703 81ed 812d 8172 02 8191 8201 8154 8183 8201 8162 02
	hex 81a0 812f 00
img15_nt_at2
	hex 02 81e3 8703 87f7 81fe 8157 01 81bf 81b8 8193 8201 815d 818c
	hex 8201 8164 81bd 81ba 01 8186 81f9 87f7 07 817e 816b 01 8182
	hex 8101 8174 8135 812e 816c 819b 8130 8131 816d 8101 8153 01 819a
	hex 814f 0e 8101 8171 01 8201 815b 01 81c7 81ad 81a9 81c4 01
	hex 818a 8201 01 819f 8101 0e 8101 817c 01 813b 8201 81d0 8192
	hex 8201 8163 81ce 8201 8139 01 81a7 8101 0b 00
img15_nt_at3
	hex 02 03 8143 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121
	hex 815e 01 819e 813e 07 87f5 81fb 816a 02 81a1 8176 8601 8175
	hex 8173 02 8199 81f8 87f5 8703 81e9 8152 81c5 01 81a6 8801 817b
	hex 01 81c8 8181 81df 8703 08 81d9 816f 01 81a8 8129 8601 8126
	hex 817d 01 819d 81d8 10 81eb 81d2 81ac 01 8188 812b 8120 8133
	hex 00
img15_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 81d1 81e1 11 8187 81d2 81ab
	hex 81ca 06 81cc 81af 81d1 8158 13 81ea 81d4 815a 81b3 81c3 81c9
	hex 81cb 81c6 81b6 8189 81d3 81e0 16 814e 8138 8125 8201 8122 8134
	hex 814b 28 00
img15_nt_at5
	hex 00 c402 08 88a0 82aa 812a 820a 818a 82aa 820a 04 820a 08
	hex 82f5 8110 02 8140 82f5 82ff 81f7 82f0 81fd 82ff 880f 00
img15_pt
	db 2
img15_pal
	hex 0f301315 0f301312 0f30150f 0f30120f
img15_txt
	db 16
	hex dc e3 ed df f2 ef db e6 00 00 e0 ef ec ec f3 d3

	; demi-_fluid
img16_nt_at0
	hex 01 60 a014 0c 00
img16_nt_at1
	hex 02 b401 8813 901e 8827 08 9803 08 9003 00
img16_nt_at2
	hex 03 08 8802 18 e402 00
img16_nt_at3
	hex 02 24 9803 08 9803 08 9803 8819 8822 00
img16_nt_at4
	hex 01 8822 882c 40 a01a 1c 00
img16_nt_at5
	hex 00 c401 10 8850 8455 82aa 02 88aa 8455 82aa 02 8805 08
	hex 00
img16_pt
	db 0
img16_pal
	hex 0f001031 0f103538 0f10303b 0f0f0f0f
img16_txt
	db 13
	hex de df e7 e3 d0 00 00 00 e0 e6 ef e3 de

	; demiflux
img17_nt_at0
	hex 01 60 a014 0c 00
img17_nt_at1
	hex 01 34 a011 b802 00
img17_nt_at2
	hex 02 28 a028 a003 20 841b 00
img17_nt_at3
	hex 1b 1c c001 a003 9029 00
img17_nt_at4
	hex 01 9029 40 a01a 1c 00
img17_nt_at5
	hex 00 c401 10 8850 8855 88a5 880a 8805 08 00
img17_pt
	db 0
img17_pal
	hex 0f001031 0f103638 0f31380f 0f0f0f0f
img17_txt
	db 8
	hex de df e7 e3 e0 e6 ef f2

	; demi-_gender
img18_nt_at0
	hex 01 60 a014 8c02 00
img18_nt_at1
	hex 02 34 a025 a003 18 00
img18_nt_at2
	hex 02 28 a018 c001 8412 00
img18_nt_at3
	hex 12 1c c002 a003 9029 00
img18_nt_at4
	hex 29 10 c002 a01a 9c01 00
img18_nt_at5
	hex 00 c401 18 8850 8855 8805 10 00
img18_pt
	db 0
img18_pal
	hex 0f001038 0f30380f 0f0f0f0f 0f0f0f0f
img18_txt
	db 13
	hex de df e7 e3 d0 00 00 e1 df e8 de df ec

	; demigirl
img19_nt_at0
	hex 01 60 a014 8c02 00
img19_nt_at1
	hex 02 34 a025 a003 18 00
img19_nt_at2
	hex 02 28 a018 c001 8412 00
img19_nt_at3
	hex 12 1c c002 a003 9029 00
img19_nt_at4
	hex 29 10 c002 a01a 9c01 00
img19_nt_at5
	hex 00 c401 18 8850 8855 8805 10 00
img19_pt
	db 0
img19_pal
	hex 0f001035 0f30350f 0f0f0f0f 0f0f0f0f
img19_txt
	db 8
	hex de df e7 e3 e1 e3 ec e6

	; demiguy
img20_nt_at0
	hex 01 60 a014 8c02 00
img20_nt_at1
	hex 02 34 a025 a003 18 00
img20_nt_at2
	hex 02 28 a018 c001 8412 00
img20_nt_at3
	hex 12 1c c002 a003 9029 00
img20_nt_at4
	hex 29 10 c002 a01a 9c01 00
img20_nt_at5
	hex 00 c401 18 8850 8855 8805 10 00
img20_pt
	db 0
img20_pal
	hex 0f001031 0f30310f 0f0f0f0f 0f0f0f0f
img20_txt
	db 7
	hex de df e7 e3 e1 ef f3

	; demi-_sexual
img21_nt_at0
	hex 10 01 9f03 8100 01 9e03 8200 01 9d03 8300 01 9c03 8400
	hex 01 8703 00
img21_nt_at1
	hex 03 14 8500 8110 1a 8600 8110 19 8700 8110 18 8800 8110
	hex 0f 00
img21_nt_at2
	hex 00 8803 09 8110 9603 0a 8107 9501 0b 8107 9401 0b 8106
	hex 9401 04 00
img21_nt_at3
	hex 00 06 8106 9501 09 810d 9602 08 810d 9702 07 810d 9802
	hex 06 810d 8902 00
img21_nt_at4
	hex 02 10 8500 810d 1a 8400 810d 1b 8300 810d 1c 8200 810d
	hex 19 00
img21_nt_at5
	hex 02 04 8100 810d 1e 810d 1f c000 00
img21_pt
	db 0
img21_pal
	hex 0f041030 0f0f0f0f 0f0f0f0f 0f0f0f0f
img21_txt
	db 13
	hex de df e7 e3 d0 00 00 ed df f2 ef db e6

	; dis-_ability
img22_nt_at0
	hex 17 01 8102 812a 8103 811f 8101 01 8102 810e 9700 8101 01
	hex 8102 812a 8103 811f 8101 01 8102 810e 9600 8108 8101 01 8102
	hex 812a 8103 811f 8101 01 8102 810e 9600 8108 8101 01 8102 812a
	hex 8103 811f 8101 01 8102 810e 9600 8108 8101 01 8102 812a 8103
	hex 811f 8101 01 8102 00
img22_nt_at1
	hex 01 810e 9600 8108 01 8117 8102 812a 8103 811f 01 8117 8102
	hex 810e 9600 8108 01 8117 8102 812a 8103 811f 01 8117 8102 810e
	hex 9600 8108 01 8117 8102 812a 8103 811f 01 8117 8102 810e 9600
	hex 8108 01 8117 8102 812a 8103 811f 01 8117 8102 810e 8700 00
img22_nt_at2
	hex 01 8f00 8108 01 8117 8102 812a 8103 811f 01 8117 8102 810e
	hex 9600 8108 01 8117 8102 812a 8103 811f 01 8117 8102 810e 9600
	hex 8108 01 8117 8102 812a 8103 811f 01 8117 8102 810e 9600 8108
	hex 01 8117 8102 812a 8103 811f 01 8117 8102 810e 8f00 00
img22_nt_at3
	hex 01 8700 8108 01 8117 8102 812a 8103 811f 01 8117 8102 810e
	hex 9600 8108 01 8117 8102 812a 8103 811f 01 8117 8102 810e 9600
	hex 8108 01 8117 8102 812a 8103 811f 01 8117 8102 810e 9600 8108
	hex 01 8117 8102 812a 8103 811f 01 8117 8102 810e 9600 8108 00
img22_nt_at4
	hex 01 01 8117 8102 812a 8103 811f 01 8117 8102 810e 9600 8108
	hex 01 8117 8102 812a 8103 811f 01 8117 8102 810e 9600 8108 01
	hex 8117 8102 812a 8103 811f 01 8117 8102 810e 9600 8108 01 8117
	hex 8102 812a 8103 811f 01 8117 8102 810e 9600 8108 01 8117 8102
	hex 812a 8103 811f 01 8117 00
img22_nt_at5
	hex 00 8102 810e 16 8108 8101 8117 8102 812a 8103 811f 8101 8117
	hex 8102 810e 16 8108 8101 8117 8102 812a 8103 811f 8101 8117 8102
	hex 810e 08 8150 07 8145 8151 07 8145 8151 07 8145 8151 07
	hex 8145 8151 07 8145 8151 07 8105 8101 01 00
img22_pt
	db 0
img22_pal
	hex 0f212a30 0f262830 0f0f0f0f 0f0f0f0f
img22_txt
	db 12
	hex de e3 ed d0 00 db dc e3 e6 e3 ee f3

	; gay_men
img23_nt_at0
	hex 01 60 a014 8c02 00
img23_nt_at1
	hex 02 34 a025 a003 18 00
img23_nt_at2
	hex 02 28 a028 c003 8424 00
img23_nt_at3
	hex 24 1c c001 a003 9029 00
img23_nt_at4
	hex 29 10 c002 a01a 9c01 00
img23_nt_at5
	hex 00 c401 08 8850 8855 88a5 88aa 880a 10 00
img23_pt
	db 0
img23_pal
	hex 0f031222 0f0b1b2b 0f222b30 0f0f0f0f
img23_txt
	db 11
	hex e1 db f3 00 00 00 00 00 e7 df e8

	; gender-_fluid
img24_nt_at0
	hex 02 7f 01 8c26 00
img24_nt_at1
	hex 26 14 f803 00
img24_nt_at2
	hex 03 08 a023 e401 00
img24_nt_at3
	hex 01 1c a00a d000 00
img24_nt_at4
	hex 00 30 a005 bc01 00
img24_nt_at5
	hex 01 44 b000 8855 8805 00
img24_pt
	db 0
img24_pal
	hex 0f142530 0f020f0f 0f0f0f0f 0f0f0f0f
img24_txt
	db 15
	hex e1 df e8 de df ec d0 00 00 00 e0 e6 ef e3 de

	; gender-_queer
img25_nt_at0
	hex 01 7f 0d 00
img25_nt_at1
	hex 01 74 9803 00
img25_nt_at2
	hex 03 7f 0d 00
img25_nt_at3
	hex 03 5c b002 00
img25_nt_at4
	hex 02 7f 0d 00
img25_nt_at5
	hex 02 44 c000 00
img25_pt
	db 0
img25_pal
	hex 0f131930 0f0f0f0f 0f0f0f0f 0f0f0f0f
img25_txt
	db 15
	hex e1 df e8 de df ec d0 00 00 00 eb ef df df ec

	; intersex
img26_nt_at0
	hex 01 7f 0d 00
img26_nt_at1
	hex 01 61 810e 8115 8125 8139 8119 810f 19 811b 8102 814d 8149
	hex 8148 814b 8102 812d 04 00
img26_nt_at2
	hex 01 13 8112 8102 8143 812c 02 811a 8141 8102 8116 16 8123
	hex 8145 812c 04 811a 8144 8137 16 812a 8136 06 8122 813e 16
	hex 814e 8135 06 8121 814f 0f 00
img26_nt_at3
	hex 01 07 8129 8138 810d 04 810c 8124 813d 16 8120 8102 812d
	hex 810d 02 810c 811b 8102 8134 17 8141 8102 8131 8111 8110 811d
	hex 8102 8143 19 8126 814a 8150 8152 814c 813a 1d 00
img26_nt_at4
	hex 01 7f 0d 00
img26_nt_at5
	hex 01 44 c000 00
img26_pt
	db 1
img26_pal
	hex 0f28040f 0f0f0f0f 0f0f0f0f 0f0f0f0f
img26_txt
	db 8
	hex e3 e8 ee df ec ed df f2

	; leather
img27_nt_at0
	hex 02 8700 8106 8107 8109 8108 9c00 810b 03 810c 9400 8604 81d4
	hex 05 81d5 9304 8401 8119 8122 8141 05 8163 9601 813c 08 00
img27_nt_at1
	hex 02 8171 9301 8205 81d6 815a 08 81d7 9305 8200 810a 09 810e
	hex 9600 810f 08 810d 9300 8301 813e 818f 06 8199 8c01 00
img27_nt_at2
	hex 01 0c 813b 817d 818d 8198 819a 81a1 81a2 8178 14 a0a5 c003
	hex 84ab 00
img27_nt_at3
	hex ab 1c c001 b000 00
img27_nt_at4
	hex 00 10 a004 c001 9c05 00
img27_nt_at5
	hex 00 8405 7f 01 00
img27_pt
	db 4
img27_pal
	hex 0f011530 0f0f0f0f 0f0f0f0f 0f0f0f0f
img27_txt
	db 7
	hex e6 df db ee e2 df ec

	; lesbian_5stripes
img28_nt_at0
	hex 01 7f 01 8c12 00
img28_nt_at1
	hex 12 14 f802 00
img28_nt_at2
	hex 02 08 a027 e403 00
img28_nt_at3
	hex 03 1c a02c d002 00
img28_nt_at4
	hex 02 30 a018 bc01 00
img28_nt_at5
	hex 00 c401 08 8850 9055 20 00
img28_pt
	db 0
img28_pal
	hex 0f142430 0f172730 0f0f0f0f 0f0f0f0f
img28_txt
	db 15
	hex e6 df ed dc e3 db e8 d6 ed ee ec e3 ea df ed

	; lesbian_5stripes_furry
img29_nt_at0
	hex 02 6c 81be 81b5 8198 8201 8169 81b2 81b9 0c 8af4 81fd 819c
	hex 00
img29_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 816e 81fc 8af4 8903 81ef
	hex 81e5 8141 8168 01 81cf 02 81cd 01 8197 8146 81db 81ee 8903
	hex 08 81f3 81e5 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f
	hex 81db 81f1 10 81e7 814a 02 81a4 8201 815c 818b 8201 8179 02
	hex 814d 81dd 0f 81a5 812d 8172 02 8191 8201 8154 8183 8201 8162
	hex 02 81a0 812f 00
img29_nt_at2
	hex 01 817a 8702 87c2 818f 8157 8102 81bf 81b8 8193 02 815d 818c
	hex 02 8164 81bd 81ba 8102 8186 8160 87c2 08 816b 8102 8182 01
	hex 8174 8135 812e 816c 819b 8130 8131 816d 01 8153 8102 819a 10
	hex 8171 8102 02 815b 8102 81c7 81ad 81a9 81c4 8102 818a 02 8102
	hex 819f 10 817c 8102 813b 02 81d0 8192 02 8163 81ce 02 8139
	hex 8102 81a7 0c 00
img29_nt_at3
	hex 02 8401 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121 815e
	hex 01 819e 8801 87d7 81d6 816a 02 81a1 8176 8601 8175 8173 02
	hex 8199 81d5 87d7 8703 81e9 8152 81c5 01 81a6 8801 817b 01 81c8
	hex 8181 81df 8f03 81d9 816f 01 81a8 8129 8601 8126 817d 01 819d
	hex 81d8 9003 81eb 81d2 81ac 01 8188 812b 8120 8133 00
img29_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 81d1 81e1 9103 81e6 81d2 81ab
	hex 81ca 06 81cc 81af 81d1 81dc 8903 8af6 81ff 8136 815a 81b3 81c3
	hex 81c9 81cb 81c6 81b6 8189 8132 81fa 8af6 0c 814e 8138 8125 8201
	hex 8122 8134 814b 28 00
img29_nt_at5
	hex 00 c402 08 88a0 83aa 820a 83aa 82ff 8101 02 8104 82ff 20
	hex 00
img29_pt
	db 2
img29_pal
	hex 0f301424 0f301427 0f301727 0f30270f
img29_txt
	db 23
	hex e6 df ed dc e3 db e8 d6 ed ee ec e3 ea df ed 00 00 00 e0 ef ec ec
	hex f3

	; lesbian_7stripes
img30_nt_at0
	hex 01 60 a014 8c02 00
img30_nt_at1
	hex 02 34 a025 a003 18 00
img30_nt_at2
	hex 02 28 a028 c003 8424 00
img30_nt_at3
	hex 24 1c c001 a003 9029 00
img30_nt_at4
	hex 29 10 c002 a01a 9c01 00
img30_nt_at5
	hex 00 c401 08 8850 8855 88a5 88aa 880a 10 00
img30_pt
	db 0
img30_pal
	hex 0f041424 0f071727 0f242730 0f0f0f0f
img30_txt
	db 15
	hex e6 df ed dc e3 db e8 d8 ed ee ec e3 ea df ed

	; non-_binary
img31_nt_at0
	hex 02 7f 0d 00
img31_nt_at1
	hex 02 34 d803 00
img31_nt_at2
	hex 03 68 a401 00
img31_nt_at3
	hex 01 7f 0d 00
img31_nt_at4
	hex 01 10 fc00 00
img31_nt_at5
	hex 00 7f 05 00
img31_pt
	db 0
img31_pal
	hex 0f132830 0f0f0f0f 0f0f0f0f 0f0f0f0f
img31_txt
	db 12
	hex e8 e9 e8 d0 00 00 dc e3 e8 db ec f3

	; non-_binary_furry
img32_nt_at0
	hex 02 6c 81be 81b5 8198 8201 8169 81b2 81b9 16 81f2 81ec 00
img32_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 81e2 81f0 13 81b7 81e5
	hex 8141 8168 01 81cf 02 81cd 01 8197 8146 81db 81b4 09 8a01
	hex 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f 9301 814a 02
	hex 81a4 8201 815c 818b 8201 8179 02 814d 9101 812d 8172 02 8191
	hex 8201 8154 8183 8201 8162 02 81a0 812f 00
img32_nt_at2
	hex 01 10 8157 8102 81bf 81b8 8193 02 815d 818c 02 8164 81bd
	hex 81ba 8102 8186 10 816b 8102 8182 01 8174 8135 812e 816c 819b
	hex 8130 8131 816d 01 8153 8102 819a 10 8171 8102 02 815b 8102
	hex 81c7 81ad 81a9 81c4 8102 818a 02 8102 819f 08 8702 01 817c
	hex 8102 813b 02 81d0 8192 02 8163 81ce 02 8139 8102 81a7 01
	hex 8b02 00
img32_nt_at3
	hex 02 03 814c 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121
	hex 815e 01 819e 8149 0e 8184 816a 02 81a1 8176 8601 8175 8173
	hex 02 8199 8155 0e 8194 8152 81c5 01 81a6 8801 817b 01 81c8
	hex 8181 8165 0f 8145 816f 01 81a8 8129 8601 8126 817d 01 819d
	hex 8140 10 8195 812a 81ac 01 8188 812b 8120 8133 00
img32_nt_at4
	hex 00 8137 8123 8128 8159 8102 81b0 8127 8166 8802 09 810f 811c
	hex 81ab 81ca 8602 81cc 81af 811d 8114 13 810e 8119 815a 81b3 81c3
	hex 81c9 81cb 81c6 81b6 8189 811b 8113 16 8116 8118 811e 8201 811f
	hex 811a 8117 28 00
img32_nt_at5
	hex 00 4c 8850 8255 8115 8205 8145 8255 28 00
img32_pt
	db 2
img32_pal
	hex 0f301328 0f30280f 0f0f0f0f 0f0f0f0f
img32_txt
	db 20
	hex e8 e9 e8 d0 00 00 dc e3 e8 db ec f3 00 00 00 e0 ef ec ec f3

	; omni-_sexual
img33_nt_at0
	hex 02 7f 01 8c1b 00
img33_nt_at1
	hex 1b 14 f801 00
img33_nt_at2
	hex 01 08 a00b e400 00
img33_nt_at3
	hex 00 1c a004 d001 00
img33_nt_at4
	hex 01 30 a015 bc02 00
img33_nt_at5
	hex 00 c402 08 8850 9055 20 00
img33_pt
	db 0
img33_pal
	hex 0f22320f 0f25350f 0f0f0f0f 0f0f0f0f
img33_txt
	db 13
	hex e9 e7 e8 e3 d0 00 00 ed df f2 ef db e6

	; otherkin
img34_nt_at0
	hex 02 7f 0d 00
img34_nt_at1
	hex 01 8102 81a5 81a2 81c1 81c0 81a0 81a4 9802 81a3 819b 8196 01
	hex 8173 814b 01 818e 819a 81a1 9502 819e 8197 02 8180 8153 8129
	hex 817f 02 818f 819c 9302 819f 8194 02 817e 816e 812c 8156 8145
	hex 817d 02 818c 819d 8902 0c 8176 810c 8110 815b 8132 8112 810e
	hex 8175 04 00
img34_nt_at2
	hex 01 13 8172 8125 8167 8136 8154 812b 815f 813e 8150 814a 15
	hex 817c 814e 811b 810a 8149 812a 8155 8171 810b 8115 8126 817b 14
	hex 816f 8135 8164 8128 8160 8104 8107 8137 8152 813b 815e 8146 14
	hex 815c 8147 8124 8163 8108 8140 8169 8105 813a 814f 816d 8133 0e
	hex 00
img34_nt_at3
	hex 01 06 815d 8143 8111 8141 815a 813d 8166 8130 816a 8113 8131
	hex 8134 14 8168 8117 8122 8121 8114 811e 8118 811a 8120 8122 811d
	hex 813f 13 8182 8159 8123 8178 8174 812f 8116 811c 8158 814c 817a
	hex 814d 812e 8181 09 8802 8198 81bf 812d 8162 8127 8161 8106 8144
	hex 816c 8109 8138 8151 8139 8157 81be 8190 9102 8195 02 816b 810f
	hex 813c 8177 00
img34_nt_at4
	hex 01 8179 8165 810d 8142 02 818d 9302 8192 03 8170 811f 8119
	hex 8148 03 818a 9502 8193 8184 06 8183 818b 9702 8199 8189 8187
	hex 8285 8186 8188 8191 a802 00
img34_nt_at5
	hex 00 c402 28 8250 8110 02 8140 8250 8355 8151 8154 8355 8805
	hex 00
img34_pt
	db 5
img34_pal
	hex 0f301b0f 0f30030f 0f0f0f0f 0f0f0f0f
img34_txt
	db 8
	hex e9 ee e2 df ec e5 e3 e8

	; pan-_sexual
img35_nt_at0
	hex 01 7f 0d 00
img35_nt_at1
	hex 01 74 9803 00
img35_nt_at2
	hex 03 7f 0d 00
img35_nt_at3
	hex 03 5c b002 00
img35_nt_at4
	hex 02 7f 0d 00
img35_nt_at5
	hex 02 44 c000 00
img35_pt
	db 0
img35_pal
	hex 0f152128 0f0f0f0f 0f0f0f0f 0f0f0f0f
img35_txt
	db 12
	hex ea db e8 d0 00 00 ed df f2 ef db e6

	; pan-_sexual_furry1
img36_nt_at0
	hex 01 7f 0d 00
img36_nt_at1
	hex 01 41 815c 8152 8153 8156 8150 8159 19 8157 8137 8100 8126
	hex 8140 8100 811f 8155 18 8145 8200 8121 8139 8200 812a 04 00
img36_nt_at2
	hex 00 9201 815c 8158 8142 02 8124 813c 02 8128 815b 8159 9401
	hex 8138 01 812f 8111 8107 812c 8146 810b 810e 812d 01 8120 9401
	hex 02 8123 8101 815f 814f 814d 815e 8101 813b 02 9401 8114 02
	hex 8161 8141 02 8127 8160 02 8113 8e01 00
img36_nt_at3
	hex 01 06 813d 8105 8116 8149 8400 8133 8118 8104 8125 15 8148
	hex 8132 8600 8130 812e 16 814a 8800 8134 16 814b 8110 8600 810d
	hex 8136 17 8144 8112 8108 8117 00
img36_nt_at4
	hex 01 8119 810c 810f 8129 7f 09 00
img36_nt_at5
	hex a5 c401 9800 8850 8855 03 81a1 81a4 03 88aa 880a 00
img36_pt
	db 3
img36_pal
	hex 0f150f0f 0f280f0f 0f210f0f 0f0f0f0f
img36_txt
	db 20
	hex ea db e8 d0 00 00 ed df f2 ef db e6 00 00 e0 ef ec ec f3 d2

	; pan-_sexual_furry2
img37_nt_at0
	hex 02 6c 81be 81b5 8198 8201 8169 81b2 81b9 16 81c0 819c 00
img37_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 816e 81bb 13 81b7 8180
	hex 8141 8168 01 81cf 02 81cd 01 8197 8146 8151 81b4 11 81c1
	hex 8180 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f 8151 81bc
	hex 10 818e 814a 02 81a4 8201 815c 818b 8201 8179 02 814d 815f
	hex 0f 81a5 812d 8172 02 8191 8201 8154 8183 8201 8162 02 81a0
	hex 812f 00
img37_nt_at2
	hex 02 817a 0e 8190 8157 01 81bf 81b8 8193 8201 815d 818c 8201
	hex 8164 81bd 81ba 01 8186 8161 0e 817e 816b 01 8182 8101 8174
	hex 8135 812e 816c 819b 8130 8131 816d 8101 8153 01 819a 814f 0e
	hex 8101 8171 01 8201 815b 01 81c7 81ad 81a9 81c4 01 818a 8201
	hex 01 819f 8101 0e 8101 817c 01 813b 8201 81d0 8192 8201 8163
	hex 81ce 8201 8139 01 81a7 8101 0b 00
img37_nt_at3
	hex 02 03 8143 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121
	hex 815e 01 819e 813e 0e 8185 816a 02 81a1 8176 8601 8175 8173
	hex 02 8199 8156 0e 8194 8152 81c5 01 81a6 8801 817b 01 81c8
	hex 8181 8165 0f 81d9 816f 01 81a8 8129 8601 8126 817d 01 819d
	hex 81d8 10 81eb 81d2 81ac 01 8188 812b 8120 8133 00
img37_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 81d1 81e1 11 8187 81d2 81ab
	hex 81ca 06 81cc 81af 81d1 8158 13 81ea 81d4 815a 81b3 81c3 81c9
	hex 81cb 81c6 81b6 8189 81d3 81e0 16 814e 8138 8125 8201 8122 8134
	hex 814b 28 00
img37_nt_at5
	hex 00 c402 18 82a0 04 82a0 82aa 04 82aa 825a 04 825a 8255
	hex 8151 8250 8154 8255 8805 00
img37_pt
	db 2
img37_pal
	hex 0f301521 0f30210f 0f30280f 0f0f0f0f
img37_txt
	db 20
	hex ea db e8 d0 00 00 ed df f2 ef db e6 00 00 e0 ef ec ec f3 d3

	; poly-_amory1
img38_nt_at0
	hex 01 7f 0d 00
img38_nt_at1
	hex 01 74 9802 00
img38_nt_at2
	hex 02 15 81ad 81b0 81b3 81b2 81ae 81b4 81b8 19 81bf 81ce 81cd
	hex 81cc 81d2 81d0 81c2 19 81c1 81af 81ca 81b6 81c9 1c 81bb 81c6
	hex 81ba 81c7 12 00
img38_nt_at3
	hex 02 0a 81be 81c4 81bc 81c8 81b5 1b 81c0 81c3 81b9 81d1 81c5
	hex 2d b000 00
img38_nt_at4
	hex 00 7f 0d 00
img38_nt_at5
	hex 00 7f 05 00
img38_pt
	db 4
img38_pal
	hex 0f021628 0f0f0f0f 0f0f0f0f 0f0f0f0f
img38_txt
	db 13
	hex ea e9 e6 f3 d0 00 00 db e7 e9 ec f3 d2

	; poly-_amory2
img39_nt_at0
	hex 02 7f 0a 81e4 81d2 81ca 00
img39_nt_at1
	hex 02 81cb 81d9 04 81dd 81d1 81ca 81cc 81e2 11 81e0 81b4 8101
	hex 815b 8159 8177 81c2 81db 81df 81c4 819d 8154 815b 8101 818f 81dc
	hex 10 81bb 8101 8185 01 81b9 8171 815a 8189 81af 8155 816d 8194
	hex 01 81ab 8101 8197 10 81b0 8179 81e1 03 81ad 8164 8161 8187
	hex 03 81e1 819f 818a 0f 81d3 81a7 8201 8188 81c6 81da 01 81b2
	hex 818c 01 81de 81c7 81ae 8201 8181 00
img39_nt_at2
	hex 02 81cd 0d 81d6 81a1 8157 8101 8172 8169 815a 817f 81c8 02
	hex 81c9 81a5 8155 8168 816e 8101 8157 817b 81d0 0c 81b6 815c 818e
	hex 8101 8198 01 81b3 8167 8101 81c3 81c5 8101 8166 818d 01 81bc
	hex 8101 8195 815e 8191 0c 81a9 817a 01 8175 8182 02 81c0 8170
	hex 8201 816c 819c 02 81a8 8173 01 81a0 8183 0c 81a3 817c 01
	hex 81b1 8101 819b 01 81e5 81be 8201 819a 81e3 01 81bf 8101 818b
	hex 01 81a2 817d 0a 00
img39_nt_at3
	hex 02 02 81aa 8178 81cf 01 816f 8180 81d8 81ba 8101 8174 8176
	hex 8101 8196 81d7 81a6 816b 01 81d5 819e 8184 0c 81bd 8163 8190
	hex 81ce 81b7 8201 815d 817e 02 81a4 815f 8201 8192 81d4 81b5 8160
	hex 8199 0d 81ac 8165 8201 8156 8101 8193 04 81b8 8101 8158 8201
	hex 8162 8186 07 8900 8223 8100 8125 8122 8108 8200 8107 8116 8126
	hex 8100 8223 9500 810c 812a 8120 8106 00
img39_nt_at4
	hex 00 8105 8115 812d 8117 19 810d 812f 811f 8113 8131 8118 1b
	hex 810e 8134 8136 811a 1d 8111 811b 2b 00
img39_nt_at5
	hex 00 5c 8850 8855 8805 10 00
img39_pt
	db 6
img39_pal
	hex 0f28020f 0f28160f 0f0f0f0f 0f0f0f0f
img39_txt
	db 13
	hex ea e9 e6 f3 d0 00 00 db e7 e9 ec f3 d3

	; poly-_amory3
img40_nt_at0
	hex 03 08 81a6 9701 09 81a6 9601 0a 81a6 9501 04 81bc 81b9
	hex 81ba 81bd 03 81a6 9401 03 81b7 8302 81ad 81bb 03 00
img40_nt_at1
	hex 03 81a6 9301 03 81b3 8402 81ad 81bb 03 81a6 9201 03 81b2
	hex 8502 81ad 81bb 03 81a6 9101 03 81b5 8602 81ad 81bb 03 81a6
	hex 9001 03 81b8 8602 81aa 81af 03 81b6 8802 00
img40_nt_at2
	hex 03 8802 03 81b3 8502 81a8 81af 03 81b6 9102 03 81b1 8402
	hex 81a8 81ae 03 81b6 9202 03 81b4 8302 81a8 81ae 03 81b6 9302
	hex 04 81ac 81a9 81ab 81b0 03 81b6 9402 04 00
img40_nt_at3
	hex 03 06 81b6 9502 09 81b6 9602 08 81b6 9702 07 81a7 9801
	hex 06 81a7 8901 00
img40_nt_at4
	hex 01 10 8503 81a7 1a 8403 81a7 1b 8303 81a7 1c 8203 81a7
	hex 19 00
img40_nt_at5
	hex 01 04 8103 81a7 1e 81a7 1f 8a00 8650 8140 8155 8114 8555
	hex 8144 8255 8104 8405 8104 8155 01 9d00 00
img40_pt
	db 5
img40_pal
	hex 0f031530 0f212830 0f0f0f0f 0f0f0f0f
img40_txt
	db 13
	hex ea e9 e6 f3 d0 00 00 db e7 e9 ec f3 d4

	; poly-_sexual
img41_nt_at0
	hex 01 7f 0d 00
img41_nt_at1
	hex 01 74 9803 00
img41_nt_at2
	hex 03 7f 0d 00
img41_nt_at3
	hex 03 5c b002 00
img41_nt_at4
	hex 02 7f 0d 00
img41_nt_at5
	hex 02 44 c000 00
img41_pt
	db 0
img41_pal
	hex 0f14212b 0f0f0f0f 0f0f0f0f 0f0f0f0f
img41_txt
	db 13
	hex ea e9 e6 f3 d0 00 00 ed df f2 ef db e6

	; queer
img42_nt_at0
	hex 00 40 a00c ac02 00
img42_nt_at1
	hex 02 14 a019 c001 18 00
img42_nt_at2
	hex 02 28 a027 c003 8422 00
img42_nt_at3
	hex 22 1c f001 00
img42_nt_at4
	hex 01 10 a013 c002 9c0f 00
img42_nt_at5
	hex 00 840f 58 88a0 88aa 885a 8855 08 00
img42_pt
	db 0
img42_pal
	hex 0f21310f 0f26350f 0f282930 0f0f0f0f
img42_txt
	db 5
	hex eb ef df df ec

	; rainbow_6stripes
img43_nt_at0
	hex 03 7f 01 8c02 00
img43_nt_at1
	hex 02 74 9803 00
img43_nt_at2
	hex 03 68 a401 00
img43_nt_at3
	hex 01 5c b002 00
img43_nt_at4
	hex 02 50 bc01 00
img43_nt_at5
	hex 00 c401 10 8850 9055 8805 10 00
img43_pt
	db 0
img43_pal
	hex 0f041216 0f192728 0f0f0f0f 0f0f0f0f
img43_txt
	db 15
	hex ec db e3 e8 dc e9 f1 d7 ed ee ec e3 ea df ed

	; rainbow_7stripes
img44_nt_at0
	hex 01 60 a014 8c02 00
img44_nt_at1
	hex 02 34 a025 a003 18 00
img44_nt_at2
	hex 02 28 a018 c001 841d 00
img44_nt_at3
	hex 1d 1c e003 9021 00
img44_nt_at4
	hex 21 10 c001 a013 9c02 00
img44_nt_at5
	hex 00 c402 08 8850 8855 88a5 88aa 18 00
img44_pt
	db 0
img44_pal
	hex 0f03042c 0f162728 0f19282c 0f0f0f0f
img44_txt
	db 15
	hex ec db e3 e8 dc e9 f1 d8 ed ee ec e3 ea df ed

	; rainbow_8stripes
img45_nt_at0
	hex 02 60 ac01 00
img45_nt_at1
	hex 01 7f 0d 00
img45_nt_at2
	hex 01 08 e002 24 00
img45_nt_at3
	hex 01 3c d002 00
img45_nt_at4
	hex 02 10 e001 1c 00
img45_nt_at5
	hex 00 c402 08 8850 8855 88ff 88af 88aa 10 00
img45_pt
	db 0
img45_pal
	hex 0f03040f 0f16250f 0f192c0f 0f27280f
img45_txt
	db 15
	hex ec db e3 e8 dc e9 f1 d9 ed ee ec e3 ea df ed

	; rainbow_furry1
img46_nt_at0
	hex 02 8193 01 819b 8103 8193 01 819a 01 8189 8101 811a 9500
	hex 8101 8193 01 819b 8101 8193 8103 819a 01 8189 8101 811a 9400
	hex 814e 8101 8193 01 819b 8103 8193 01 819a 01 8189 8101 814c
	hex 811b 8115 8105 9100 814e 8101 8193 01 819b 8101 8193 8103 819a
	hex 01 818a 8185 8184 8101 813e 810a 9100 814e 8101 8193 01 819b
	hex 8103 8193 01 81af 8178 00
img46_nt_at1
	hex 00 8179 817a 818f 8183 8143 8106 11 814e 8101 8193 8102 819b
	hex 8101 8193 8180 81ab 81ae 8169 8102 8191 8101 813a 12 814e 8101
	hex 8193 8102 81b1 8182 8109 8164 816f 8163 81b0 817b 8188 8147 13
	hex 814e 8101 8195 8173 817e 813f 819e 8174 816a 817f 816b 8190 814c
	hex 14 8160 818d 8172 817c 8131 02 816d 817d 8168 8192 8101 811a
	hex 05 00
img46_nt_at2
	hex 00 0e 8135 818c 8177 81ac 8137 02 8165 8181 81ad 8102 8189
	hex 8101 811a 12 812b 8101 8194 8170 04 8166 8102 819a 8102 8189
	hex 8101 811a 11 811c 8154 818b 81a3 8362 81aa 811d 8193 8103 819a
	hex 8102 8189 8101 811a 11 8122 815a 8101 818e 8196 8198 8102 819b
	hex 8103 8193 8102 819a 8102 8189 8101 811a 0d 00
img46_nt_at3
	hex 01 8400 811e 8151 815d 8160 01 8193 8102 819b 01 8193 8103
	hex 819a 8102 8189 01 811a 9400 814e 01 8193 8102 819b 8103 8193
	hex 8102 819a 8102 8189 01 811a 9400 814e 01 8193 8102 819b 01
	hex 8193 8103 819a 8102 8189 01 811a 9400 814e 01 8193 8102 819b
	hex 8103 8193 8102 819a 8102 8189 01 811a 9400 814e 00
img46_nt_at4
	hex 01 01 8193 8102 819b 01 8193 8103 819a 8102 8189 01 811a
	hex 9400 814e 01 8193 8102 819b 8103 8193 8102 819a 8102 8189 01
	hex 811a 9400 814e 01 8193 8102 819b 01 8193 8103 819a 8102 8189
	hex 01 811a 9400 814e 01 8193 8102 819b 8103 8193 8102 819a 8102
	hex 8189 01 811a 9400 814e 01 8193 8102 819b 01 8193 8103 819a
	hex 00
img46_nt_at5
	hex 00 8102 8189 8101 811a 14 814e 8101 8193 8102 819b 8103 8193
	hex 8102 819a 8102 8189 8101 15 814e 8101 8193 8102 819b 8101 8193
	hex 8103 819a 8102 8189 09 8160 8150 06 8108 8165 8155 8111 05
	hex 8188 8166 8151 06 8108 8165 8151 06 8108 8165 8151 06 8108
	hex 8165 8151 06 8108 8105 00
img46_pt
	db 3
img46_pal
	hex 0f04111b 0f162728 0f1b280f 0f0f0f0f
img46_txt
	db 15
	hex ec db e3 e8 dc e9 f1 00 00 e0 ef ec ec f3 d2

	; rainbow_furry2
img47_nt_at0
	hex 02 6c 81be 81b5 8198 8201 8169 81b2 81b9 0c 8a03 81f2 81ec
	hex 00
img47_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 81e2 81f0 9303 81ef 81e5
	hex 8141 8168 01 81cf 02 81cd 01 8197 8146 81db 81ee 9103 81f3
	hex 81e5 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f 81db 81f1
	hex 9003 81e7 814a 02 81a4 8201 815c 818b 8201 8179 02 814d 81dd
	hex 8f03 81ed 812d 8172 02 8191 8201 8154 8183 8201 8162 02 81a0
	hex 812f 00
img47_nt_at2
	hex 01 81e3 8e03 81e8 8157 8102 81bf 81b8 8193 02 815d 818c 02
	hex 8164 81bd 81ba 8102 8186 81de 8e03 81e4 816b 8102 8182 01 8174
	hex 8135 812e 816c 819b 8130 8131 816d 01 8153 8102 819a 81da 8e03
	hex 01 8171 8102 02 815b 8102 81c7 81ad 81a9 81c4 8102 818a 02
	hex 8102 819f 01 8703 8702 01 817c 8102 813b 02 81d0 8192 02
	hex 8163 81ce 02 8139 8102 81a7 01 8b02 00
img47_nt_at3
	hex 02 03 8143 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121
	hex 815e 01 819e 813e 0e 8185 816a 02 81a1 8176 8601 8175 8173
	hex 02 8199 8156 0e 8194 8152 81c5 01 81a6 8801 817b 01 81c8
	hex 8181 8165 07 8803 81d9 816f 01 81a8 8129 8601 8126 817d 01
	hex 819d 81d8 9003 81eb 81d2 81ac 01 8188 812b 8120 8133 00
img47_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 81d1 81e1 9103 81e6 81d2 81ab
	hex 81ca 06 81cc 81af 81d1 81dc 9303 81ea 81d4 815a 81b3 81c3 81c9
	hex 81cb 81c6 81b6 8189 81d3 81e0 8a03 0c 814e 8138 8125 8201 8122
	hex 8134 814b 28 00
img47_nt_at5
	hex 00 c402 08 88a0 880a 82a0 04 82a0 82fa 04 82fa 825f 8110
	hex 02 8140 825f 8305 02 8305 08 00
img47_pt
	db 2
img47_pal
	hex 0f300427 0f300412 0f301628 0f30190f
img47_txt
	db 15
	hex ec db e3 e8 dc e9 f1 00 00 e0 ef ec ec f3 d3

	; rainbow_progress
img48_nt_at0
	hex 02 812d 8101 8106 8100 8109 1c 812d 8101 8106 8100 8109 1a
	hex 8156 01 812d 8101 8106 8100 8109 19 8103 8156 01 812d 8101
	hex 8106 8100 8109 18 8156 01 8156 01 812d 8101 8106 8100 8105
	hex 8301 00
img48_nt_at1
	hex 01 14 8103 8156 8103 8156 8102 812d 01 8106 8100 8105 16
	hex 8203 8156 8102 8156 8102 812d 01 8106 8100 8105 15 8303 8156
	hex 8103 8156 8102 812d 01 8106 8100 8105 14 8403 8156 8102 8156
	hex 8102 812d 01 8106 8100 8109 8b02 00
img48_nt_at2
	hex 02 08 8503 8156 8103 8156 01 812d 8101 8106 8100 8109 12
	hex 8603 8156 01 8156 01 812d 8101 8106 8100 8109 11 8703 8156
	hex 8103 8156 01 812d 8101 8106 8100 8109 10 8703 8157 8103 8157
	hex 01 8143 8101 8107 8100 810a 9403 00
img48_nt_at3
	hex 57 8203 01 8102 01 8102 8143 8101 8107 8100 810a 9603 01
	hex 8103 01 8102 8143 8101 8107 8100 810a 9603 01 8102 01 8102
	hex 8143 8101 8107 8100 810a 9603 01 8103 01 8102 8143 8101 8107
	hex 8100 8104 9401 8203 01 8102 01 8102 8143 8101 8107 8100 8104
	hex 8501 00
img48_nt_at4
	hex 01 10 8103 8157 8103 8157 8102 8143 01 8107 8100 8104 16
	hex 8157 8102 8157 8102 8143 01 8107 8100 8104 17 8103 8157 8102
	hex 8143 01 8107 8100 8104 18 8157 8102 8143 01 8107 8100 8104
	hex 15 00
img48_nt_at5
	hex 01 04 8102 8143 01 8107 8100 8104 1a 8143 01 8107 8100
	hex 8104 1b 8900 87a0 8110 8108 86fa 8155 8110 810c 85ff 8255 8100
	hex 818c 84af 8155 01 8180 85aa 01 8140 865a 8100 8705 00
img48_pt
	db 1
img48_pal
	hex 0f082125 0f042530 0f121619 0f27280f
img48_txt
	db 15
	hex ec db e3 e8 dc e9 f1 ea ec e9 e1 ec df ed ed

	; rainbow_progress_intersex
img49_nt_at0
	hex 56 01 8102 01 8102 812d 8101 8106 8100 8105 9701 8103 01
	hex 8103 01 8102 812d 8101 8106 8100 8105 9601 8155 8103 01 8102
	hex 01 8102 812d 8101 8106 8100 8105 9501 8102 8155 8103 01 8103
	hex 01 8102 812d 8101 8106 8100 8105 9401 8202 8155 8103 01 8102
	hex 01 8102 812d 8101 8106 8100 00
img49_nt_at1
	hex 02 810b 9303 03 8155 8103 8156 8103 8156 01 812d 8101 8106
	hex 8100 810b 9203 04 8155 8103 8156 01 8156 01 812d 8101 8106
	hex 8100 810b 9103 05 8155 8103 8156 8103 8156 01 812d 8101 8106
	hex 8100 810b 9003 06 8155 8103 8156 01 8156 01 812d 8101 8106
	hex 8100 8109 07 00
img49_nt_at2
	hex 02 0a 8147 8142 8140 8146 01 8155 8103 8156 8103 8156 01
	hex 812d 8101 8106 8100 8109 0f 813c 8113 812b 813f 8117 8128 01
	hex 8155 8103 8156 01 8156 01 812d 8101 8106 8100 8109 0e 8130
	hex 812b 02 813f 811c 02 8155 8103 8156 8103 8156 01 812d 8101
	hex 8106 8100 8109 0d 812f 8151 02 8153 812e 02 8154 8103 8157
	hex 8103 8157 01 8143 8101 8107 8100 8108 0d 8132 8127 8151 00
img49_nt_at3
	hex 02 8153 813b 811e 01 8154 8103 8157 01 8157 01 8143 8101
	hex 8107 8100 8108 0f 8118 811f 8133 8114 01 8154 8103 8157 8103
	hex 8157 01 8143 8101 8107 8100 8108 14 8154 8103 8157 01 8157
	hex 01 8143 8101 8107 8100 8108 14 8154 8103 8157 8103 8157 01
	hex 8143 8101 8107 8100 8104 9001 04 8154 8103 8157 01 8157 01
	hex 8143 8101 8107 8100 8104 8101 00
img49_nt_at4
	hex 01 10 8302 8154 8103 8157 8103 8157 8102 8143 01 8107 8100
	hex 8104 12 8202 8154 8103 8157 8102 8157 8102 8143 01 8107 8100
	hex 8104 13 8102 8154 8103 8157 8103 8157 8102 8143 01 8107 8100
	hex 8104 14 8154 8103 8157 8102 8157 8102 8143 01 8107 8100 8104
	hex 11 00
img49_nt_at5
	hex 00 8401 8103 8157 8103 8157 8102 8143 8101 8107 01 8104 9601
	hex 8157 8102 8157 8102 8143 8101 8107 01 8104 9701 08 8160 8150
	hex 86f0 8108 8165 815d 85ff 01 8108 8165 815d 840f 02 8188 8155
	hex 81d1 83f0 01 8180 8156 8195 84af 8180 8156 8115 850a 8106 8105
	hex 06 00
img49_pt
	db 1
img49_pal
	hex 0f042830 0f082125 0f122530 0f161927
img49_txt
	db 23
	hex ec db e3 e8 dc e9 f1 ea ec e9 e1 ec df ed ed e3 e8 ee df ec ed df
	hex f2

	; sapphic
img50_nt_at0
	hex 01 7f 0d 00
img50_nt_at1
	hex 01 7f 03 8117 8130 8134 811c 06 00
img50_nt_at2
	hex 01 16 814f 8202 816c 1a 811f 812a 814c 8202 8169 8129 8124
	hex 18 814e 8102 8175 81dd 81df 8157 8102 816b 18 814d 819c 819e
	hex 81de 81e4 819b 819f 816a 10 00
img50_nt_at3
	hex 01 09 8128 8149 8174 8156 8166 812b 1a 8154 8102 8177 8159
	hex 8102 8172 1a 8153 8197 8168 814b 8196 8170 3d 00
img50_nt_at4
	hex 01 7f 0d 00
img50_nt_at5
	hex 00 c401 18 8850 8855 8805 10 00
img50_pt
	db 4
img50_pal
	hex 0f250f0f 0f301327 0f0f0f0f 0f0f0f0f
img50_txt
	db 7
	hex ed db ea ea e2 e3 dd

	; trans-_gender
img51_nt_at0
	hex 01 7f 01 8c12 00
img51_nt_at1
	hex 12 14 f802 00
img51_nt_at2
	hex 02 08 a027 e403 00
img51_nt_at3
	hex 03 1c a02c d002 00
img51_nt_at4
	hex 02 30 a018 bc01 00
img51_nt_at5
	hex 01 44 c000 00
img51_pt
	db 0
img51_pal
	hex 0f212530 0f0f0f0f 0f0f0f0f 0f0f0f0f
img51_txt
	db 14
	hex ee ec db e8 ed d0 00 00 e1 df e8 de df ec

	; trans-_gender_furry1
img52_nt_at0
	hex 02 7f 01 8c99 00
img52_nt_at1
	hex 00 9499 ad01 815c 8152 8153 8156 8150 8159 9901 8157 8137 01
	hex 8126 8140 01 811f 8155 8c01 8c02 8175 02 8167 8171 02 816c
	hex 8402 00
img52_nt_at2
	hex 00 8802 8a97 81a9 81a6 81a5 02 819c 81a4 02 819d 81a8 81a7
	hex 8a97 8a01 8138 01 812f 8111 8107 812c 8146 810b 810e 812d 01
	hex 8120 9401 02 8123 8101 815f 814f 814d 815e 8101 813b 02 9401
	hex 8114 02 8161 8141 02 8127 8160 02 8113 8e01 00
img52_nt_at3
	hex 01 06 813d 8105 8116 8149 8400 8133 8118 8104 8125 0a 8b86
	hex 81a2 81a1 8600 81a0 819f 8b86 8b02 8176 8800 816e 8b02 0b 814b
	hex 8110 8600 810d 8136 17 8144 8112 8108 8117 00
img52_nt_at4
	hex 19 01 810c 810f 8129 ac01 a087 bc02 00
img52_nt_at5
	hex 00 c402 08 8850 8855 8805 08 8850 8855 8805 00
img52_pt
	db 3
img52_pal
	hex 0f30250f 0f25210f 0f0f0f0f 0f0f0f0f
img52_txt
	db 22
	hex ee ec db e8 ed d0 00 00 e1 df e8 de df ec 00 00 e0 ef ec ec f3 d2

	; trans-_gender_furry2
img53_nt_at0
	hex 01 4c 8802 18 81be 81b5 8198 02 8169 81b2 81b9 0c 882c
	hex 82f4 81fd 819c 00
img53_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 816e 81fc 82f4 882c 08
	hex 8103 81ef 81e5 8141 8168 01 81cf 02 81cd 01 8197 8146 81db
	hex 81ee 8103 10 81f3 81e5 8150 02 81ae 8101 8177 81a2 8101 81aa
	hex 02 817f 81db 81f1 10 81e7 814a 02 81a4 8201 815c 818b 8201
	hex 8179 02 814d 81dd 0f 81a5 812d 8172 02 8191 8201 8154 8183
	hex 8201 8162 02 81a0 812f 00
img53_nt_at2
	hex 01 817a 8702 87c2 818f 8157 8102 81bf 81b8 8193 02 815d 818c
	hex 02 8164 81bd 81ba 8102 8186 8160 87c2 08 816b 8102 8182 01
	hex 8174 8135 812e 816c 819b 8130 8131 816d 01 8153 8102 819a 10
	hex 8171 8102 02 815b 8102 81c7 81ad 81a9 81c4 8102 818a 02 8102
	hex 819f 10 817c 8102 813b 02 81d0 8192 02 8163 81ce 02 8139
	hex 8102 81a7 0c 00
img53_nt_at3
	hex 02 8401 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121 815e
	hex 01 819e 8801 873d 813c 816a 02 81a1 8176 8601 8175 8173 02
	hex 8199 813a 873d 07 8194 8152 81c5 01 81a6 8801 817b 01 81c8
	hex 8181 8165 0f 81d9 816f 01 81a8 8129 8601 8126 817d 01 819d
	hex 81d8 10 81eb 81d2 81ac 01 8188 812b 8120 8133 00
img53_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 81d1 81e1 10 8103 81e6 81d2
	hex 81ab 81ca 06 81cc 81af 81d1 81dc 8103 08 88b1 82f6 81ff 8136
	hex 815a 81b3 81c3 81c9 81cb 81c6 81b6 8189 8132 81fa 82f6 88b1 8c01
	hex 814e 8138 8125 8201 8122 8134 814b 9801 08 8801 00
img53_nt_at5
	hex 00 c401 08 88a0 82aa 810a 02 810a 82aa 8255 04 8255 08
	hex 8255 04 8255 82aa 81a0 02 81a0 82aa 880a 00
img53_pt
	db 2
img53_pal
	hex 0f302125 0f30250f 0f21250f 0f0f0f0f
img53_txt
	db 22
	hex ee ec db e8 ed d0 00 00 e1 df e8 de df ec 00 00 e0 ef ec ec f3 d3

