; Image data excluding pattern tables. Generated by convert.py.

image_count equ 66

image_ptrs
	dw img0_ptrs, img1_ptrs, img2_ptrs, img3_ptrs, img4_ptrs
	dw img5_ptrs, img6_ptrs, img7_ptrs, img8_ptrs, img9_ptrs
	dw img10_ptrs, img11_ptrs, img12_ptrs, img13_ptrs, img14_ptrs
	dw img15_ptrs, img16_ptrs, img17_ptrs, img18_ptrs, img19_ptrs
	dw img20_ptrs, img21_ptrs, img22_ptrs, img23_ptrs, img24_ptrs
	dw img25_ptrs, img26_ptrs, img27_ptrs, img28_ptrs, img29_ptrs
	dw img30_ptrs, img31_ptrs, img32_ptrs, img33_ptrs, img34_ptrs
	dw img35_ptrs, img36_ptrs, img37_ptrs, img38_ptrs, img39_ptrs
	dw img40_ptrs, img41_ptrs, img42_ptrs, img43_ptrs, img44_ptrs
	dw img45_ptrs, img46_ptrs, img47_ptrs, img48_ptrs, img49_ptrs
	dw img50_ptrs, img51_ptrs, img52_ptrs, img53_ptrs, img54_ptrs
	dw img55_ptrs, img56_ptrs, img57_ptrs, img58_ptrs, img59_ptrs
	dw img60_ptrs, img61_ptrs, img62_ptrs, img63_ptrs, img64_ptrs
	dw img65_ptrs

img0_ptrs
	dw img0_nt_at0, img0_nt_at1, img0_nt_at2, img0_nt_at3
	dw img0_nt_at4, img0_nt_at5, img0_pt, img0_pal
	dw img0_txt
img1_ptrs
	dw img1_nt_at0, img1_nt_at1, img1_nt_at2, img1_nt_at3
	dw img1_nt_at4, img1_nt_at5, img1_pt, img1_pal
	dw img1_txt
img2_ptrs
	dw img2_nt_at0, img2_nt_at1, img2_nt_at2, img2_nt_at3
	dw img2_nt_at4, img2_nt_at5, img2_pt, img2_pal
	dw img2_txt
img3_ptrs
	dw img3_nt_at0, img3_nt_at1, img3_nt_at2, img3_nt_at3
	dw img3_nt_at4, img3_nt_at5, img3_pt, img3_pal
	dw img3_txt
img4_ptrs
	dw img4_nt_at0, img4_nt_at1, img4_nt_at2, img4_nt_at3
	dw img4_nt_at4, img4_nt_at5, img4_pt, img4_pal
	dw img4_txt
img5_ptrs
	dw img5_nt_at0, img5_nt_at1, img5_nt_at2, img5_nt_at3
	dw img5_nt_at4, img5_nt_at5, img5_pt, img5_pal
	dw img5_txt
img6_ptrs
	dw img6_nt_at0, img6_nt_at1, img6_nt_at2, img6_nt_at3
	dw img6_nt_at4, img6_nt_at5, img6_pt, img6_pal
	dw img6_txt
img7_ptrs
	dw img7_nt_at0, img7_nt_at1, img7_nt_at2, img7_nt_at3
	dw img7_nt_at4, img7_nt_at5, img7_pt, img7_pal
	dw img7_txt
img8_ptrs
	dw img8_nt_at0, img8_nt_at1, img8_nt_at2, img8_nt_at3
	dw img8_nt_at4, img8_nt_at5, img8_pt, img8_pal
	dw img8_txt
img9_ptrs
	dw img9_nt_at0, img9_nt_at1, img9_nt_at2, img9_nt_at3
	dw img9_nt_at4, img9_nt_at5, img9_pt, img9_pal
	dw img9_txt
img10_ptrs
	dw img10_nt_at0, img10_nt_at1, img10_nt_at2, img10_nt_at3
	dw img10_nt_at4, img10_nt_at5, img10_pt, img10_pal
	dw img10_txt
img11_ptrs
	dw img11_nt_at0, img11_nt_at1, img11_nt_at2, img11_nt_at3
	dw img11_nt_at4, img11_nt_at5, img11_pt, img11_pal
	dw img11_txt
img12_ptrs
	dw img12_nt_at0, img12_nt_at1, img12_nt_at2, img12_nt_at3
	dw img12_nt_at4, img12_nt_at5, img12_pt, img12_pal
	dw img12_txt
img13_ptrs
	dw img13_nt_at0, img13_nt_at1, img13_nt_at2, img13_nt_at3
	dw img13_nt_at4, img13_nt_at5, img13_pt, img13_pal
	dw img13_txt
img14_ptrs
	dw img14_nt_at0, img14_nt_at1, img14_nt_at2, img14_nt_at3
	dw img14_nt_at4, img14_nt_at5, img14_pt, img14_pal
	dw img14_txt
img15_ptrs
	dw img15_nt_at0, img15_nt_at1, img15_nt_at2, img15_nt_at3
	dw img15_nt_at4, img15_nt_at5, img15_pt, img15_pal
	dw img15_txt
img16_ptrs
	dw img16_nt_at0, img16_nt_at1, img16_nt_at2, img16_nt_at3
	dw img16_nt_at4, img16_nt_at5, img16_pt, img16_pal
	dw img16_txt
img17_ptrs
	dw img17_nt_at0, img17_nt_at1, img17_nt_at2, img17_nt_at3
	dw img17_nt_at4, img17_nt_at5, img17_pt, img17_pal
	dw img17_txt
img18_ptrs
	dw img18_nt_at0, img18_nt_at1, img18_nt_at2, img18_nt_at3
	dw img18_nt_at4, img18_nt_at5, img18_pt, img18_pal
	dw img18_txt
img19_ptrs
	dw img19_nt_at0, img19_nt_at1, img19_nt_at2, img19_nt_at3
	dw img19_nt_at4, img19_nt_at5, img19_pt, img19_pal
	dw img19_txt
img20_ptrs
	dw img20_nt_at0, img20_nt_at1, img20_nt_at2, img20_nt_at3
	dw img20_nt_at4, img20_nt_at5, img20_pt, img20_pal
	dw img20_txt
img21_ptrs
	dw img21_nt_at0, img21_nt_at1, img21_nt_at2, img21_nt_at3
	dw img21_nt_at4, img21_nt_at5, img21_pt, img21_pal
	dw img21_txt
img22_ptrs
	dw img22_nt_at0, img22_nt_at1, img22_nt_at2, img22_nt_at3
	dw img22_nt_at4, img22_nt_at5, img22_pt, img22_pal
	dw img22_txt
img23_ptrs
	dw img23_nt_at0, img23_nt_at1, img23_nt_at2, img23_nt_at3
	dw img23_nt_at4, img23_nt_at5, img23_pt, img23_pal
	dw img23_txt
img24_ptrs
	dw img24_nt_at0, img24_nt_at1, img24_nt_at2, img24_nt_at3
	dw img24_nt_at4, img24_nt_at5, img24_pt, img24_pal
	dw img24_txt
img25_ptrs
	dw img25_nt_at0, img25_nt_at1, img25_nt_at2, img25_nt_at3
	dw img25_nt_at4, img25_nt_at5, img25_pt, img25_pal
	dw img25_txt
img26_ptrs
	dw img26_nt_at0, img26_nt_at1, img26_nt_at2, img26_nt_at3
	dw img26_nt_at4, img26_nt_at5, img26_pt, img26_pal
	dw img26_txt
img27_ptrs
	dw img27_nt_at0, img27_nt_at1, img27_nt_at2, img27_nt_at3
	dw img27_nt_at4, img27_nt_at5, img27_pt, img27_pal
	dw img27_txt
img28_ptrs
	dw img28_nt_at0, img28_nt_at1, img28_nt_at2, img28_nt_at3
	dw img28_nt_at4, img28_nt_at5, img28_pt, img28_pal
	dw img28_txt
img29_ptrs
	dw img29_nt_at0, img29_nt_at1, img29_nt_at2, img29_nt_at3
	dw img29_nt_at4, img29_nt_at5, img29_pt, img29_pal
	dw img29_txt
img30_ptrs
	dw img30_nt_at0, img30_nt_at1, img30_nt_at2, img30_nt_at3
	dw img30_nt_at4, img30_nt_at5, img30_pt, img30_pal
	dw img30_txt
img31_ptrs
	dw img31_nt_at0, img31_nt_at1, img31_nt_at2, img31_nt_at3
	dw img31_nt_at4, img31_nt_at5, img31_pt, img31_pal
	dw img31_txt
img32_ptrs
	dw img32_nt_at0, img32_nt_at1, img32_nt_at2, img32_nt_at3
	dw img32_nt_at4, img32_nt_at5, img32_pt, img32_pal
	dw img32_txt
img33_ptrs
	dw img33_nt_at0, img33_nt_at1, img33_nt_at2, img33_nt_at3
	dw img33_nt_at4, img33_nt_at5, img33_pt, img33_pal
	dw img33_txt
img34_ptrs
	dw img34_nt_at0, img34_nt_at1, img34_nt_at2, img34_nt_at3
	dw img34_nt_at4, img34_nt_at5, img34_pt, img34_pal
	dw img34_txt
img35_ptrs
	dw img35_nt_at0, img35_nt_at1, img35_nt_at2, img35_nt_at3
	dw img35_nt_at4, img35_nt_at5, img35_pt, img35_pal
	dw img35_txt
img36_ptrs
	dw img36_nt_at0, img36_nt_at1, img36_nt_at2, img36_nt_at3
	dw img36_nt_at4, img36_nt_at5, img36_pt, img36_pal
	dw img36_txt
img37_ptrs
	dw img37_nt_at0, img37_nt_at1, img37_nt_at2, img37_nt_at3
	dw img37_nt_at4, img37_nt_at5, img37_pt, img37_pal
	dw img37_txt
img38_ptrs
	dw img38_nt_at0, img38_nt_at1, img38_nt_at2, img38_nt_at3
	dw img38_nt_at4, img38_nt_at5, img38_pt, img38_pal
	dw img38_txt
img39_ptrs
	dw img39_nt_at0, img39_nt_at1, img39_nt_at2, img39_nt_at3
	dw img39_nt_at4, img39_nt_at5, img39_pt, img39_pal
	dw img39_txt
img40_ptrs
	dw img40_nt_at0, img40_nt_at1, img40_nt_at2, img40_nt_at3
	dw img40_nt_at4, img40_nt_at5, img40_pt, img40_pal
	dw img40_txt
img41_ptrs
	dw img41_nt_at0, img41_nt_at1, img41_nt_at2, img41_nt_at3
	dw img41_nt_at4, img41_nt_at5, img41_pt, img41_pal
	dw img41_txt
img42_ptrs
	dw img42_nt_at0, img42_nt_at1, img42_nt_at2, img42_nt_at3
	dw img42_nt_at4, img42_nt_at5, img42_pt, img42_pal
	dw img42_txt
img43_ptrs
	dw img43_nt_at0, img43_nt_at1, img43_nt_at2, img43_nt_at3
	dw img43_nt_at4, img43_nt_at5, img43_pt, img43_pal
	dw img43_txt
img44_ptrs
	dw img44_nt_at0, img44_nt_at1, img44_nt_at2, img44_nt_at3
	dw img44_nt_at4, img44_nt_at5, img44_pt, img44_pal
	dw img44_txt
img45_ptrs
	dw img45_nt_at0, img45_nt_at1, img45_nt_at2, img45_nt_at3
	dw img45_nt_at4, img45_nt_at5, img45_pt, img45_pal
	dw img45_txt
img46_ptrs
	dw img46_nt_at0, img46_nt_at1, img46_nt_at2, img46_nt_at3
	dw img46_nt_at4, img46_nt_at5, img46_pt, img46_pal
	dw img46_txt
img47_ptrs
	dw img47_nt_at0, img47_nt_at1, img47_nt_at2, img47_nt_at3
	dw img47_nt_at4, img47_nt_at5, img47_pt, img47_pal
	dw img47_txt
img48_ptrs
	dw img48_nt_at0, img48_nt_at1, img48_nt_at2, img48_nt_at3
	dw img48_nt_at4, img48_nt_at5, img48_pt, img48_pal
	dw img48_txt
img49_ptrs
	dw img49_nt_at0, img49_nt_at1, img49_nt_at2, img49_nt_at3
	dw img49_nt_at4, img49_nt_at5, img49_pt, img49_pal
	dw img49_txt
img50_ptrs
	dw img50_nt_at0, img50_nt_at1, img50_nt_at2, img50_nt_at3
	dw img50_nt_at4, img50_nt_at5, img50_pt, img50_pal
	dw img50_txt
img51_ptrs
	dw img51_nt_at0, img51_nt_at1, img51_nt_at2, img51_nt_at3
	dw img51_nt_at4, img51_nt_at5, img51_pt, img51_pal
	dw img51_txt
img52_ptrs
	dw img52_nt_at0, img52_nt_at1, img52_nt_at2, img52_nt_at3
	dw img52_nt_at4, img52_nt_at5, img52_pt, img52_pal
	dw img52_txt
img53_ptrs
	dw img53_nt_at0, img53_nt_at1, img53_nt_at2, img53_nt_at3
	dw img53_nt_at4, img53_nt_at5, img53_pt, img53_pal
	dw img53_txt
img54_ptrs
	dw img54_nt_at0, img54_nt_at1, img54_nt_at2, img54_nt_at3
	dw img54_nt_at4, img54_nt_at5, img54_pt, img54_pal
	dw img54_txt
img55_ptrs
	dw img55_nt_at0, img55_nt_at1, img55_nt_at2, img55_nt_at3
	dw img55_nt_at4, img55_nt_at5, img55_pt, img55_pal
	dw img55_txt
img56_ptrs
	dw img56_nt_at0, img56_nt_at1, img56_nt_at2, img56_nt_at3
	dw img56_nt_at4, img56_nt_at5, img56_pt, img56_pal
	dw img56_txt
img57_ptrs
	dw img57_nt_at0, img57_nt_at1, img57_nt_at2, img57_nt_at3
	dw img57_nt_at4, img57_nt_at5, img57_pt, img57_pal
	dw img57_txt
img58_ptrs
	dw img58_nt_at0, img58_nt_at1, img58_nt_at2, img58_nt_at3
	dw img58_nt_at4, img58_nt_at5, img58_pt, img58_pal
	dw img58_txt
img59_ptrs
	dw img59_nt_at0, img59_nt_at1, img59_nt_at2, img59_nt_at3
	dw img59_nt_at4, img59_nt_at5, img59_pt, img59_pal
	dw img59_txt
img60_ptrs
	dw img60_nt_at0, img60_nt_at1, img60_nt_at2, img60_nt_at3
	dw img60_nt_at4, img60_nt_at5, img60_pt, img60_pal
	dw img60_txt
img61_ptrs
	dw img61_nt_at0, img61_nt_at1, img61_nt_at2, img61_nt_at3
	dw img61_nt_at4, img61_nt_at5, img61_pt, img61_pal
	dw img61_txt
img62_ptrs
	dw img62_nt_at0, img62_nt_at1, img62_nt_at2, img62_nt_at3
	dw img62_nt_at4, img62_nt_at5, img62_pt, img62_pal
	dw img62_txt
img63_ptrs
	dw img63_nt_at0, img63_nt_at1, img63_nt_at2, img63_nt_at3
	dw img63_nt_at4, img63_nt_at5, img63_pt, img63_pal
	dw img63_txt
img64_ptrs
	dw img64_nt_at0, img64_nt_at1, img64_nt_at2, img64_nt_at3
	dw img64_nt_at4, img64_nt_at5, img64_pt, img64_pal
	dw img64_txt
img65_ptrs
	dw img65_nt_at0, img65_nt_at1, img65_nt_at2, img65_nt_at3
	dw img65_nt_at4, img65_nt_at5, img65_pt, img65_pal
	dw img65_txt

	; title_screen
img0_nt_at0
	hex 02 28 81d1 81d2 81d0 05 8165 8166 811b 8169 8147 8161 12
	hex 8193 8101 81cf 05 814e 18 8101 17 8177 8154 8150 816d 815b
	hex 816e 02 8101 81b0 81b8 00
img0_nt_at1
	hex 03 02 81c6 81b1 82ad 81b0 81b8 02 81c6 81b1 82ad 81b0 81b8
	hex 8502 814b 8187 8184 817e 8176 8302 8101 12 8502 813c 813d 8128
	hex 8107 817a 8172 8183 8102 8101 02 81c5 81b6 81c4 81b5 81ab 81a2
	hex 8194 81a0 81ae 81bb 06 8502 8125 8126 8130 810e 8146 814a 8202
	hex 8101 02 81c5 81b3 81c5 81b4 81ab 81a2 819c 819d 81b2 81bc 06
	hex 8502 812d 8123 8139 8136 8112 8302 8101 0e 00
img0_nt_at2
	hex 02 8403 05 812c 8124 8118 8117 811e 03 8101 9203 07 8192
	hex 8191 04 8101 8403 8195 819e 81ba 8103 81bf 81bd 81a5 81a1 8603
	hex 05 8156 8157 812f 8111 8153 03 8101 8403 8197 819f 81b9 81cc
	hex 81af 81ba 819b 819d 8603 05 8154 8151 815a 816f 8155 8170 816a
	hex 01 8101 9203 05 8185 8186 8167 00
img0_nt_at3
	hex 02 8160 817d 814d 8190 01 8101 9203 05 813f 8140 8144 8106
	hex 810f 810b 02 8101 8403 81aa 819a 81a9 81a8 81c7 81b7 81c3 81c8
	hex 8203 81a3 8196 8203 05 812a 8134 8119 8116 8152 03 8101 8403
	hex 81ac 8198 81a6 8199 81c1 81c0 81c2 81be 8203 81a7 81a4 8203 05
	hex 8142 811c 812b 8133 814f 03 8101 9203 05 8137 8138 8145 813e
	hex 811f 03 8101 81ce 81cb 82c9 81ca 81cd 00
img0_nt_at4
	hex 02 8203 81ce 81cb 82c9 81ca 81cd 8203 81ce 81cb 0d 8101 1f
	hex 8101 06 8141 01 8162 8164 8163 815c 810a 815f 815d 815e 0f
	hex 8101 06 8159 01 8121 8175 8174 8158 0b 8168 8188 816c 05
	hex 8101 06 8182 01 8181 817f 817b 816b 8180 817c 04 00
img0_nt_at5
	hex 02 05 813b 813a 8149 8178 04 8101 02 818b 8179 818d 818c
	hex 8129 01 8122 8115 8105 8113 8114 8104 8189 8171 8173 818e 818f
	hex 818a 03 8132 812e 8132 812e 04 8101 02 814c 8148 8127 8135
	hex 8143 01 811a 8120 814c 812e 8135 811d 8131 8108 810c 810d 8110
	hex 8109 02 9b00 8106 8109 8101 8500 8104 8106 01 8500 8108 8105
	hex 02 9100 00
img0_pt
	db 4
img0_pal
	hex 0f132130 0f121530 0f192730 0f0f0f0f
img0_txt
	db 13
	hex ed e2 ed e5 de 00 00 ec dc eb de de e7

	; abro-_sexual
img1_nt_at0
	hex 01 7f 01 8c4e 00
img1_nt_at1
	hex 4e 14 f803 00
img1_nt_at2
	hex 03 08 a07e e402 00
img1_nt_at3
	hex 02 1c a07b d003 00
img1_nt_at4
	hex 03 30 a06d bc01 00
img1_nt_at5
	hex 00 c401 08 8850 9055 20 00
img1_pt
	db 7
img1_pal
	hex 0f253035 0f2b303b 0f0f0f0f 0f0f0f0f
img1_txt
	db 13
	hex da db eb e8 f5 00 00 ec de f1 ee da e5

	; aego-_sexual1
img2_nt_at0
	hex 00 7f 01 8133 8b02 00
img2_nt_at1
	hex 02 13 8134 8100 8133 1c 8134 8300 8133 1a 8134 8500 8133
	hex 18 8134 8300 8401 816b 9303 00
img2_nt_at2
	hex 03 03 816c 8901 816b 14 816c 8b01 816b 12 816c 8d01 816b
	hex 10 816c 8701 08 8153 8e01 8152 0c 00
img2_nt_at3
	hex 03 05 8153 8c01 8152 13 8153 8a01 8152 15 8153 8801 8152
	hex 0b 8c02 8124 8600 8122 9902 8124 8200 00
img2_nt_at4
	hex 00 02 8122 9b02 8124 02 8122 9d02 8124 8122 8f02 3c 00
img2_nt_at5
	hex 00 7f 05 00
img2_pt
	db 7
img2_pal
	hex 0f001430 0f0f0f0f 0f0f0f0f 0f0f0f0f
img2_txt
	db 13
	hex da de e0 e8 f5 00 ec de f1 ee da e5 d1

	; aego-_sexual2
img3_nt_at0
	hex 02 60 a06f 8c01 00
img3_nt_at1
	hex 01 34 a07a b803 00
img3_nt_at2
	hex 03 28 a04d c000 8448 00
img3_nt_at3
	hex 48 1c e003 907d 00
img3_nt_at4
	hex 7d 10 c001 a053 9c02 00
img3_nt_at5
	hex 02 44 c000 00
img3_pt
	db 5
img3_pal
	hex 0f10131c 0f0f0f0f 0f0f0f0f 0f0f0f0f
img3_txt
	db 13
	hex da de e0 e8 f5 00 ec de f1 ee da e5 d2

	; agender
img4_nt_at0
	hex 00 60 a00a 8c01 00
img4_nt_at1
	hex 01 34 a07a b803 00
img4_nt_at2
	hex 03 28 a084 c002 8480 00
img4_nt_at3
	hex 80 1c e003 907d 00
img4_nt_at4
	hex 7d 10 c001 a022 9c00 00
img4_nt_at5
	hex 00 7f 05 00
img4_pt
	db 5
img4_pal
	hex 0f002930 0f0f0f0f 0f0f0f0f 0f0f0f0f
img4_txt
	db 7
	hex da e0 de e7 dd de eb

	; andro-_gyne
img5_nt_at0
	hex 02 0a 8177 8a01 81ac 8a03 0a 8177 8a01 81ac 8a03 0a 8177
	hex 8a01 81ac 8a03 0a 8177 8a01 81ac 8a03 0a 8177 8101 00
img5_nt_at1
	hex 01 09 81ac 8a03 8a02 8177 0a 81ac 8a03 8a02 8177 0a 81ac
	hex 8a03 8a02 8177 0a 81ac 8a03 8a02 8177 0a 81ac 8203 00
img5_nt_at2
	hex 03 08 8a02 8177 8a01 81ac 0a 8a02 8177 8a01 81ac 0a 8a02
	hex 8177 8a01 81ac 0a 8a02 8177 8a01 81ac 0a 8402 00
img5_nt_at3
	hex 02 06 8177 8a01 81ac 8a03 0a 8177 8a01 81ac 8a03 0a 8177
	hex 8a01 81ac 8a03 0a 8177 8a01 81ac 8a03 0a 8177 8501 00
img5_nt_at4
	hex 01 05 81ac 8a03 8a02 8177 0a 81ac 8a03 8a02 8177 0a 81ac
	hex 8a03 8a02 8177 0a 81ac 8a03 8a02 8177 0a 81ac 8603 00
img5_nt_at5
	hex 03 04 8a02 8177 8a01 81ac 0a 8a02 8177 8a01 81ac 0a c000
	hex 00
img5_pt
	db 2
img5_pal
	hex 0f13152c 0f0f0f0f 0f0f0f0f 0f0f0f0f
img5_txt
	db 14
	hex da e7 dd eb e8 f5 00 00 00 00 e0 f2 e7 de

	; andro-_sexual
img6_nt_at0
	hex 02 7f 0d 00
img6_nt_at1
	hex 02 74 9801 00
img6_nt_at2
	hex 01 7f 0d 00
img6_nt_at3
	hex 01 5c b003 00
img6_nt_at4
	hex 03 7f 0d 00
img6_nt_at5
	hex 03 44 c000 00
img6_pt
	db 0
img6_pal
	hex 0f172124 0f0f0f0f 0f0f0f0f 0f0f0f0f
img6_txt
	db 14
	hex da e7 dd eb e8 f5 00 00 ec de f1 ee da e5

	; a-_romantic
img7_nt_at0
	hex 01 7f 01 8c50 00
img7_nt_at1
	hex 50 14 f802 00
img7_nt_at2
	hex 02 08 a081 e403 00
img7_nt_at3
	hex 03 1c a07e d001 00
img7_nt_at4
	hex 01 30 a01d bc00 00
img7_nt_at5
	hex 00 4c 8850 8855 28 00
img7_pt
	db 5
img7_pal
	hex 0f002930 0f1a290f 0f0f0f0f 0f0f0f0f
img7_txt
	db 10
	hex da f5 eb e8 e6 da e7 ed e2 dc

	; a-_romantic_asexual
img8_nt_at0
	hex 01 7f 01 8c50 00
img8_nt_at1
	hex 50 14 f802 00
img8_nt_at2
	hex 02 08 a081 e403 00
img8_nt_at3
	hex 03 1c a085 d002 00
img8_nt_at4
	hex 02 30 a06d bc01 00
img8_nt_at5
	hex 00 c401 08 8850 9055 20 00
img8_pt
	db 5
img8_pal
	hex 0f0c2130 0f172830 0f0f0f0f 0f0f0f0f
img8_txt
	db 18
	hex da f5 eb e8 e6 da e7 ed e2 dc 00 da ec de f1 ee da e5

	; asexual
img9_nt_at0
	hex 00 7f 0d 00
img9_nt_at1
	hex 00 34 d801 00
img9_nt_at2
	hex 01 68 a403 00
img9_nt_at3
	hex 03 7f 0d 00
img9_nt_at4
	hex 03 10 fc02 00
img9_nt_at5
	hex 02 44 c000 00
img9_pt
	db 0
img9_pal
	hex 0f001430 0f0f0f0f 0f0f0f0f 0f0f0f0f
img9_txt
	db 7
	hex da ec de f1 ee da e5

	; asexual_furry1
img10_nt_at0
	hex 00 7f 0d 00
img10_nt_at1
	hex 00 34 8d01 8144 813c 813d 813f 813b 8142 9901 8140 8129 01
	hex 811b 812f 01 8115 813e 9801 8133 02 8117 812b 02 811f 8401
	hex 00
img10_nt_at2
	hex 00 9201 8144 8141 8131 02 8119 812d 02 811d 8143 8142 9401
	hex 812a 01 8123 810d 8105 8120 8134 8107 810a 8121 01 8116 9401
	hex 02 8118 8101 8146 813a 8139 8145 8101 812c 02 9401 8110 02
	hex 8148 8130 02 811c 8147 02 810f 8e01 00
img10_nt_at3
	hex 01 06 812e 8104 8111 8136 8400 8126 8113 8103 811a 15 8135
	hex 8125 8600 8124 8122 16 8137 8800 8127 16 8138 810c 8600 8109
	hex 8128 17 8132 810e 8106 8112 00
img10_nt_at4
	hex 01 8114 8108 810b 811e 7f 09 00
img10_nt_at5
	hex 55 c401 a000 8850 03 8151 8154 03 88aa 880a 00
img10_pt
	db 1
img10_pal
	hex 0f000f0f 0f300f0f 0f140f0f 0f0f0f0f
img10_txt
	db 15
	hex da ec de f1 ee da e5 00 00 df ee eb eb f2 d1

	; asexual_furry2
img11_nt_at0
	hex 00 6c 8105 8109 810d 8201 8112 810b 8107 16 8104 810c 00
img11_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 8111 8106 9300 8108 8110
	hex 8141 8168 01 81cf 02 81cd 01 8197 8146 8115 810a 8900 08
	hex 81f3 81e5 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f 81db
	hex 81f1 10 81e7 814a 02 81a4 8201 815c 818b 8201 8179 02 814d
	hex 81dd 0f 81a5 812d 8172 02 8191 8201 8154 8183 8201 8162 02
	hex 81a0 812f 00
img11_nt_at2
	hex 02 817a 0e 8190 8157 01 81bf 81b8 8193 8201 815d 818c 8201
	hex 8164 81bd 81ba 01 8186 8161 0e 817e 816b 01 8182 8101 8174
	hex 8135 812e 816c 819b 8130 8131 816d 8101 8153 01 819a 814f 0e
	hex 8101 8171 01 8201 815b 01 81c7 81ad 81a9 81c4 01 818a 8201
	hex 01 819f 8101 07 8801 817c 01 813b 8201 81d0 8192 8201 8163
	hex 81ce 8201 8139 01 81a7 8c01 00
img11_nt_at3
	hex 01 04 8170 8102 818d 8124 813f 81a3 04 8178 8144 8121 815e
	hex 8102 819e 10 816a 8202 81a1 8176 06 8175 8173 8202 8199 10
	hex 8152 81c5 8102 81a6 08 817b 8102 81c8 8181 11 816f 8102 81a8
	hex 8129 06 8126 817d 8102 819d 13 81ac 8102 8188 812b 8120 8133
	hex 00
img11_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 8a01 09 8187 812a 81ab 81ca
	hex 06 81cc 81af 8127 8158 13 8196 8136 815a 81b3 81c3 81c9 81cb
	hex 81c6 81b6 8189 8132 8167 16 814e 8138 8125 8201 8122 8134 814b
	hex 28 00
img11_nt_at5
	hex 00 c402 18 8255 04 8255 8205 04 8205 18 00
img11_pt
	db 0
img11_pal
	hex 0f301400 0f30000f 0f0f0f0f 0f0f0f0f
img11_txt
	db 15
	hex da ec de f1 ee da e5 00 00 df ee eb eb f2 d2

	; autism
img12_nt_at0
	hex 01 7f 0d 00
img12_nt_at1
	hex 01 5b 810c 811e 8125 8123 8112 08 8110 811f 8125 8122 810d
	hex 0d 811d 814c 8402 813a 8118 04 8113 8134 8402 00
img12_nt_at2
	hex 01 816f 8121 0c 8151 81a9 8193 8180 8182 8198 81a8 817a 812c
	hex 02 8128 8156 81a9 819b 8189 8180 8190 81a8 8174 0b 812f 8102
	hex 8179 04 8153 819f 8103 81b9 8133 8102 81a3 8176 04 8155 8102
	hex 8135 0a 8147 8102 8165 05 813e 81c2 81b5 8102 8195 8162 05
	hex 8145 8102 816a 0a 8147 8102 8165 05 810c 8142 8102 81b1 81ad
	hex 810d 05 8141 8102 816a 09 00
img12_nt_at3
	hex 01 01 8140 8102 816c 04 8116 814b 8102 818c 81ae 8103 816e
	hex 811b 04 8149 8102 8164 0b 8187 817f 812d 810e 8115 812a 815b
	hex 81a7 817b 02 8157 81a6 817f 812e 811a 810e 8129 815b 818f 0c
	hex 8143 81a0 8402 81a1 8171 04 814e 819d 8402 81a4 8167 0d 813e
	hex 8184 819c 8194 8175 08 8152 8191 819c 818b 8162 17 00
img12_nt_at4
	hex 01 7f 0d 00
img12_nt_at5
	hex 00 c401 19 8188 8122 01 8150 81dd 8133 02 81aa 01 8154
	hex 8115 01 81ff 02 8188 8166 8105 01 81cc 8133 11 00
img12_pt
	db 2
img12_pal
	hex 0f37270f 0f372127 0f37250f 0f37290f
img12_txt
	db 6
	hex da ee ed e2 ec e6

	; autism_hstripes
img13_nt_at0
	hex 01 60 a026 8c02 00
img13_nt_at1
	hex 01 b402 a0af 07 810c 811e 8125 8123 8112 08 8110 811f 8125
	hex 8122 810d 0d 811d 814c 8402 813a 8118 04 8113 8134 8402 00
img13_nt_at2
	hex 01 816f 8121 0c 8151 81a9 8193 8180 8182 8198 81a8 817a 812c
	hex 02 8128 8156 81a9 819b 8189 8180 8190 81a8 8174 0b 812f 8102
	hex 8179 04 8153 819f 8102 8139 8133 8102 81a3 8176 04 8155 8102
	hex 8135 0a 8147 8102 8165 05 813e 8192 8202 8195 8162 05 8145
	hex 8102 816a 0a 8147 8102 8165 05 810c 8142 8202 8166 810d 05
	hex 8141 8102 816a 09 00
img13_nt_at3
	hex 01 01 8140 8102 816c 04 8116 814b 8102 818c 8185 8102 816e
	hex 811b 04 8149 8102 8164 0b 8187 817f 812d 810e 8115 812a 815b
	hex 81a7 817b 02 8157 81a6 817f 812e 811a 810e 8129 815b 818f 0c
	hex 8143 81a0 8402 81a1 8171 04 814e 819d 8402 81a4 8167 0d 813e
	hex 8184 819c 8194 8175 08 8152 8191 819c 818b 8162 07 90aa 00
img13_nt_at4
	hex aa 10 c002 a0a5 9c01 00
img13_nt_at5
	hex 01 44 9800 9055 88a5 88ff 880f 00
img13_pt
	db 2
img13_pal
	hex 0f16260f 0f283026 0f28302a 0f1a2a0f
img13_txt
	db 14
	hex da ee ed e2 ec e6 e1 ec ed eb e2 e9 de ec

	; autism_vstripes
img14_nt_at0
	hex 01 0a 8147 8102 09 81ac 14 8147 8102 09 81ac 14 8147
	hex 8102 09 81ac 14 8147 8102 09 81ac 14 8147 8102 00
img14_nt_at1
	hex 01 09 81ac 14 8147 8102 09 81ac 14 81ab 8103 09 81ac
	hex 11 810c 811e 8125 81bb 81b8 08 8110 81bc 8125 8122 810d 0d
	hex 811d 814c 8402 813a 8118 04 8113 8134 8402 00
img14_nt_at2
	hex 01 816f 8121 0c 8151 81a9 8193 8180 81be 81b0 81a8 817a 812c
	hex 02 8128 8156 81a9 819b 81c1 8180 8190 81a8 8174 0b 812f 8102
	hex 8179 02 8147 8102 8153 819f 8102 8139 8133 8102 81a3 8176 01
	hex 81ac 02 8155 8102 8135 0a 8147 8102 8165 02 8147 8102 01
	hex 813e 8192 8202 8195 8162 02 81ac 02 8145 8102 816a 0a 8147
	hex 8102 8165 02 8147 8102 01 810c 8142 8202 8166 810d 02 81ac
	hex 02 8141 8102 816a 09 00
img14_nt_at3
	hex 01 01 8140 8102 816c 02 8147 8102 8116 814b 8102 818c 8185
	hex 8102 816e 811b 01 81ac 02 8149 8102 8164 0b 8187 817f 812d
	hex 810e 81ba 81b7 815b 81a7 817b 02 8157 81a6 817f 812e 81bd 810e
	hex 8129 815b 818f 0c 8143 81a0 8402 81a1 8171 04 814e 819d 8402
	hex 81a4 8167 0d 813e 8184 819c 81c0 81b2 08 8152 81bf 819c 818b
	hex 8162 11 81ab 8103 04 00
img14_nt_at4
	hex 01 05 81ac 14 8147 8102 09 81ac 14 8147 8102 09 81ac
	hex 14 8147 8102 09 81ac 14 8147 8102 09 81ac 06 00
img14_nt_at5
	hex 00 8e01 8147 8102 8901 81ac 9401 8147 8102 8901 81ac 8a01 0a
	hex 81c0 8250 8190 82a0 02 81cc 8255 8199 82aa 03 8255 8199 82aa
	hex 02 81cc 8255 8199 82aa 03 8255 8199 82aa 02 81cc 8255 8199
	hex 82aa 02 810c 8205 8109 820a 00
img14_pt
	db 2
img14_pal
	hex 0f16301a 0f1a3012 0f12300f 0f161a0f
img14_txt
	db 14
	hex da ee ed e2 ec e6 ef ec ed eb e2 e9 de ec

	; auto-_sexual
img15_nt_at0
	hex 02 7f 0d 00
img15_nt_at1
	hex 02 7f 0d 00
img15_nt_at2
	hex 02 68 a401 00
img15_nt_at3
	hex 01 7f 0d 00
img15_nt_at4
	hex 01 7f 0d 00
img15_nt_at5
	hex 01 44 c000 00
img15_pt
	db 0
img15_pal
	hex 0f00310f 0f0f0f0f 0f0f0f0f 0f0f0f0f
img15_txt
	db 13
	hex da ee ed e8 f5 00 00 ec de f1 ee da e5

	; bear
img16_nt_at0
	hex 00 a501 811b 8118 8117 9d01 810e 02 8113 8114 8115 811a 9401
	hex 8243 8189 01 8188 8187 8180 811e 8183 8184 01 810a 818a 9343
	hex 8302 8123 01 812c 8136 8135 8137 812f 8120 01 00
img16_nt_at1
	hex 00 812d 813a 9502 8132 8121 812a 03 812b 8130 8127 8131 8128
	hex 8138 9102 837a 8139 818e 818d 07 818b 818c 917a 8303 813c 01
	hex 813f 8107 05 813b 813d 9203 8301 810f 8105 810b 8112 03 8104
	hex 8109 810d 8b01 00
img16_nt_at2
	hex 00 8b01 8119 8111 811c 8110 02 8106 810c 9501 8344 8185 01
	hex 8182 8186 01 811f 8181 9644 8402 8125 8126 812e 811d 8129 9702
	hex 8703 813e 9803 847f 00
img16_nt_at3
	hex 7f 1c e002 9045 00
img16_nt_at4
	hex 45 10 c001 a016 9c00 00
img16_nt_at5
	hex 00 4c 8850 8855 81a5 81a9 81a0 85a5 880a 18 00
img16_pt
	db 7
img16_pal
	hex 0f003037 0f071727 0f27370f 0f0f0f0f
img16_txt
	db 4
	hex db de da eb

	; bigender
img17_nt_at0
	hex 01 60 a043 8c02 00
img17_nt_at1
	hex 02 34 a07a a003 18 00
img17_nt_at2
	hex 02 28 a046 c001 8441 00
img17_nt_at3
	hex 41 1c c002 a003 907d 00
img17_nt_at4
	hex 7d 10 c002 a048 9c01 00
img17_nt_at5
	hex 00 c401 08 8850 8855 88a5 88aa 880a 10 00
img17_pt
	db 7
img17_pal
	hex 0f112133 0f142433 0f30330f 0f0f0f0f
img17_txt
	db 8
	hex db e2 e0 de e7 dd de eb

	; bisexual
img18_nt_at0
	hex 03 7f 0d 00
img18_nt_at1
	hex 03 7f 0d 00
img18_nt_at2
	hex 03 08 a07e e402 00
img18_nt_at3
	hex 02 1c a047 d001 00
img18_nt_at4
	hex 01 7f 0d 00
img18_nt_at5
	hex 01 44 c000 00
img18_pt
	db 7
img18_pal
	hex 0f121315 0f0f0f0f 0f0f0f0f 0f0f0f0f
img18_txt
	db 8
	hex db e2 ec de f1 ee da e5

	; bisexual_furry1
img19_nt_at0
	hex 01 7f 0d 00
img19_nt_at1
	hex 00 c101 8144 813c 813d 813f 813b 8142 9901 8140 8129 01 811b
	hex 812f 01 8115 813e 8c01 8c02 814d 02 8149 814c 02 814a 8402
	hex 00
img19_nt_at2
	hex 00 8802 8a53 8189 8186 8185 02 8177 8184 02 8179 8188 8187
	hex 8a53 8a01 812a 01 8123 810d 8105 8120 8134 8107 810a 8121 01
	hex 8116 9401 02 8118 8101 8146 813a 8139 8145 8101 812c 02 9401
	hex 8110 02 8148 8130 02 811c 8147 02 810f 8e01 00
img19_nt_at3
	hex 01 06 812e 8104 8111 8136 8400 8126 8113 8103 811a 0a 8b51
	hex 817f 817c 8600 817b 817a 8b51 8b02 814e 8800 814b 8b02 0b 8138
	hex 810c 8600 8109 8128 17 8132 810e 8106 8112 00
img19_nt_at4
	hex 01 8114 8108 810b 811e 7f 09 00
img19_nt_at5
	hex fa c401 9800 8850 8855 03 81f2 81f8 03 88ff 880f 00
img19_pt
	db 1
img19_pal
	hex 0f150f0f 0f13150f 0f13120f 0f120f0f
img19_txt
	db 16
	hex db e2 ec de f1 ee da e5 00 00 df ee eb eb f2 d1

	; bisexual_furry2
img20_nt_at0
	hex 02 6c 81be 81b5 8198 8201 8169 81b2 81b9 16 81f2 81ec 00
img20_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 81e2 81f0 13 81b7 81e5
	hex 8141 8168 01 81cf 02 81cd 01 8197 8146 81db 81b4 11 81f3
	hex 81e5 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f 81db 81f1
	hex 10 81e7 814a 02 81a4 8201 815c 818b 8201 8179 02 814d 81dd
	hex 08 8703 81ed 812d 8172 02 8191 8201 8154 8183 8201 8162 02
	hex 81a0 812f 00
img20_nt_at2
	hex 02 81e3 8703 87f7 81fe 8157 01 81bf 81b8 8193 8201 815d 818c
	hex 8201 8164 81bd 81ba 01 8186 81f9 87f7 07 817e 816b 01 8182
	hex 8101 8174 8135 812e 816c 819b 8130 8131 816d 8101 8153 01 819a
	hex 814f 0e 8101 8171 01 8201 815b 01 81c7 81ad 81a9 81c4 01
	hex 818a 8201 01 819f 8101 0e 8101 817c 01 813b 8201 81d0 8192
	hex 8201 8163 81ce 8201 8139 01 81a7 8101 0b 00
img20_nt_at3
	hex 02 03 8143 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121
	hex 815e 01 819e 813e 07 87f5 81fb 816a 02 81a1 8176 8601 8175
	hex 8173 02 8199 81f8 87f5 8703 81e9 8152 81c5 01 81a6 8801 817b
	hex 01 81c8 8181 81df 8703 08 81d9 816f 01 81a8 8129 8601 8126
	hex 817d 01 819d 81d8 10 81eb 81d2 81ac 01 8188 812b 8120 8133
	hex 00
img20_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 81d1 81e1 11 8187 81d2 81ab
	hex 81ca 06 81cc 81af 81d1 8158 13 81ea 81d4 815a 81b3 81c3 81c9
	hex 81cb 81c6 81b6 8189 81d3 81e0 16 814e 8138 8125 8201 8122 8134
	hex 814b 28 00
img20_nt_at5
	hex 00 c402 08 88a0 82aa 812a 820a 818a 82aa 820a 04 820a 08
	hex 82f5 8110 02 8140 82f5 82ff 81f7 82f0 81fd 82ff 880f 00
img20_pt
	db 0
img20_pal
	hex 0f301315 0f301312 0f30150f 0f30120f
img20_txt
	db 16
	hex db e2 ec de f1 ee da e5 00 00 df ee eb eb f2 d2

	; demi-_fluid
img21_nt_at0
	hex 01 60 a056 0c 00
img21_nt_at1
	hex 02 b401 8853 907b 8881 08 9803 08 9003 00
img21_nt_at2
	hex 03 08 8802 18 e402 00
img21_nt_at3
	hex 02 24 9803 08 9803 08 9803 886f 887e 00
img21_nt_at4
	hex 01 887e 8885 40 a073 1c 00
img21_nt_at5
	hex 00 c401 10 8850 8455 82aa 02 88aa 8455 82aa 02 8805 08
	hex 00
img21_pt
	db 5
img21_pal
	hex 0f001031 0f103538 0f10303b 0f0f0f0f
img21_txt
	db 13
	hex dd de e6 e2 f5 00 00 00 df e5 ee e2 dd

	; demiflux
img22_nt_at0
	hex 01 60 a043 0c 00
img22_nt_at1
	hex 01 34 a040 b802 00
img22_nt_at2
	hex 02 28 a07c a003 20 8449 00
img22_nt_at3
	hex 49 1c c001 a003 907d 00
img22_nt_at4
	hex 01 907d 40 a048 1c 00
img22_nt_at5
	hex 00 c401 10 8850 8855 88a5 880a 8805 08 00
img22_pt
	db 7
img22_pal
	hex 0f001031 0f103638 0f31380f 0f0f0f0f
img22_txt
	db 8
	hex dd de e6 e2 df e5 ee f1

	; demi-_gender
img23_nt_at0
	hex 01 60 a043 8c02 00
img23_nt_at1
	hex 02 34 a07a a003 18 00
img23_nt_at2
	hex 02 28 a046 c001 8441 00
img23_nt_at3
	hex 41 1c c002 a003 907d 00
img23_nt_at4
	hex 7d 10 c002 a048 9c01 00
img23_nt_at5
	hex 00 c401 18 8850 8855 8805 10 00
img23_pt
	db 7
img23_pal
	hex 0f001038 0f30380f 0f0f0f0f 0f0f0f0f
img23_txt
	db 13
	hex dd de e6 e2 f5 00 00 e0 de e7 dd de eb

	; demigirl
img24_nt_at0
	hex 01 60 a043 8c02 00
img24_nt_at1
	hex 02 34 a07a a003 18 00
img24_nt_at2
	hex 02 28 a046 c001 8441 00
img24_nt_at3
	hex 41 1c c002 a003 907d 00
img24_nt_at4
	hex 7d 10 c002 a048 9c01 00
img24_nt_at5
	hex 00 c401 18 8850 8855 8805 10 00
img24_pt
	db 7
img24_pal
	hex 0f001035 0f30350f 0f0f0f0f 0f0f0f0f
img24_txt
	db 8
	hex dd de e6 e2 e0 e2 eb e5

	; demiguy
img25_nt_at0
	hex 01 60 a043 8c02 00
img25_nt_at1
	hex 02 34 a07a a003 18 00
img25_nt_at2
	hex 02 28 a046 c001 8441 00
img25_nt_at3
	hex 41 1c c002 a003 907d 00
img25_nt_at4
	hex 7d 10 c002 a048 9c01 00
img25_nt_at5
	hex 00 c401 18 8850 8855 8805 10 00
img25_pt
	db 7
img25_pal
	hex 0f001031 0f30310f 0f0f0f0f 0f0f0f0f
img25_txt
	db 7
	hex dd de e6 e2 e0 ee f2

	; demi-_sexual
img26_nt_at0
	hex 0b 01 9f03 8100 01 9e03 8200 01 9d03 8300 01 9c03 8400
	hex 01 8703 00
img26_nt_at1
	hex 03 14 8500 810b 1a 8600 810b 19 8700 810b 18 8800 810b
	hex 0f 00
img26_nt_at2
	hex 00 8803 09 810b 9603 0a 8105 9501 0b 8105 9401 0b 8104
	hex 9401 04 00
img26_nt_at3
	hex 00 06 8104 9501 09 8108 9602 08 8108 9702 07 8108 9802
	hex 06 8108 8902 00
img26_nt_at4
	hex 02 10 8500 8108 1a 8400 8108 1b 8300 8108 1c 8200 8108
	hex 19 00
img26_nt_at5
	hex 02 04 8100 8108 1e 8108 1f c000 00
img26_pt
	db 2
img26_pal
	hex 0f041030 0f0f0f0f 0f0f0f0f 0f0f0f0f
img26_txt
	db 13
	hex dd de e6 e2 f5 00 00 ec de f1 ee da e5

	; dis-_ability
img27_nt_at0
	hex 6b 01 8102 8183 8103 817c 8101 01 8102 812c 9700 8101 01
	hex 8102 8183 8103 817c 8101 01 8102 812c 9600 811c 8101 01 8102
	hex 8183 8103 817c 8101 01 8102 812c 9600 811c 8101 01 8102 8183
	hex 8103 817c 8101 01 8102 812c 9600 811c 8101 01 8102 8183 8103
	hex 817c 8101 01 8102 00
img27_nt_at1
	hex 01 812c 9600 811c 01 816b 8102 8183 8103 817c 01 816b 8102
	hex 812c 9600 811c 01 816b 8102 8183 8103 817c 01 816b 8102 812c
	hex 9600 811c 01 816b 8102 8183 8103 817c 01 816b 8102 812c 9600
	hex 811c 01 816b 8102 8183 8103 817c 01 816b 8102 812c 8700 00
img27_nt_at2
	hex 01 8f00 811c 01 816b 8102 8183 8103 817c 01 816b 8102 812c
	hex 9600 811c 01 816b 8102 8183 8103 817c 01 816b 8102 812c 9600
	hex 811c 01 816b 8102 8183 8103 817c 01 816b 8102 812c 9600 811c
	hex 01 816b 8102 8183 8103 817c 01 816b 8102 812c 8f00 00
img27_nt_at3
	hex 01 8700 811c 01 816b 8102 8183 8103 817c 01 816b 8102 812c
	hex 9600 811c 01 816b 8102 8183 8103 817c 01 816b 8102 812c 9600
	hex 811c 01 816b 8102 8183 8103 817c 01 816b 8102 812c 9600 811c
	hex 01 816b 8102 8183 8103 817c 01 816b 8102 812c 9600 811c 00
img27_nt_at4
	hex 01 01 816b 8102 8183 8103 817c 01 816b 8102 812c 9600 811c
	hex 01 816b 8102 8183 8103 817c 01 816b 8102 812c 9600 811c 01
	hex 816b 8102 8183 8103 817c 01 816b 8102 812c 9600 811c 01 816b
	hex 8102 8183 8103 817c 01 816b 8102 812c 9600 811c 01 816b 8102
	hex 8183 8103 817c 01 816b 00
img27_nt_at5
	hex 00 8102 812c 16 811c 8101 816b 8102 8183 8103 817c 8101 816b
	hex 8102 812c 16 811c 8101 816b 8102 8183 8103 817c 8101 816b 8102
	hex 812c 08 8150 07 8145 8151 07 8145 8151 07 8145 8151 07
	hex 8145 8151 07 8145 8151 07 8105 8101 01 00
img27_pt
	db 5
img27_pal
	hex 0f212a30 0f262830 0f0f0f0f 0f0f0f0f
img27_txt
	db 12
	hex dd e2 ec f5 00 da db e2 e5 e2 ed f2

	; fray-_sexual
img28_nt_at0
	hex 02 7f 0d 00
img28_nt_at1
	hex 02 34 d801 00
img28_nt_at2
	hex 01 68 a403 00
img28_nt_at3
	hex 03 7f 0d 00
img28_nt_at4
	hex 03 10 fc01 00
img28_nt_at5
	hex 00 c401 18 8855 8805 18 00
img28_pt
	db 0
img28_pal
	hex 0f001130 0f3c0f0f 0f0f0f0f 0f0f0f0f
img28_txt
	db 13
	hex df eb da f2 f5 00 00 ec de f1 ee da e5

	; gay_men
img29_nt_at0
	hex 01 60 a043 8c02 00
img29_nt_at1
	hex 02 34 a07a a003 18 00
img29_nt_at2
	hex 02 28 a07c c003 8479 00
img29_nt_at3
	hex 79 1c c001 a003 907d 00
img29_nt_at4
	hex 7d 10 c002 a048 9c01 00
img29_nt_at5
	hex 00 c401 08 8850 8855 88a5 88aa 880a 10 00
img29_pt
	db 7
img29_pal
	hex 0f031222 0f0b1b2b 0f222b30 0f0f0f0f
img29_txt
	db 11
	hex e0 da f2 00 00 00 00 00 e6 de e7

	; gender-_fluid
img30_nt_at0
	hex 02 7f 01 8c80 00
img30_nt_at1
	hex 80 14 f803 00
img30_nt_at2
	hex 03 08 a07f e401 00
img30_nt_at3
	hex 01 1c a01f d000 00
img30_nt_at4
	hex 00 30 a00b bc01 00
img30_nt_at5
	hex 01 44 b000 8855 8805 00
img30_pt
	db 5
img30_pal
	hex 0f142530 0f020f0f 0f0f0f0f 0f0f0f0f
img30_txt
	db 15
	hex e0 de e7 dd de eb f5 00 00 00 df e5 ee e2 dd

	; gender-_queer
img31_nt_at0
	hex 01 7f 0d 00
img31_nt_at1
	hex 01 74 9803 00
img31_nt_at2
	hex 03 7f 0d 00
img31_nt_at3
	hex 03 5c b002 00
img31_nt_at4
	hex 02 7f 0d 00
img31_nt_at5
	hex 02 44 c000 00
img31_pt
	db 0
img31_pal
	hex 0f131930 0f0f0f0f 0f0f0f0f 0f0f0f0f
img31_txt
	db 15
	hex e0 de e7 dd de eb f5 00 00 00 ea ee de de eb

	; grey-_sexual
img32_nt_at0
	hex 02 7f 01 8c49 00
img32_nt_at1
	hex 49 14 f801 00
img32_nt_at2
	hex 01 08 a051 e403 00
img32_nt_at3
	hex 03 1c a070 d001 00
img32_nt_at4
	hex 01 30 a044 bc02 00
img32_nt_at5
	hex 02 44 c000 00
img32_pt
	db 7
img32_pal
	hex 0f101330 0f0f0f0f 0f0f0f0f 0f0f0f0f
img32_txt
	db 13
	hex e0 eb de f2 f5 00 00 ec de f1 ee da e5

	; intersex
img33_nt_at0
	hex 02 7f 0d 00
img33_nt_at1
	hex 02 61 81a2 818a 8162 813e 8183 819e 19 817c 8101 8114 8120
	hex 8124 8119 8101 8158 04 00
img33_nt_at2
	hex 02 13 818e 8101 8130 815b 02 817f 8136 8101 8186 16 8169
	hex 8127 815b 04 817f 812b 8146 16 815c 8148 06 816b 813b 16
	hex 8111 814f 06 8172 810f 0f 00
img33_nt_at3
	hex 02 07 815d 8144 81a8 04 81a9 8168 813c 16 8173 8101 8158
	hex 81a8 02 81a9 817c 8101 8150 17 8136 8101 8154 8196 8199 8178
	hex 8101 8130 19 815f 811c 810d 810c 8117 813d 1d 00
img33_nt_at4
	hex 02 7f 0d 00
img33_nt_at5
	hex 02 44 c000 00
img33_pt
	db 2
img33_pal
	hex 0f04280f 0f0f0f0f 0f0f0f0f 0f0f0f0f
img33_txt
	db 8
	hex e2 e7 ed de eb ec de f1

	; leather
img34_nt_at0
	hex 02 8700 8125 8129 812b 812a 9c00 8132 03 8138 9400 8608 8186
	hex 05 8187 9308 8401 8151 8154 815e 05 8165 9601 815b 08 00
img34_nt_at1
	hex 02 8168 9301 821f 8189 8162 08 818b 931f 8200 812d 09 813c
	hex 9600 8140 08 813a 9300 8301 815d 8172 06 8176 8c01 00
img34_nt_at2
	hex 01 0c 815a 816a 8171 8175 8177 8178 8179 8169 14 a07b c003
	hex 847e 00
img34_nt_at3
	hex 7e 1c c001 b000 00
img34_nt_at4
	hex 00 10 a008 c001 9c1f 00
img34_nt_at5
	hex 00 841f 7f 01 00
img34_pt
	db 5
img34_pal
	hex 0f011530 0f0f0f0f 0f0f0f0f 0f0f0f0f
img34_txt
	db 7
	hex e5 de da ed e1 de eb

	; lesbian_5stripes
img35_nt_at0
	hex 01 7f 01 8c50 00
img35_nt_at1
	hex 50 14 f802 00
img35_nt_at2
	hex 02 08 a081 e403 00
img35_nt_at3
	hex 03 1c a085 d002 00
img35_nt_at4
	hex 02 30 a06d bc01 00
img35_nt_at5
	hex 00 c401 08 8850 9055 20 00
img35_pt
	db 5
img35_pal
	hex 0f142430 0f172730 0f0f0f0f 0f0f0f0f
img35_txt
	db 15
	hex e5 de ec db e2 da e7 d5 ec ed eb e2 e9 de ec

	; lesbian_5stripes_furry1
img36_nt_at0
	hex 01 7f 01 8c4f 00
img36_nt_at1
	hex 01 944f a002 0d 8144 813c 813d 813f 813b 8142 19 8140 8129
	hex 8100 811b 812f 8100 8115 813e 18 8133 8200 8117 812b 8200 811f
	hex 04 00
img36_nt_at2
	hex 00 8801 8a50 8183 8180 817e 02 8176 817d 02 8178 8182 8181
	hex 8a50 8a01 812a 01 8123 810d 8105 8120 8134 8107 810a 8121 01
	hex 8116 9401 02 8118 8101 8146 813a 8139 8145 8101 812c 02 9401
	hex 8110 02 8148 8130 02 811c 8147 02 810f 8e01 00
img36_nt_at3
	hex 01 06 812e 8104 8111 8136 8400 8126 8113 8103 811a 0a 8b51
	hex 817f 817c 8600 817b 817a 8b51 8b02 814e 8800 814b 8b02 0b 8138
	hex 810c 8600 8109 8128 17 8132 810e 8106 8112 00
img36_nt_at4
	hex 14 01 8108 810b 811e ac01 a052 bc02 00
img36_nt_at5
	hex fa c402 9800 8855 88aa 03 81f2 81f8 03 88ff 880f 00
img36_pt
	db 1
img36_pal
	hex 0f17270f 0f27300f 0f30240f 0f24140f
img36_txt
	db 23
	hex e5 de ec db e2 da e7 d5 ec ed eb e2 e9 de ec 00 00 df ee eb eb f2
	hex d1

	; lesbian_5stripes_furry2
img37_nt_at0
	hex 02 6c 81be 81b5 8198 8201 8169 81b2 81b9 0c 8af4 81fd 819c
	hex 00
img37_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 816e 81fc 8af4 8903 81ef
	hex 81e5 8141 8168 01 81cf 02 81cd 01 8197 8146 81db 81ee 8903
	hex 08 81f3 81e5 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f
	hex 81db 81f1 10 81e7 814a 02 81a4 8201 815c 818b 8201 8179 02
	hex 814d 81dd 0f 81a5 812d 8172 02 8191 8201 8154 8183 8201 8162
	hex 02 81a0 812f 00
img37_nt_at2
	hex 01 817a 8702 87c2 818f 8157 8102 81bf 81b8 8193 02 815d 818c
	hex 02 8164 81bd 81ba 8102 8186 8160 87c2 08 816b 8102 8182 01
	hex 8174 8135 812e 816c 819b 8130 8131 816d 01 8153 8102 819a 10
	hex 8171 8102 02 815b 8102 81c7 81ad 81a9 81c4 8102 818a 02 8102
	hex 819f 10 817c 8102 813b 02 81d0 8192 02 8163 81ce 02 8139
	hex 8102 81a7 0c 00
img37_nt_at3
	hex 02 8401 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121 815e
	hex 01 819e 8801 87d7 81d6 816a 02 81a1 8176 8601 8175 8173 02
	hex 8199 81d5 87d7 8703 81e9 8152 81c5 01 81a6 8801 817b 01 81c8
	hex 8181 81df 8f03 81d9 816f 01 81a8 8129 8601 8126 817d 01 819d
	hex 81d8 9003 81eb 81d2 81ac 01 8188 812b 8120 8133 00
img37_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 81d1 81e1 9103 81e6 81d2 81ab
	hex 81ca 06 81cc 81af 81d1 81dc 8903 8af6 81ff 8136 815a 81b3 81c3
	hex 81c9 81cb 81c6 81b6 8189 8132 81fa 8af6 0c 814e 8138 8125 8201
	hex 8122 8134 814b 28 00
img37_nt_at5
	hex 00 c402 08 88a0 83aa 820a 83aa 82ff 8101 02 8104 82ff 20
	hex 00
img37_pt
	db 0
img37_pal
	hex 0f301424 0f301427 0f301727 0f30270f
img37_txt
	db 23
	hex e5 de ec db e2 da e7 d5 ec ed eb e2 e9 de ec 00 00 df ee eb eb f2
	hex d2

	; lesbian_7stripes
img38_nt_at0
	hex 01 60 a043 8c02 00
img38_nt_at1
	hex 02 34 a07a a003 18 00
img38_nt_at2
	hex 02 28 a07c c003 8479 00
img38_nt_at3
	hex 79 1c c001 a003 907d 00
img38_nt_at4
	hex 7d 10 c002 a048 9c01 00
img38_nt_at5
	hex 00 c401 08 8850 8855 88a5 88aa 880a 10 00
img38_pt
	db 7
img38_pal
	hex 0f041424 0f071727 0f242730 0f0f0f0f
img38_txt
	db 15
	hex e5 de ec db e2 da e7 d7 ec ed eb e2 e9 de ec

	; neptunic
img39_nt_at0
	hex 01 7f 01 8c03 00
img39_nt_at1
	hex 03 7f 0d 00
img39_nt_at2
	hex 03 68 a401 00
img39_nt_at3
	hex 01 5c b002 00
img39_nt_at4
	hex 02 7f 0d 00
img39_nt_at5
	hex 00 c402 18 8850 9055 8805 08 00
img39_pt
	db 0
img39_pal
	hex 0f1c222c 0f30323c 0f0f0f0f 0f0f0f0f
img39_txt
	db 8
	hex e7 de e9 ed ee e7 e2 dc

	; non-_binary
img40_nt_at0
	hex 02 7f 0d 00
img40_nt_at1
	hex 02 34 d803 00
img40_nt_at2
	hex 03 68 a401 00
img40_nt_at3
	hex 01 7f 0d 00
img40_nt_at4
	hex 01 10 fc00 00
img40_nt_at5
	hex 00 7f 05 00
img40_pt
	db 0
img40_pal
	hex 0f132830 0f0f0f0f 0f0f0f0f 0f0f0f0f
img40_txt
	db 12
	hex e7 e8 e7 f5 00 00 db e2 e7 da eb f2

	; non-_binary_furry
img41_nt_at0
	hex 02 6c 81be 81b5 8198 8201 8169 81b2 81b9 16 81f2 81ec 00
img41_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 81e2 81f0 13 81b7 81e5
	hex 8141 8168 01 81cf 02 81cd 01 8197 8146 81db 81b4 09 8a01
	hex 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f 9301 814a 02
	hex 81a4 8201 815c 818b 8201 8179 02 814d 9101 812d 8172 02 8191
	hex 8201 8154 8183 8201 8162 02 81a0 812f 00
img41_nt_at2
	hex 01 10 8157 8102 81bf 81b8 8193 02 815d 818c 02 8164 81bd
	hex 81ba 8102 8186 10 816b 8102 8182 01 8174 8135 812e 816c 819b
	hex 8130 8131 816d 01 8153 8102 819a 10 8171 8102 02 815b 8102
	hex 81c7 81ad 81a9 81c4 8102 818a 02 8102 819f 08 8702 01 817c
	hex 8102 813b 02 81d0 8192 02 8163 81ce 02 8139 8102 81a7 01
	hex 8b02 00
img41_nt_at3
	hex 02 03 814c 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121
	hex 815e 01 819e 8149 0e 8184 816a 02 81a1 8176 8601 8175 8173
	hex 02 8199 8155 0e 8194 8152 81c5 01 81a6 8801 817b 01 81c8
	hex 8181 8165 0f 8145 816f 01 81a8 8129 8601 8126 817d 01 819d
	hex 8140 10 8195 812a 81ac 01 8188 812b 8120 8133 00
img41_nt_at4
	hex 00 8137 8123 8128 8159 8102 81b0 8127 8166 8802 09 810f 811c
	hex 81ab 81ca 8602 81cc 81af 811d 8114 13 810e 8119 815a 81b3 81c3
	hex 81c9 81cb 81c6 81b6 8189 811b 8113 16 8116 8118 811e 8201 811f
	hex 811a 8117 28 00
img41_nt_at5
	hex 00 4c 8850 8255 8115 8205 8145 8255 28 00
img41_pt
	db 0
img41_pal
	hex 0f301328 0f30280f 0f0f0f0f 0f0f0f0f
img41_txt
	db 20
	hex e7 e8 e7 f5 00 00 db e2 e7 da eb f2 00 00 00 df ee eb eb f2

	; omni-_sexual
img42_nt_at0
	hex 02 7f 01 8c49 00
img42_nt_at1
	hex 49 14 f801 00
img42_nt_at2
	hex 01 08 a016 e400 00
img42_nt_at3
	hex 00 1c a008 d001 00
img42_nt_at4
	hex 01 30 a044 bc02 00
img42_nt_at5
	hex 00 c402 08 8850 9055 20 00
img42_pt
	db 7
img42_pal
	hex 0f22320f 0f25350f 0f0f0f0f 0f0f0f0f
img42_txt
	db 13
	hex e8 e6 e7 e2 f5 00 00 ec de f1 ee da e5

	; pan-_sexual
img43_nt_at0
	hex 01 7f 0d 00
img43_nt_at1
	hex 01 74 9803 00
img43_nt_at2
	hex 03 7f 0d 00
img43_nt_at3
	hex 03 5c b002 00
img43_nt_at4
	hex 02 7f 0d 00
img43_nt_at5
	hex 02 44 c000 00
img43_pt
	db 0
img43_pal
	hex 0f152128 0f0f0f0f 0f0f0f0f 0f0f0f0f
img43_txt
	db 12
	hex e9 da e7 f5 00 00 ec de f1 ee da e5

	; pan-_sexual_furry1
img44_nt_at0
	hex 01 7f 0d 00
img44_nt_at1
	hex 01 41 8144 813c 813d 813f 813b 8142 19 8140 8129 8100 811b
	hex 812f 8100 8115 813e 18 8133 8200 8117 812b 8200 811f 04 00
img44_nt_at2
	hex 00 9201 8144 8141 8131 02 8119 812d 02 811d 8143 8142 9401
	hex 812a 01 8123 810d 8105 8120 8134 8107 810a 8121 01 8116 9401
	hex 02 8118 8101 8146 813a 8139 8145 8101 812c 02 9401 8110 02
	hex 8148 8130 02 811c 8147 02 810f 8e01 00
img44_nt_at3
	hex 01 06 812e 8104 8111 8136 8400 8126 8113 8103 811a 15 8135
	hex 8125 8600 8124 8122 16 8137 8800 8127 16 8138 810c 8600 8109
	hex 8128 17 8132 810e 8106 8112 00
img44_nt_at4
	hex 01 8114 8108 810b 811e 7f 09 00
img44_nt_at5
	hex a5 c401 9800 8850 8855 03 81a1 81a4 03 88aa 880a 00
img44_pt
	db 1
img44_pal
	hex 0f150f0f 0f280f0f 0f210f0f 0f0f0f0f
img44_txt
	db 20
	hex e9 da e7 f5 00 00 ec de f1 ee da e5 00 00 df ee eb eb f2 d1

	; pan-_sexual_furry2
img45_nt_at0
	hex 02 6c 81be 81b5 8198 8201 8169 81b2 81b9 16 81c0 819c 00
img45_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 816e 81bb 13 81b7 8180
	hex 8141 8168 01 81cf 02 81cd 01 8197 8146 8151 81b4 11 81c1
	hex 8180 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f 8151 81bc
	hex 10 818e 814a 02 81a4 8201 815c 818b 8201 8179 02 814d 815f
	hex 0f 81a5 812d 8172 02 8191 8201 8154 8183 8201 8162 02 81a0
	hex 812f 00
img45_nt_at2
	hex 02 817a 0e 8190 8157 01 81bf 81b8 8193 8201 815d 818c 8201
	hex 8164 81bd 81ba 01 8186 8161 0e 817e 816b 01 8182 8101 8174
	hex 8135 812e 816c 819b 8130 8131 816d 8101 8153 01 819a 814f 0e
	hex 8101 8171 01 8201 815b 01 81c7 81ad 81a9 81c4 01 818a 8201
	hex 01 819f 8101 0e 8101 817c 01 813b 8201 81d0 8192 8201 8163
	hex 81ce 8201 8139 01 81a7 8101 0b 00
img45_nt_at3
	hex 02 03 8143 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121
	hex 815e 01 819e 813e 0e 8185 816a 02 81a1 8176 8601 8175 8173
	hex 02 8199 8156 0e 8194 8152 81c5 01 81a6 8801 817b 01 81c8
	hex 8181 8165 0f 81d9 816f 01 81a8 8129 8601 8126 817d 01 819d
	hex 81d8 10 81eb 81d2 81ac 01 8188 812b 8120 8133 00
img45_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 81d1 81e1 11 8187 81d2 81ab
	hex 81ca 06 81cc 81af 81d1 8158 13 81ea 81d4 815a 81b3 81c3 81c9
	hex 81cb 81c6 81b6 8189 81d3 81e0 16 814e 8138 8125 8201 8122 8134
	hex 814b 28 00
img45_nt_at5
	hex 00 c402 18 82a0 04 82a0 82aa 04 82aa 825a 04 825a 8255
	hex 8151 8250 8154 8255 8805 00
img45_pt
	db 0
img45_pal
	hex 0f301521 0f30210f 0f30280f 0f0f0f0f
img45_txt
	db 20
	hex e9 da e7 f5 00 00 ec de f1 ee da e5 00 00 df ee eb eb f2 d2

	; poly-_amory1
img46_nt_at0
	hex 01 7f 0d 00
img46_nt_at1
	hex 01 74 9802 00
img46_nt_at2
	hex 02 15 8155 8158 815a 8159 8156 815b 815e 19 8164 8172 8171
	hex 8170 8175 8173 8167 19 8166 8157 816f 815d 816e 1c 8161 816b
	hex 8160 816c 12 00
img46_nt_at3
	hex 02 0a 8163 8169 8162 816d 815c 1b 8165 8168 815f 8174 816a
	hex 2d b000 00
img46_nt_at4
	hex 00 7f 0d 00
img46_nt_at5
	hex 00 7f 05 00
img46_pt
	db 1
img46_pal
	hex 0f021628 0f0f0f0f 0f0f0f0f 0f0f0f0f
img46_txt
	db 13
	hex e9 e8 e5 f2 f5 00 00 da e6 e8 eb f2 d1

	; poly-_amory2
img47_nt_at0
	hex 01 7f 0a 811f 8128 812c 00
img47_nt_at1
	hex 01 812b 8127 04 8124 8129 812c 812a 8120 11 8122 8132 8103
	hex 8147 8149 8142 812f 8126 8123 812d 8138 814b 8147 8103 813b 8125
	hex 10 8130 8103 813f 01 8131 8143 8148 813d 8134 814a 8144 813a
	hex 01 8136 8103 8139 10 8133 8141 8121 03 8135 8145 8146 813e
	hex 03 8121 8137 813c 08 8702 8158 8179 8203 8197 8161 814f 8102
	hex 8171 8195 8102 814e 8160 8174 8203 819c 00
img47_nt_at2
	hex 02 815c 0d 8154 8180 81c5 8103 81ac 81b4 81c3 819e 815f 02
	hex 815d 817c 81c7 81b5 81af 8103 81c5 81a2 8159 0c 816e 81c2 8193
	hex 8103 818a 01 8170 81b6 8103 8163 8162 8103 81b9 8194 01 8169
	hex 8103 818d 81c0 8190 0c 8177 81a5 01 81a8 819b 02 8165 81ad
	hex 8203 81b0 8183 02 8178 81ab 01 8181 819a 0c 817e 81a1 01
	hex 8172 8103 8186 01 814c 8167 8203 8187 814d 01 8166 8103 8196
	hex 01 817f 81a0 0a 00
img47_nt_at3
	hex 02 02 8176 81a6 815a 01 81ae 819d 8151 816a 8103 81a9 81a7
	hex 8103 818c 8152 817a 81b1 01 8155 8182 8199 0c 8168 81bc 8192
	hex 815b 816d 8203 81c1 819f 02 817d 81bf 8203 818f 8157 816f 81be
	hex 8188 0d 8175 81ba 8203 81c6 8103 818e 04 816c 8103 81c4 8203
	hex 81bd 8198 07 8900 8216 8100 8117 8115 8107 8200 8106 810e 8118
	hex 8100 8216 9500 8108 8119 8114 8105 00
img47_nt_at4
	hex 00 8104 810d 811a 810f 19 8109 811b 8113 810c 811c 8110 1b
	hex 810a 811d 811e 8111 1d 810b 8112 2b 00
img47_nt_at5
	hex 00 7f 05 00
img47_pt
	db 6
img47_pal
	hex 0f021628 0f0f0f0f 0f0f0f0f 0f0f0f0f
img47_txt
	db 13
	hex e9 e8 e5 f2 f5 00 00 da e6 e8 eb f2 d2

	; poly-_amory3
img48_nt_at0
	hex 03 08 812e 9701 09 812e 9601 0a 812e 9501 04 81b8 81b2
	hex 81b3 81bb 03 812e 9401 03 81a4 8302 816b 81b7 03 00
img48_nt_at1
	hex 03 812e 9301 03 8189 8402 816b 81b7 03 812e 9201 03 8185
	hex 8502 816b 81b7 03 812e 9101 03 8191 8602 816b 81b7 03 812e
	hex 9001 03 81aa 8602 8156 817b 03 81a3 8802 00
img48_nt_at2
	hex 03 8802 03 8189 8502 8150 817b 03 81a3 9102 03 8184 8402
	hex 8150 8173 03 81a3 9202 03 818b 8302 8150 8173 03 81a3 9302
	hex 04 8164 8153 815e 817c 03 81a3 9402 04 00
img48_nt_at3
	hex 03 06 81a3 9502 09 81a3 9602 08 81a3 9702 07 8140 9801
	hex 06 8140 8901 00
img48_nt_at4
	hex 01 10 8503 8140 1a 8403 8140 1b 8303 8140 1c 8203 8140
	hex 19 00
img48_nt_at5
	hex 01 04 8103 8140 1e 8140 1f 8a00 8650 8140 8155 8114 8555
	hex 8144 8255 8104 8405 8104 8155 01 9d00 00
img48_pt
	db 6
img48_pal
	hex 0f031530 0f212830 0f0f0f0f 0f0f0f0f
img48_txt
	db 13
	hex e9 e8 e5 f2 f5 00 00 da e6 e8 eb f2 d3

	; poly-_sexual
img49_nt_at0
	hex 01 7f 0d 00
img49_nt_at1
	hex 01 74 9803 00
img49_nt_at2
	hex 03 7f 0d 00
img49_nt_at3
	hex 03 5c b002 00
img49_nt_at4
	hex 02 7f 0d 00
img49_nt_at5
	hex 02 44 c000 00
img49_pt
	db 0
img49_pal
	hex 0f14212b 0f0f0f0f 0f0f0f0f 0f0f0f0f
img49_txt
	db 13
	hex e9 e8 e5 f2 f5 00 00 ec de f1 ee da e5

	; queer
img50_nt_at0
	hex 00 40 a028 ac02 00
img50_nt_at1
	hex 02 14 a06f c001 18 00
img50_nt_at2
	hex 02 28 a081 c003 847e 00
img50_nt_at3
	hex 7e 1c f001 00
img50_nt_at4
	hex 01 10 a053 c002 9c43 00
img50_nt_at5
	hex 00 8443 58 88a0 88aa 885a 8855 08 00
img50_pt
	db 5
img50_pal
	hex 0f21310f 0f26350f 0f282930 0f0f0f0f
img50_txt
	db 5
	hex ea ee de de eb

	; rainbow_6stripes
img51_nt_at0
	hex 03 7f 01 8c02 00
img51_nt_at1
	hex 02 74 9803 00
img51_nt_at2
	hex 03 68 a401 00
img51_nt_at3
	hex 01 5c b002 00
img51_nt_at4
	hex 02 50 bc01 00
img51_nt_at5
	hex 00 c401 10 8850 9055 8805 10 00
img51_pt
	db 0
img51_pal
	hex 0f041216 0f192728 0f0f0f0f 0f0f0f0f
img51_txt
	db 15
	hex eb da e2 e7 db e8 f0 d6 ec ed eb e2 e9 de ec

	; rainbow_7stripes
img52_nt_at0
	hex 01 60 a043 8c02 00
img52_nt_at1
	hex 02 34 a07a a003 18 00
img52_nt_at2
	hex 02 28 a046 c001 844e 00
img52_nt_at3
	hex 4e 1c e003 906a 00
img52_nt_at4
	hex 6a 10 c001 a042 9c02 00
img52_nt_at5
	hex 00 c402 08 8850 8855 88a5 88aa 18 00
img52_pt
	db 7
img52_pal
	hex 0f03042c 0f162728 0f19282c 0f0f0f0f
img52_txt
	db 15
	hex eb da e2 e7 db e8 f0 d7 ec ed eb e2 e9 de ec

	; rainbow_8stripes
img53_nt_at0
	hex 02 60 ac01 00
img53_nt_at1
	hex 01 7f 0d 00
img53_nt_at2
	hex 01 08 e002 24 00
img53_nt_at3
	hex 01 3c d002 00
img53_nt_at4
	hex 02 10 e001 1c 00
img53_nt_at5
	hex 00 c402 08 8850 8855 88ff 88af 88aa 10 00
img53_pt
	db 0
img53_pal
	hex 0f03040f 0f16250f 0f192c0f 0f27280f
img53_txt
	db 15
	hex eb da e2 e7 db e8 f0 d8 ec ed eb e2 e9 de ec

	; rainbow_furry1
img54_nt_at0
	hex 02 816b 01 8183 8103 816b 01 8182 01 8158 8101 810c 9500
	hex 8101 816b 01 8183 8101 816b 8103 8182 01 8158 8101 810c 9400
	hex 811c 8101 816b 01 8183 8103 816b 01 8182 01 8158 8101 811b
	hex 810d 8109 8104 9100 811c 8101 816b 01 8183 8101 816b 8103 8182
	hex 01 8159 8155 8152 8101 8117 8107 9100 811c 8101 816b 01 8183
	hex 8103 816b 01 8191 8141 00
img54_nt_at1
	hex 00 8142 8144 8163 814f 8119 8105 11 811c 8101 816b 8102 8183
	hex 8101 816b 814b 818d 8190 8133 8102 8166 8101 8116 12 811c 8101
	hex 816b 8102 8193 814e 8106 812e 8137 8127 8192 8145 8157 811a 13
	hex 811c 8101 816e 813d 8149 8118 8188 813e 8134 814a 8135 8164 811b
	hex 14 8124 8160 813b 8146 8113 02 8136 8147 8131 8167 8101 810c
	hex 05 00
img54_nt_at2
	hex 00 0e 8114 815f 813f 818e 8115 02 812f 814c 818f 8102 8158
	hex 8101 810c 12 8112 8101 816c 8139 04 8130 8102 8182 8102 8158
	hex 8101 810c 11 810e 8120 815c 818a 8326 818c 810f 816b 8103 8182
	hex 8102 8158 8101 810c 11 8111 8121 8101 8161 8170 8174 8102 8183
	hex 8103 816b 8102 8182 8102 8158 8101 810c 0d 00
img54_nt_at3
	hex 01 8400 8110 811e 8123 8124 01 816b 8102 8183 01 816b 8103
	hex 8182 8102 8158 01 810c 9400 811c 01 816b 8102 8183 8103 816b
	hex 8102 8182 8102 8158 01 810c 9400 811c 01 816b 8102 8183 01
	hex 816b 8103 8182 8102 8158 01 810c 9400 811c 01 816b 8102 8183
	hex 8103 816b 8102 8182 8102 8158 01 810c 9400 811c 00
img54_nt_at4
	hex 01 01 816b 8102 8183 01 816b 8103 8182 8102 8158 01 810c
	hex 9400 811c 01 816b 8102 8183 8103 816b 8102 8182 8102 8158 01
	hex 810c 9400 811c 01 816b 8102 8183 01 816b 8103 8182 8102 8158
	hex 01 810c 9400 811c 01 816b 8102 8183 8103 816b 8102 8182 8102
	hex 8158 01 810c 9400 811c 01 816b 8102 8183 01 816b 8103 8182
	hex 00
img54_nt_at5
	hex 00 8102 8158 8101 810c 14 811c 8101 816b 8102 8183 8103 816b
	hex 8102 8182 8102 8158 8101 15 811c 8101 816b 8102 8183 8101 816b
	hex 8103 8182 8102 8158 09 8160 8150 06 8108 8165 8155 8111 05
	hex 8188 8166 8151 06 8108 8165 8151 06 8108 8165 8151 06 8108
	hex 8165 8151 06 8108 8105 00
img54_pt
	db 5
img54_pal
	hex 0f04111b 0f162728 0f1b280f 0f0f0f0f
img54_txt
	db 15
	hex eb da e2 e7 db e8 f0 00 00 df ee eb eb f2 d1

	; rainbow_furry2
img55_nt_at0
	hex 02 6c 81be 81b5 8198 8201 8169 81b2 81b9 0c 8a03 81f2 81ec
	hex 00
img55_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 81e2 81f0 9303 81ef 81e5
	hex 8141 8168 01 81cf 02 81cd 01 8197 8146 81db 81ee 9103 81f3
	hex 81e5 8150 02 81ae 8101 8177 81a2 8101 81aa 02 817f 81db 81f1
	hex 9003 81e7 814a 02 81a4 8201 815c 818b 8201 8179 02 814d 81dd
	hex 8f03 81ed 812d 8172 02 8191 8201 8154 8183 8201 8162 02 81a0
	hex 812f 00
img55_nt_at2
	hex 01 81e3 8e03 81e8 8157 8102 81bf 81b8 8193 02 815d 818c 02
	hex 8164 81bd 81ba 8102 8186 81de 8e03 81e4 816b 8102 8182 01 8174
	hex 8135 812e 816c 819b 8130 8131 816d 01 8153 8102 819a 81da 8e03
	hex 01 8171 8102 02 815b 8102 81c7 81ad 81a9 81c4 8102 818a 02
	hex 8102 819f 01 8703 8702 01 817c 8102 813b 02 81d0 8192 02
	hex 8163 81ce 02 8139 8102 81a7 01 8b02 00
img55_nt_at3
	hex 02 03 8143 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121
	hex 815e 01 819e 813e 0e 8185 816a 02 81a1 8176 8601 8175 8173
	hex 02 8199 8156 0e 8194 8152 81c5 01 81a6 8801 817b 01 81c8
	hex 8181 8165 07 8803 81d9 816f 01 81a8 8129 8601 8126 817d 01
	hex 819d 81d8 9003 81eb 81d2 81ac 01 8188 812b 8120 8133 00
img55_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 81d1 81e1 9103 81e6 81d2 81ab
	hex 81ca 06 81cc 81af 81d1 81dc 9303 81ea 81d4 815a 81b3 81c3 81c9
	hex 81cb 81c6 81b6 8189 81d3 81e0 8a03 0c 814e 8138 8125 8201 8122
	hex 8134 814b 28 00
img55_nt_at5
	hex 00 c402 08 88a0 880a 82a0 04 82a0 82fa 04 82fa 825f 8110
	hex 02 8140 825f 8305 02 8305 08 00
img55_pt
	db 0
img55_pal
	hex 0f300427 0f300412 0f301628 0f30190f
img55_txt
	db 15
	hex eb da e2 e7 db e8 f0 00 00 df ee eb eb f2 d2

	; rainbow_progress
img56_nt_at0
	hex 02 815e 8101 8106 8100 8109 1c 815e 8101 8106 8100 8109 1a
	hex 81b4 01 815e 8101 8106 8100 8109 19 8103 81b4 01 815e 8101
	hex 8106 8100 8109 18 81b4 01 81b4 01 815e 8101 8106 8100 8105
	hex 8301 00
img56_nt_at1
	hex 01 14 8103 81b4 8103 81b4 8102 815e 01 8106 8100 8105 16
	hex 8203 81b4 8102 81b4 8102 815e 01 8106 8100 8105 15 8303 81b4
	hex 8103 81b4 8102 815e 01 8106 8100 8105 14 8403 81b4 8102 81b4
	hex 8102 815e 01 8106 8100 8109 8b02 00
img56_nt_at2
	hex 02 08 8503 81b4 8103 81b4 01 815e 8101 8106 8100 8109 12
	hex 8603 81b4 01 81b4 01 815e 8101 8106 8100 8109 11 8703 81b4
	hex 8103 81b4 01 815e 8101 8106 8100 8109 10 8703 81b6 8103 81b6
	hex 01 818d 8101 8107 8100 810a 9403 00
img56_nt_at3
	hex b6 8203 01 8102 01 8102 818d 8101 8107 8100 810a 9603 01
	hex 8103 01 8102 818d 8101 8107 8100 810a 9603 01 8102 01 8102
	hex 818d 8101 8107 8100 810a 9603 01 8103 01 8102 818d 8101 8107
	hex 8100 8104 9401 8203 01 8102 01 8102 818d 8101 8107 8100 8104
	hex 8501 00
img56_nt_at4
	hex 01 10 8103 81b6 8103 81b6 8102 818d 01 8107 8100 8104 16
	hex 81b6 8102 81b6 8102 818d 01 8107 8100 8104 17 8103 81b6 8102
	hex 818d 01 8107 8100 8104 18 81b6 8102 818d 01 8107 8100 8104
	hex 15 00
img56_nt_at5
	hex 01 04 8102 818d 01 8107 8100 8104 1a 818d 01 8107 8100
	hex 8104 1b 8900 87a0 8110 8108 86fa 8155 8110 810c 85ff 8255 8100
	hex 818c 84af 8155 01 8180 85aa 01 8140 865a 8100 8705 00
img56_pt
	db 2
img56_pal
	hex 0f082125 0f042530 0f121619 0f27280f
img56_txt
	db 15
	hex eb da e2 e7 db e8 f0 e9 eb e8 e0 eb de ec ec

	; rainbow_progress_intersex
img57_nt_at0
	hex b4 01 8102 01 8102 815e 8101 8106 8100 8105 9701 8103 01
	hex 8103 01 8102 815e 8101 8106 8100 8105 9601 81b3 8103 01 8102
	hex 01 8102 815e 8101 8106 8100 8105 9501 8102 81b3 8103 01 8103
	hex 01 8102 815e 8101 8106 8100 8105 9401 8202 81b3 8103 01 8102
	hex 01 8102 815e 8101 8106 8100 00
img57_nt_at1
	hex 02 810b 9303 03 81b3 8103 81b4 8103 81b4 01 815e 8101 8106
	hex 8100 810b 9203 04 81b3 8103 81b4 01 81b4 01 815e 8101 8106
	hex 8100 810b 9103 05 81b3 8103 81b4 8103 81b4 01 815e 8101 8106
	hex 8100 810b 9003 06 81b3 8103 81b4 01 81b4 01 815e 8101 8106
	hex 8100 8109 07 00
img57_nt_at2
	hex 02 0a 819a 8188 8181 8197 01 81b3 8103 81b4 8103 81b4 01
	hex 815e 8101 8106 8100 8109 0f 817e 8131 815b 817f 8137 815a 01
	hex 81b3 8103 81b4 01 81b4 01 815e 8101 8106 8100 8109 0e 8163
	hex 815b 02 817f 813f 02 81b3 8103 81b4 8103 81b4 01 815e 8101
	hex 8106 8100 8109 0d 8161 81a8 02 81a9 8160 02 81b1 8103 81b6
	hex 8103 81b6 01 818d 8101 8107 8100 8108 0d 816d 8159 81a8 00
img57_nt_at3
	hex 02 81a9 817d 814a 01 81b1 8103 81b6 01 81b6 01 818d 8101
	hex 8107 8100 8108 0f 8138 814d 8170 8132 01 81b1 8103 81b6 8103
	hex 81b6 01 818d 8101 8107 8100 8108 14 81b1 8103 81b6 01 81b6
	hex 01 818d 8101 8107 8100 8108 14 81b1 8103 81b6 8103 81b6 01
	hex 818d 8101 8107 8100 8104 9001 04 81b1 8103 81b6 01 81b6 01
	hex 818d 8101 8107 8100 8104 8101 00
img57_nt_at4
	hex 01 10 8302 81b1 8103 81b6 8103 81b6 8102 818d 01 8107 8100
	hex 8104 12 8202 81b1 8103 81b6 8102 81b6 8102 818d 01 8107 8100
	hex 8104 13 8102 81b1 8103 81b6 8103 81b6 8102 818d 01 8107 8100
	hex 8104 14 81b1 8103 81b6 8102 81b6 8102 818d 01 8107 8100 8104
	hex 11 00
img57_nt_at5
	hex 00 8401 8103 81b6 8103 81b6 8102 818d 8101 8107 01 8104 9601
	hex 81b6 8102 81b6 8102 818d 8101 8107 01 8104 9701 08 8160 8150
	hex 86f0 8108 8165 815d 85ff 01 8108 8165 815d 840f 02 8188 8155
	hex 81d1 83f0 01 8180 8156 8195 84af 8180 8156 8115 850a 8106 8105
	hex 06 00
img57_pt
	db 2
img57_pal
	hex 0f042830 0f082125 0f122530 0f161927
img57_txt
	db 23
	hex eb da e2 e7 db e8 f0 e9 eb e8 e0 eb de ec ec e2 e7 ed de eb ec de
	hex f1

	; sapio-_sexual1
img58_nt_at0
	hex 03 7f 0d 00
img58_nt_at1
	hex 03 74 9802 00
img58_nt_at2
	hex 02 7f 0d 00
img58_nt_at3
	hex 02 5c b001 00
img58_nt_at4
	hex 01 7f 0d 00
img58_nt_at5
	hex 01 44 c000 00
img58_pt
	db 0
img58_pal
	hex 0f121819 0f0f0f0f 0f0f0f0f 0f0f0f0f
img58_txt
	db 14
	hex ec da e9 e2 e8 f5 00 ec de f1 ee da e5 d1

	; sapio-_sexual2
img59_nt_at0
	hex 01 7f 0d 00
img59_nt_at1
	hex 01 74 9802 00
img59_nt_at2
	hex 02 7f 0d 00
img59_nt_at3
	hex 02 5c b003 00
img59_nt_at4
	hex 03 7f 0d 00
img59_nt_at5
	hex 03 44 c000 00
img59_pt
	db 0
img59_pal
	hex 0f101521 0f0f0f0f 0f0f0f0f 0f0f0f0f
img59_txt
	db 14
	hex ec da e9 e2 e8 f5 00 ec de f1 ee da e5 d2

	; sapphic
img60_nt_at0
	hex 01 7f 0d 00
img60_nt_at1
	hex 03 f401 0e 8178 816f 816e 8177 06 00
img60_nt_at2
	hex 03 16 8164 8201 8159 1a 8176 8172 8167 8201 815c 8173 8175
	hex 18 8165 8101 8155 8192 818f 8160 8101 815a 18 8166 814c 814b
	hex 8190 8191 814d 814a 815b 10 00
img60_nt_at3
	hex 03 09 8174 8169 8156 8161 815e 8171 1a 8162 8101 8154 815f
	hex 8101 8157 1a 8163 814f 815d 8168 8150 8158 0d b001 00
img60_nt_at4
	hex 01 7f 0d 00
img60_nt_at5
	hex 00 c401 08 8850 8855 8805 08 8850 8855 8805 00
img60_pt
	db 7
img60_pal
	hex 0f132730 0f250f0f 0f0f0f0f 0f0f0f0f
img60_txt
	db 7
	hex ec da e9 e9 e1 e2 dc

	; therian,_otherkin
img61_nt_at0
	hex 02 7f 0d 00
img61_nt_at1
	hex 03 8102 8194 8197 81a8 81a9 8199 8195 9802 8196 819e 81a1 01
	hex 8173 814b 01 81a4 819f 8198 9502 819b 81a0 02 8180 8153 8129
	hex 817f 02 81a3 819d 9302 819a 81a2 02 817e 816e 812c 8156 8145
	hex 817d 02 81a5 819c 8902 0c 8176 810c 8110 815b 8132 8112 810e
	hex 8175 04 00
img61_nt_at2
	hex 03 13 8172 8125 8167 8136 8154 812b 815f 813e 8150 814a 15
	hex 817c 814e 811b 810a 8149 812a 8155 8171 810b 8115 8126 817b 14
	hex 816f 8135 8164 8128 8160 8104 8107 8137 8152 813b 815e 8146 14
	hex 815c 8147 8124 8163 8108 8140 8169 8105 813a 814f 816d 8133 0e
	hex 00
img61_nt_at3
	hex 03 06 815d 8143 8111 8141 815a 813d 8166 8130 816a 8113 8131
	hex 8134 14 8168 8117 8122 8121 8114 811e 8118 811a 8120 8122 811d
	hex 813f 13 8182 8159 8123 8178 8174 812f 8116 811c 8158 814c 817a
	hex 814d 812e 8181 09 8801 8184 81a7 812d 8162 8127 8161 8106 8144
	hex 816c 8109 8138 8151 8139 8157 81a6 8189 9101 8185 02 816b 810f
	hex 813c 8177 00
img61_nt_at4
	hex 03 8179 8165 810d 8142 02 818a 9301 8187 03 8170 811f 8119
	hex 8148 03 818c 9501 8186 8192 06 8193 818b 9701 8183 818d 818f
	hex 8291 8190 818e 8188 a801 00
img61_nt_at5
	hex 01 44 c000 00
img61_pt
	db 3
img61_pal
	hex 0f031b30 0f0f0f0f 0f0f0f0f 0f0f0f0f
img61_txt
	db 16
	hex ed e1 de eb e2 da e7 f4 e8 ed e1 de eb e4 e2 e7

	; trans-_gender
img62_nt_at0
	hex 01 7f 01 8c50 00
img62_nt_at1
	hex 50 14 f802 00
img62_nt_at2
	hex 02 08 a081 e403 00
img62_nt_at3
	hex 03 1c a085 d002 00
img62_nt_at4
	hex 02 30 a06d bc01 00
img62_nt_at5
	hex 01 44 c000 00
img62_pt
	db 5
img62_pal
	hex 0f212530 0f0f0f0f 0f0f0f0f 0f0f0f0f
img62_txt
	db 14
	hex ed eb da e7 ec f5 00 00 e0 de e7 dd de eb

	; trans-_gender_furry1
img63_nt_at0
	hex 02 7f 01 8c54 00
img63_nt_at1
	hex 00 9454 ad01 8144 813c 813d 813f 813b 8142 9901 8140 8129 01
	hex 811b 812f 01 8115 813e 8c01 8c02 814d 02 8149 814c 02 814a
	hex 8402 00
img63_nt_at2
	hex 00 8802 8a53 8189 8186 8185 02 8177 8184 02 8179 8188 8187
	hex 8a53 8a01 812a 01 8123 810d 8105 8120 8134 8107 810a 8121 01
	hex 8116 9401 02 8118 8101 8146 813a 8139 8145 8101 812c 02 9401
	hex 8110 02 8148 8130 02 811c 8147 02 810f 8e01 00
img63_nt_at3
	hex 01 06 812e 8104 8111 8136 8400 8126 8113 8103 811a 0a 8b51
	hex 817f 817c 8600 817b 817a 8b51 8b02 814e 8800 814b 8b02 0b 8138
	hex 810c 8600 8109 8128 17 8132 810e 8106 8112 00
img63_nt_at4
	hex 14 01 8108 810b 811e ac01 a052 bc02 00
img63_nt_at5
	hex 00 c402 08 8850 8855 8805 08 8850 8855 8805 00
img63_pt
	db 1
img63_pal
	hex 0f30250f 0f25210f 0f0f0f0f 0f0f0f0f
img63_txt
	db 22
	hex ed eb da e7 ec f5 00 00 e0 de e7 dd de eb 00 00 df ee eb eb f2 d1

	; trans-_gender_furry2
img64_nt_at0
	hex 01 4c 8802 18 81be 81b5 8198 02 8169 81b2 81b9 0c 882c
	hex 82f4 81fd 819c 00
img64_nt_at1
	hex 02 8121 8134 8142 8248 8147 8138 8124 816e 81fc 82f4 882c 08
	hex 8103 81ef 81e5 8141 8168 01 81cf 02 81cd 01 8197 8146 81db
	hex 81ee 8103 10 81f3 81e5 8150 02 81ae 8101 8177 81a2 8101 81aa
	hex 02 817f 81db 81f1 10 81e7 814a 02 81a4 8201 815c 818b 8201
	hex 8179 02 814d 81dd 0f 81a5 812d 8172 02 8191 8201 8154 8183
	hex 8201 8162 02 81a0 812f 00
img64_nt_at2
	hex 01 817a 8702 87c2 818f 8157 8102 81bf 81b8 8193 02 815d 818c
	hex 02 8164 81bd 81ba 8102 8186 8160 87c2 08 816b 8102 8182 01
	hex 8174 8135 812e 816c 819b 8130 8131 816d 01 8153 8102 819a 10
	hex 8171 8102 02 815b 8102 81c7 81ad 81a9 81c4 8102 818a 02 8102
	hex 819f 10 817c 8102 813b 02 81d0 8192 02 8163 81ce 02 8139
	hex 8102 81a7 0c 00
img64_nt_at3
	hex 02 8401 8170 01 818d 8124 813f 81a3 8401 8178 8144 8121 815e
	hex 01 819e 8801 873d 813c 816a 02 81a1 8176 8601 8175 8173 02
	hex 8199 813a 873d 07 8194 8152 81c5 01 81a6 8801 817b 01 81c8
	hex 8181 8165 0f 81d9 816f 01 81a8 8129 8601 8126 817d 01 819d
	hex 81d8 10 81eb 81d2 81ac 01 8188 812b 8120 8133 00
img64_nt_at4
	hex 02 8137 8123 8128 8159 01 81b0 81d1 81e1 10 8103 81e6 81d2
	hex 81ab 81ca 06 81cc 81af 81d1 81dc 8103 08 88b1 82f6 81ff 8136
	hex 815a 81b3 81c3 81c9 81cb 81c6 81b6 8189 8132 81fa 82f6 88b1 8c01
	hex 814e 8138 8125 8201 8122 8134 814b 9801 08 8801 00
img64_nt_at5
	hex 00 c401 08 88a0 82aa 810a 02 810a 82aa 8255 04 8255 08
	hex 8255 04 8255 82aa 81a0 02 81a0 82aa 880a 00
img64_pt
	db 0
img64_pal
	hex 0f302125 0f30250f 0f21250f 0f0f0f0f
img64_txt
	db 22
	hex ed eb da e7 ec f5 00 00 e0 de e7 dd de eb 00 00 df ee eb eb f2 d2

	; uranic
img65_nt_at0
	hex 01 7f 01 8c02 00
img65_nt_at1
	hex 02 74 9803 00
img65_nt_at2
	hex 03 68 a402 00
img65_nt_at3
	hex 02 5c b001 00
img65_nt_at4
	hex 01 50 bc03 00
img65_nt_at5
	hex 03 44 a000 8850 9055 8805 00
img65_pt
	db 0
img65_pal
	hex 0f011121 0f303138 0f0f0f0f 0f0f0f0f
img65_txt
	db 6
	hex ee eb da e7 e2 dc

