; Image data excluding pattern tables. Generated by convert.py.

IMAGE_COUNT        equ 69
BG_COLOR           equ $0f
RLE_SLICE_LEN      equ 140
LAST_RLE_SLICE_LEN equ 132
NT_TOP_PADDING     equ 192

image_pts
	db 4, 7, 2, 1, 1, 2, 0, 1, 1, 0, 1, 0, 2, 2, 2, 0
	db 5, 1, 7, 1, 0, 1, 1, 1, 1, 1, 1, 2, 7, 0, 1, 7
	db 0, 1, 7, 7, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1
	db 0, 2, 6, 1, 0, 1, 0, 1, 0, 5, 0, 2, 2, 0, 0, 7
	db 3, 1, 1, 0, 0

image_ptrs
	dw img0_ptrs, img1_ptrs, img2_ptrs, img3_ptrs, img4_ptrs
	dw img5_ptrs, img6_ptrs, img7_ptrs, img8_ptrs, img9_ptrs
	dw img10_ptrs, img11_ptrs, img12_ptrs, img13_ptrs, img14_ptrs
	dw img15_ptrs, img16_ptrs, img17_ptrs, img18_ptrs, img19_ptrs
	dw img20_ptrs, img21_ptrs, img22_ptrs, img23_ptrs, img24_ptrs
	dw img25_ptrs, img26_ptrs, img27_ptrs, img28_ptrs, img29_ptrs
	dw img30_ptrs, img31_ptrs, img32_ptrs, img33_ptrs, img34_ptrs
	dw img35_ptrs, img36_ptrs, img37_ptrs, img38_ptrs, img39_ptrs
	dw img40_ptrs, img41_ptrs, img42_ptrs, img43_ptrs, img44_ptrs
	dw img45_ptrs, img46_ptrs, img47_ptrs, img48_ptrs, img49_ptrs
	dw img50_ptrs, img51_ptrs, img52_ptrs, img53_ptrs, img54_ptrs
	dw img55_ptrs, img56_ptrs, img57_ptrs, img58_ptrs, img59_ptrs
	dw img60_ptrs, img61_ptrs, img62_ptrs, img63_ptrs, img64_ptrs
	dw img65_ptrs, img66_ptrs, img67_ptrs, img68_ptrs

img0_ptrs
	dw img0_nt_at0, img0_nt_at1, img0_nt_at2, img0_nt_at3
	dw img0_nt_at4, img0_nt_at5, img0_pal, img0_txt
img1_ptrs
	dw img1_nt_at0, img1_nt_at1, img1_nt_at2, img1_nt_at3
	dw img1_nt_at4, img1_nt_at5, img1_pal, img1_txt
img2_ptrs
	dw img2_nt_at0, img2_nt_at1, img2_nt_at2, img2_nt_at3
	dw img2_nt_at4, img2_nt_at5, img2_pal, img2_txt
img3_ptrs
	dw img3_nt_at0, img3_nt_at1, img3_nt_at2, img3_nt_at3
	dw img3_nt_at4, img3_nt_at5, img3_pal, img3_txt
img4_ptrs
	dw img4_nt_at0, img4_nt_at1, img4_nt_at2, img4_nt_at3
	dw img4_nt_at4, img4_nt_at5, img4_pal, img4_txt
img5_ptrs
	dw img5_nt_at0, img5_nt_at1, img5_nt_at2, img5_nt_at3
	dw img5_nt_at4, img5_nt_at5, img5_pal, img5_txt
img6_ptrs
	dw img6_nt_at0, img6_nt_at1, img6_nt_at2, img6_nt_at3
	dw img6_nt_at4, img6_nt_at5, img6_pal, img6_txt
img7_ptrs
	dw img7_nt_at0, img7_nt_at1, img7_nt_at2, img7_nt_at3
	dw img7_nt_at4, img7_nt_at5, img7_pal, img7_txt
img8_ptrs
	dw img8_nt_at0, img8_nt_at1, img8_nt_at2, img8_nt_at3
	dw img8_nt_at4, img8_nt_at5, img8_pal, img8_txt
img9_ptrs
	dw img9_nt_at0, img9_nt_at1, img9_nt_at2, img9_nt_at3
	dw img9_nt_at4, img9_nt_at5, img9_pal, img9_txt
img10_ptrs
	dw img10_nt_at0, img10_nt_at1, img10_nt_at2, img10_nt_at3
	dw img10_nt_at4, img10_nt_at5, img10_pal, img10_txt
img11_ptrs
	dw img11_nt_at0, img11_nt_at1, img11_nt_at2, img11_nt_at3
	dw img11_nt_at4, img11_nt_at5, img11_pal, img11_txt
img12_ptrs
	dw img12_nt_at0, img12_nt_at1, img12_nt_at2, img12_nt_at3
	dw img12_nt_at4, img12_nt_at5, img12_pal, img12_txt
img13_ptrs
	dw img13_nt_at0, img13_nt_at1, img13_nt_at2, img13_nt_at3
	dw img13_nt_at4, img13_nt_at5, img13_pal, img13_txt
img14_ptrs
	dw img14_nt_at0, img14_nt_at1, img14_nt_at2, img14_nt_at3
	dw img14_nt_at4, img14_nt_at5, img14_pal, img14_txt
img15_ptrs
	dw img15_nt_at0, img15_nt_at1, img15_nt_at2, img15_nt_at3
	dw img15_nt_at4, img15_nt_at5, img15_pal, img15_txt
img16_ptrs
	dw img16_nt_at0, img16_nt_at1, img16_nt_at2, img16_nt_at3
	dw img16_nt_at4, img16_nt_at5, img16_pal, img16_txt
img17_ptrs
	dw img17_nt_at0, img17_nt_at1, img17_nt_at2, img17_nt_at3
	dw img17_nt_at4, img17_nt_at5, img17_pal, img17_txt
img18_ptrs
	dw img18_nt_at0, img18_nt_at1, img18_nt_at2, img18_nt_at3
	dw img18_nt_at4, img18_nt_at5, img18_pal, img18_txt
img19_ptrs
	dw img19_nt_at0, img19_nt_at1, img19_nt_at2, img19_nt_at3
	dw img19_nt_at4, img19_nt_at5, img19_pal, img19_txt
img20_ptrs
	dw img20_nt_at0, img20_nt_at1, img20_nt_at2, img20_nt_at3
	dw img20_nt_at4, img20_nt_at5, img20_pal, img20_txt
img21_ptrs
	dw img21_nt_at0, img21_nt_at1, img21_nt_at2, img21_nt_at3
	dw img21_nt_at4, img21_nt_at5, img21_pal, img21_txt
img22_ptrs
	dw img22_nt_at0, img22_nt_at1, img22_nt_at2, img22_nt_at3
	dw img22_nt_at4, img22_nt_at5, img22_pal, img22_txt
img23_ptrs
	dw img23_nt_at0, img23_nt_at1, img23_nt_at2, img23_nt_at3
	dw img23_nt_at4, img23_nt_at5, img23_pal, img23_txt
img24_ptrs
	dw img24_nt_at0, img24_nt_at1, img24_nt_at2, img24_nt_at3
	dw img24_nt_at4, img24_nt_at5, img24_pal, img24_txt
img25_ptrs
	dw img25_nt_at0, img25_nt_at1, img25_nt_at2, img25_nt_at3
	dw img25_nt_at4, img25_nt_at5, img25_pal, img25_txt
img26_ptrs
	dw img26_nt_at0, img26_nt_at1, img26_nt_at2, img26_nt_at3
	dw img26_nt_at4, img26_nt_at5, img26_pal, img26_txt
img27_ptrs
	dw img27_nt_at0, img27_nt_at1, img27_nt_at2, img27_nt_at3
	dw img27_nt_at4, img27_nt_at5, img27_pal, img27_txt
img28_ptrs
	dw img28_nt_at0, img28_nt_at1, img28_nt_at2, img28_nt_at3
	dw img28_nt_at4, img28_nt_at5, img28_pal, img28_txt
img29_ptrs
	dw img29_nt_at0, img29_nt_at1, img29_nt_at2, img29_nt_at3
	dw img29_nt_at4, img29_nt_at5, img29_pal, img29_txt
img30_ptrs
	dw img30_nt_at0, img30_nt_at1, img30_nt_at2, img30_nt_at3
	dw img30_nt_at4, img30_nt_at5, img30_pal, img30_txt
img31_ptrs
	dw img31_nt_at0, img31_nt_at1, img31_nt_at2, img31_nt_at3
	dw img31_nt_at4, img31_nt_at5, img31_pal, img31_txt
img32_ptrs
	dw img32_nt_at0, img32_nt_at1, img32_nt_at2, img32_nt_at3
	dw img32_nt_at4, img32_nt_at5, img32_pal, img32_txt
img33_ptrs
	dw img33_nt_at0, img33_nt_at1, img33_nt_at2, img33_nt_at3
	dw img33_nt_at4, img33_nt_at5, img33_pal, img33_txt
img34_ptrs
	dw img34_nt_at0, img34_nt_at1, img34_nt_at2, img34_nt_at3
	dw img34_nt_at4, img34_nt_at5, img34_pal, img34_txt
img35_ptrs
	dw img35_nt_at0, img35_nt_at1, img35_nt_at2, img35_nt_at3
	dw img35_nt_at4, img35_nt_at5, img35_pal, img35_txt
img36_ptrs
	dw img36_nt_at0, img36_nt_at1, img36_nt_at2, img36_nt_at3
	dw img36_nt_at4, img36_nt_at5, img36_pal, img36_txt
img37_ptrs
	dw img37_nt_at0, img37_nt_at1, img37_nt_at2, img37_nt_at3
	dw img37_nt_at4, img37_nt_at5, img37_pal, img37_txt
img38_ptrs
	dw img38_nt_at0, img38_nt_at1, img38_nt_at2, img38_nt_at3
	dw img38_nt_at4, img38_nt_at5, img38_pal, img38_txt
img39_ptrs
	dw img39_nt_at0, img39_nt_at1, img39_nt_at2, img39_nt_at3
	dw img39_nt_at4, img39_nt_at5, img39_pal, img39_txt
img40_ptrs
	dw img40_nt_at0, img40_nt_at1, img40_nt_at2, img40_nt_at3
	dw img40_nt_at4, img40_nt_at5, img40_pal, img40_txt
img41_ptrs
	dw img41_nt_at0, img41_nt_at1, img41_nt_at2, img41_nt_at3
	dw img41_nt_at4, img41_nt_at5, img41_pal, img41_txt
img42_ptrs
	dw img42_nt_at0, img42_nt_at1, img42_nt_at2, img42_nt_at3
	dw img42_nt_at4, img42_nt_at5, img42_pal, img42_txt
img43_ptrs
	dw img43_nt_at0, img43_nt_at1, img43_nt_at2, img43_nt_at3
	dw img43_nt_at4, img43_nt_at5, img43_pal, img43_txt
img44_ptrs
	dw img44_nt_at0, img44_nt_at1, img44_nt_at2, img44_nt_at3
	dw img44_nt_at4, img44_nt_at5, img44_pal, img44_txt
img45_ptrs
	dw img45_nt_at0, img45_nt_at1, img45_nt_at2, img45_nt_at3
	dw img45_nt_at4, img45_nt_at5, img45_pal, img45_txt
img46_ptrs
	dw img46_nt_at0, img46_nt_at1, img46_nt_at2, img46_nt_at3
	dw img46_nt_at4, img46_nt_at5, img46_pal, img46_txt
img47_ptrs
	dw img47_nt_at0, img47_nt_at1, img47_nt_at2, img47_nt_at3
	dw img47_nt_at4, img47_nt_at5, img47_pal, img47_txt
img48_ptrs
	dw img48_nt_at0, img48_nt_at1, img48_nt_at2, img48_nt_at3
	dw img48_nt_at4, img48_nt_at5, img48_pal, img48_txt
img49_ptrs
	dw img49_nt_at0, img49_nt_at1, img49_nt_at2, img49_nt_at3
	dw img49_nt_at4, img49_nt_at5, img49_pal, img49_txt
img50_ptrs
	dw img50_nt_at0, img50_nt_at1, img50_nt_at2, img50_nt_at3
	dw img50_nt_at4, img50_nt_at5, img50_pal, img50_txt
img51_ptrs
	dw img51_nt_at0, img51_nt_at1, img51_nt_at2, img51_nt_at3
	dw img51_nt_at4, img51_nt_at5, img51_pal, img51_txt
img52_ptrs
	dw img52_nt_at0, img52_nt_at1, img52_nt_at2, img52_nt_at3
	dw img52_nt_at4, img52_nt_at5, img52_pal, img52_txt
img53_ptrs
	dw img53_nt_at0, img53_nt_at1, img53_nt_at2, img53_nt_at3
	dw img53_nt_at4, img53_nt_at5, img53_pal, img53_txt
img54_ptrs
	dw img54_nt_at0, img54_nt_at1, img54_nt_at2, img54_nt_at3
	dw img54_nt_at4, img54_nt_at5, img54_pal, img54_txt
img55_ptrs
	dw img55_nt_at0, img55_nt_at1, img55_nt_at2, img55_nt_at3
	dw img55_nt_at4, img55_nt_at5, img55_pal, img55_txt
img56_ptrs
	dw img56_nt_at0, img56_nt_at1, img56_nt_at2, img56_nt_at3
	dw img56_nt_at4, img56_nt_at5, img56_pal, img56_txt
img57_ptrs
	dw img57_nt_at0, img57_nt_at1, img57_nt_at2, img57_nt_at3
	dw img57_nt_at4, img57_nt_at5, img57_pal, img57_txt
img58_ptrs
	dw img58_nt_at0, img58_nt_at1, img58_nt_at2, img58_nt_at3
	dw img58_nt_at4, img58_nt_at5, img58_pal, img58_txt
img59_ptrs
	dw img59_nt_at0, img59_nt_at1, img59_nt_at2, img59_nt_at3
	dw img59_nt_at4, img59_nt_at5, img59_pal, img59_txt
img60_ptrs
	dw img60_nt_at0, img60_nt_at1, img60_nt_at2, img60_nt_at3
	dw img60_nt_at4, img60_nt_at5, img60_pal, img60_txt
img61_ptrs
	dw img61_nt_at0, img61_nt_at1, img61_nt_at2, img61_nt_at3
	dw img61_nt_at4, img61_nt_at5, img61_pal, img61_txt
img62_ptrs
	dw img62_nt_at0, img62_nt_at1, img62_nt_at2, img62_nt_at3
	dw img62_nt_at4, img62_nt_at5, img62_pal, img62_txt
img63_ptrs
	dw img63_nt_at0, img63_nt_at1, img63_nt_at2, img63_nt_at3
	dw img63_nt_at4, img63_nt_at5, img63_pal, img63_txt
img64_ptrs
	dw img64_nt_at0, img64_nt_at1, img64_nt_at2, img64_nt_at3
	dw img64_nt_at4, img64_nt_at5, img64_pal, img64_txt
img65_ptrs
	dw img65_nt_at0, img65_nt_at1, img65_nt_at2, img65_nt_at3
	dw img65_nt_at4, img65_nt_at5, img65_pal, img65_txt
img66_ptrs
	dw img66_nt_at0, img66_nt_at1, img66_nt_at2, img66_nt_at3
	dw img66_nt_at4, img66_nt_at5, img66_pal, img66_txt
img67_ptrs
	dw img67_nt_at0, img67_nt_at1, img67_nt_at2, img67_nt_at3
	dw img67_nt_at4, img67_nt_at5, img67_pal, img67_txt
img68_ptrs
	dw img68_nt_at0, img68_nt_at1, img68_nt_at2, img68_nt_at3
	dw img68_nt_at4, img68_nt_at5, img68_pal, img68_txt

	; title_screen
img0_nt_at0
	hex 0103d0 28 81 c1d1 c1ce 05 c165 c166 c11b c169 c147 c161 12
	hex c1c4 41 c1cf 05 c14e 18 41 17 c177 c154 c150 c16d c15b
	hex c16e 02 41 c195 c19d 00
img0_nt_at1
	hex 010203 02 c1b3 c196 c294 c195 c19d 02 c1b3 c196 c294 c195 c19d
	hex 05 c14b c187 c184 c17e c176 03 81 42 02 46 02 46
	hex 05 c13c c13d c128 c107 c17a c172 c183 01 81 02 c19b c1b4
	hex c19c c1b5 c1c3 c1c8 c1bd c1a9 c1bc c1ab 0b c125 c126 c130 c10e
	hex c146 c14a 02 81 02 c19b c1b8 c19b c1b7 c1c3 c1c8 c1af c1ac
	hex c1b9 c1aa 0b c12d c123 c139 c136 c112 03 81 0e 00
img0_nt_at2
	hex 0103ad 09 c12c c124 c118 c117 c11e 03 41 19 c192 c191 04
	hex 41 04 c1cd c1ca 81 01 c1a3 c1a9 c1a4 c1a8 0b c156 c157
	hex c12f c111 c153 03 41 04 c1cc c1c9 c1ae c193 c1bb 81 c1b0
	hex c1ac 0b c154 c151 c15a c16f c155 c170 c16a 01 41 17 c185
	hex c186 c167 00
img0_nt_at3
	hex 010203 c160 c17d c14d c190 01 81 17 c13f c140 c144 c106 c10f
	hex c10b 02 81 04 c198 c1b1 c1c5 c1c6 c19a c1b2 c19e c199 02
	hex c1a7 c1ba 07 c12a c134 c119 c116 c152 03 81 04 c197 c1b6
	hex c1c7 c1cb c1a1 c1a2 c19f c1a5 02 c1a0 c1a6 07 c142 c11c c12b
	hex c133 c14f 03 81 46 02 46 02 42 05 c137 c138 c145
	hex c13e c11f 03 81 c1c2 c1c0 c2be c1bf c1c1 00
img0_nt_at4
	hex 0103c2 02 81 c1c0 c2be c1bf c1c1 02 81 c1c0 0d 41 1f
	hex 41 06 c141 01 c162 c164 c163 c15c c10a c15f c15d c15e 0f
	hex 41 06 c159 01 c121 c175 c174 c158 0b c168 c188 c16c 05
	hex 41 06 c182 01 c181 c17f c17b c16b c180 c17c 04 00
img0_nt_at5
	hex 00012e 45 c13b c13a c149 c178 44 c103 42 c18b c179 c18d c18c
	hex c129 41 c122 c115 c105 c113 c114 c104 c189 c171 c173 c18e c18f
	hex c18a 43 c132 81 c132 81 44 c103 42 c14c c148 c127 c135
	hex c143 41 c11a c120 c14c 81 c135 c11d c131 c108 c10c c10d c110
	hex c109 42 13 c110 01 c110 04 c144 c156 c15f c255 03 c144
	hex c15d c156 c157 c155 03 c104 c10d c117 c106 c117 11 00
img0_pal
	db 16
	hex 0f213013 0f30150f 0f30270f 0f301912
img0_txt
	db 13
	hex ed e2 ed e5 de 00 00 ec dc eb de de e7

	; abro-_sexual
img1_nt_at0
	hex 00017a 7f 7f 42 8c 00
img1_nt_at1
	hex 00037a 94 7f 79 00
img1_nt_at2
	hex 020383 48 a0 3f 25 00
img1_nt_at3
	hex 020381 1c a0 7f 51 00
img1_nt_at4
	hex 01037d 70 a0 3c 00
img1_nt_at5
	hex 000150 7f 45 08 88 d055 20 00
img1_pal
	db 8
	hex 0f253035 0f2b303b
img1_txt
	db 13
	hex da db eb e8 f5 00 00 ec de f1 ee da e5

	; aego-_sexual1
img2_nt_at0
	hex 000108 3f 3f 02 81 4b 00
img2_nt_at1
	hex 000109 53 81 01 c108 5c 81 03 c108 5a 81 05 c108
	hex 58 81 03 44 c180 d302 00
img2_nt_at2
	hex 010286 43 81 09 c180 54 81 0b c180 52 81 0d c180
	hex 50 81 07 48 c136 0e c12f 4c 00
img2_nt_at3
	hex 010236 45 81 0c c12f 53 81 0a c12f 55 81 08 c12f
	hex 4b 0c c105 c600 c104 19 c105 c200 00
img2_nt_at4
	hex 000104 02 81 5b c105 02 81 5d c105 81 4f 3c 00
img2_nt_at5
	hex 000550 3f 15 88 c104 46 c101 08 83 c110 c140 83 48
	hex 08 00
img2_pal
	db 6
	hex 0f00300f 0f14
img2_txt
	db 13
	hex da de e0 e8 f5 00 ec de f1 ee da e5 d1

	; aego-_sexual2
img3_nt_at0
	hex 01026f 7f 61 a0 0c 00
img3_nt_at1
	hex 010375 34 a0 78 00
img3_nt_at2
	hex 000356 68 a0 3f 01 c455 00
img3_nt_at3
	hex 035579 5c 3f 21 90 00
img3_nt_at4
	hex 015a79 90 3f 01 60 dc02 00
img3_nt_at5
	hex 000002 bf 85 3f 01 00
img3_pal
	db 4
	hex 0f10131c
img3_txt
	db 13
	hex da de e0 e8 f5 00 ec de f1 ee da e5 d2

	; agender
img4_nt_at0
	hex 000112 3f 21 a0 4c 00
img4_nt_at1
	hex 010375 34 a0 78 00
img4_nt_at2
	hex 020382 68 a0 3f 01 c47d 00
img4_nt_at3
	hex 03797d 9c 3f 21 50 00
img4_nt_at4
	hex 014879 90 3f 01 60 dc00 00
img4_nt_at5
	hex 000000 3f 3f 06 00
img4_pal
	db 4
	hex 0f002930
img4_txt
	db 7
	hex da e0 de e7 dd de eb

	; andro-_gyne
img5_nt_at0
	hex 010274 4a 81 0a c1a6 ca03 4a 81 0a c1a6 ca03 4a 81
	hex 0a c1a6 ca03 4a 81 0a c1a6 ca03 4a 81 01 00
img5_nt_at1
	hex 0103a6 09 81 4a ca02 c174 0a 81 4a ca02 c174 0a 81
	hex 4a ca02 c174 0a 81 4a ca02 c174 0a 81 42 00
img5_nt_at2
	hex 020374 48 0a 81 ca01 c1a6 4a 0a 81 ca01 c1a6 4a 0a
	hex 81 ca01 c1a6 4a 0a 81 ca01 c1a6 4a 04 00
img5_nt_at3
	hex 010274 46 81 0a c1a6 ca03 4a 81 0a c1a6 ca03 4a 81
	hex 0a c1a6 ca03 4a 81 0a c1a6 ca03 4a 81 05 00
img5_nt_at4
	hex 0103a6 05 81 4a ca02 c174 0a 81 4a ca02 c174 0a 81
	hex 4a ca02 c174 0a 81 4a ca02 c174 0a 81 46 00
img5_nt_at5
	hex 020374 44 0a 81 ca01 c1a6 4a 0a 81 ca01 c1a6 4a ff00
	hex c100 00
img5_pal
	db 4
	hex 0f13152c
img5_txt
	db 14
	hex da e7 dd eb e8 f5 00 00 00 00 e0 f2 e7 de

	; andro-_sexual
img6_nt_at0
	hex 000002 bf bf 8e 00
img6_nt_at1
	hex 000102 bf b5 58 00
img6_nt_at2
	hex 000001 bf bf 8e 00
img6_nt_at3
	hex 000103 7f 5d b0 00
img6_nt_at4
	hex 000003 bf bf 8e 00
img6_nt_at5
	hex 000003 bf 85 3f 01 00
img6_pal
	db 4
	hex 0f172124
img6_txt
	db 14
	hex da e7 dd eb e8 f5 00 00 ec de f1 ee da e5

	; a-_romantic
img7_nt_at0
	hex 000158 7f 7f 42 8c 00
img7_nt_at1
	hex 000258 94 7f 79 00
img7_nt_at2
	hex 02037e 08 a0 7f 65 00
img7_nt_at3
	hex 01037a 5c a0 3f 11 00
img7_nt_at4
	hex 00013d 70 a0 3c 00
img7_nt_at5
	hex 005055 3f 0d 48 88 28 00
img7_pal
	db 7
	hex 0f002930 0f1a29
img7_txt
	db 10
	hex da f5 eb e8 e6 da e7 ed e2 dc

	; a-_romantic_asexual
img8_nt_at0
	hex 000158 7f 7f 42 8c 00
img8_nt_at1
	hex 000258 94 7f 79 00
img8_nt_at2
	hex 02037e 08 a0 7f 65 00
img8_nt_at3
	hex 020383 5c a0 3f 11 00
img8_nt_at4
	hex 01026e 70 a0 3c 00
img8_nt_at5
	hex 000150 7f 45 08 88 d055 20 00
img8_pal
	db 8
	hex 0f0c2130 0f172830
img8_txt
	db 18
	hex da f5 eb e8 e6 da e7 ed e2 dc 00 da ec de f1 ee da e5

	; asexual
img9_nt_at0
	hex 000000 3f 3f 0e 00
img9_nt_at1
	hex 000001 34 bf 99 00
img9_nt_at2
	hex 000103 7f 69 a4 00
img9_nt_at3
	hex 000003 bf bf 8e 00
img9_nt_at4
	hex 000203 90 7f 7d 00
img9_nt_at5
	hex 000002 bf 85 3f 01 00
img9_pal
	db 4
	hex 0f001430
img9_txt
	db 7
	hex da ec de f1 ee da e5

	; asexual_furry1
img10_nt_at0
	hex 000000 3f 3f 0e 00
img10_nt_at1
	hex 000147 34 4d 81 c13f c140 c142 c13e c145 59 c143 c12b 01
	hex c11d c131 01 c117 c141 58 c135 02 c119 c12d 02 c121 44
	hex 00
img10_nt_at2
	hex 000147 52 81 c144 c133 02 c11b c12f 02 c11f c146 c145 54
	hex c12c 01 c125 c10e c106 c122 c136 c108 c10b c123 01 c118 54
	hex 02 c11a 41 c14a c13c c13b c149 41 c12e 02 54 c111 02
	hex c14c c132 02 c11e c14b 02 c110 4e 00
img10_nt_at3
	hex 000130 46 81 c105 c113 c138 04 c128 c115 c104 c11c 55 c137
	hex c127 06 c126 c124 56 c139 08 c129 56 c13a c10d 06 c10a
	hex c12a 57 c134 c10f c107 c114 00
img10_nt_at4
	hex 010916 81 41 c10c c120 3f 3f 0a 00
img10_nt_at5
	hex 000155 7f 45 20 c850 83 c151 c154 83 c8aa c80a 00
img10_pal
	db 10
	hex 0f000f0f 0f300f0f 0f14
img10_txt
	db 15
	hex da ec de f1 ee da e5 00 00 df ee eb eb f2 d1

	; asexual_furry2
img11_nt_at0
	hex 000509 3f 2d 41 81 c10d c201 c112 c10b c107 16 c104 c10c
	hex 00
img11_nt_at1
	hex 000102 c121 c134 c142 c248 c147 c138 c124 c111 c106 13 c108 c110
	hex c141 c168 81 c1cf 82 c1cd 81 c197 c146 c115 c10a 09 88
	hex c1f3 c1e5 c150 82 c1ae 41 c177 c1a2 41 c1aa 82 c17f c1db
	hex c1f1 90 c1e7 c14a 82 c1a4 42 c15c c18b 42 c179 82 c14d
	hex c1dd 8f c1a5 c12d c172 82 c191 42 c154 c183 42 c162 82
	hex c1a0 c12f 00
img11_nt_at2
	hex 01027a 81 4e c190 c157 41 c1bf c1b8 c193 02 c15d c18c 02
	hex c164 c1bd c1ba 41 c186 c161 4e c17e c16b 41 c182 01 c174
	hex c135 c12e c16c c19b c130 c131 c16d 01 c153 41 c19a c14f 4e
	hex 01 c171 41 02 c15b 41 c1c7 c1ad c1a9 c1c4 41 c18a 02
	hex 41 c19f 01 47 08 c17c 41 c13b 02 c1d0 c192 02 c163
	hex c1ce 02 c139 41 c1a7 0c 00
img11_nt_at3
	hex 010270 04 81 41 c18d c124 c13f c1a3 04 c178 c144 c121 c15e
	hex 41 c19e 10 c16a 42 c1a1 c176 06 c175 c173 42 c199 10
	hex c152 c1c5 41 c1a6 08 c17b 41 c1c8 c181 11 c16f 41 c1a8
	hex c129 06 c126 c17d 41 c19d 13 c1ac 41 c188 c12b c120 c133
	hex 00
img11_nt_at4
	hex 010237 81 c123 c128 c159 41 c1b0 0a 49 c187 c12a c1ab c1ca
	hex 46 c1cc c1af c127 c158 53 c196 c136 c15a c1b3 c1c3 c1c9 c1cb
	hex c1c6 c1b6 c189 c132 c167 56 c14e c138 c125 02 c122 c134 c14b
	hex 68 00
img11_nt_at5
	hex 000255 7f 45 18 82 04 82 c205 04 c205 18 00
img11_pal
	db 7
	hex 0f301400 0f3000
img11_txt
	db 15
	hex da ec de f1 ee da e5 00 00 df ee eb eb f2 d2

	; autism
img12_nt_at0
	hex 000001 bf bf 8e 00
img12_nt_at1
	hex 010220 3f 1c c10e c11b 81 c11f c112 08 c111 c11c 81 c11e
	hex c10f 0d c11a c149 44 c13a c117 04 c114 c133 44 00
img12_nt_at2
	hex 0102a3 c16d c11d 0c c14d 81 c18e c17b c17d c194 c1a2 c176 c12a
	hex 02 c125 c153 81 c197 c183 c17b c189 c1a2 c171 0b c12e 41
	hex c175 04 c150 c19a c103 c1b3 c132 41 c19d c173 04 c151 41
	hex c134 0a c145 41 c164 05 c13c c1bc c1af 41 c191 c15f 05
	hex c143 41 c169 0a c145 41 c164 05 c10e c141 41 c1ab c1a7
	hex c10f 05 c13f 41 c169 09 00
img12_nt_at3
	hex 01027a 01 c13e 41 c16a 04 c116 c148 41 c185 c1a8 c103 c16c
	hex c119 04 c146 41 c162 0b c181 81 c12b c110 c115 c127 c158
	hex c1a1 c177 02 c155 c1a0 81 c12c c118 c110 c126 c158 c187 0c
	hex c142 c19b 44 c19c c16f 04 c14b c199 44 c19e c167 0d c13c
	hex c17e c198 c190 c172 08 c14f c18b c198 c184 c15f 17 00
img12_nt_at4
	hex 000001 bf bf 8e 00
img12_nt_at5
	hex 000188 7f 45 19 81 c122 01 c150 c1dd c133 02 c1aa 01
	hex c154 c115 01 c1ff 02 81 c166 c105 01 c1cc c133 11 00
img12_pal
	db 15
	hex 0f37270f 0f372127 0f37250f 0f3729
img12_txt
	db 6
	hex da ee ed e2 ec e6

	; autism_hstripes
img13_nt_at0
	hex 010224 3f 21 a0 4c 00
img13_nt_at1
	hex 010220 74 e0a9 07 c10e c11b 81 c11f c112 08 c111 c11c 81
	hex c11e c10f 0d c11a c149 44 c13a c117 04 c114 c133 44 00
img13_nt_at2
	hex 0102a3 c16d c11d 0c c14d 81 c18e c17b c17d c194 c1a2 c176 c12a
	hex 02 c125 c153 81 c197 c183 c17b c189 c1a2 c171 0b c12e 41
	hex c175 04 c150 c19a 41 c139 c132 41 c19d c173 04 c151 41
	hex c134 0a c145 41 c164 05 c13c c18c 42 c191 c15f 05 c143
	hex 41 c169 0a c145 41 c164 05 c10e c141 42 c166 c10f 05
	hex c13f 41 c169 09 00
img13_nt_at3
	hex 01027a 01 c13e 41 c16a 04 c116 c148 41 c185 c17f 41 c16c
	hex c119 04 c146 41 c162 0b c181 81 c12b c110 c115 c127 c158
	hex c1a1 c177 02 c155 c1a0 81 c12c c118 c110 c126 c158 c187 0c
	hex c142 c19b 44 c19c c16f 04 c14b c199 44 c19e c167 0d c13c
	hex c17e c198 c190 c172 08 c14f c18b c198 c184 c15f 07 d0a4 00
img13_nt_at4
	hex 029fa4 90 3f 01 60 dc01 00
img13_nt_at5
	hex 000155 7f 45 18 90 c8a5 c8ff c80f 00
img13_pal
	db 15
	hex 0f16260f 0f283026 0f28302a 0f1a2a
img13_txt
	db 14
	hex da ee ed e2 ec e6 e1 ec ed eb e2 e9 de ec

	; autism_vstripes
img14_nt_at0
	hex 010245 0a 81 41 09 c1a6 14 81 41 09 c1a6 14 81
	hex 41 09 c1a6 14 81 41 09 c1a6 14 81 41 00
img14_nt_at1
	hex 0102a6 09 81 14 c145 41 09 81 14 c1a5 c103 09 81
	hex 11 c10e c11b c120 c1b5 c1b2 08 c111 c1b6 c120 c11e c10f 0d
	hex c11a c149 44 c13a c117 04 c114 c133 44 00
img14_nt_at2
	hex 010245 c16d c11d 0c c14d c1a3 c18e c17b c1b8 c1aa c1a2 c176 c12a
	hex 02 c125 c153 c1a3 c197 c1bb c17b c189 c1a2 c171 0b c12e 41
	hex c175 02 81 41 c150 c19a 41 c139 c132 41 c19d c173 01
	hex c1a6 02 c151 41 c134 0a 81 41 c164 02 81 41 01
	hex c13c c18c 42 c191 c15f 02 c1a6 02 c143 41 c169 0a 81
	hex 41 c164 02 81 41 01 c10e c141 42 c166 c10f 02 c1a6
	hex 02 c13f 41 c169 09 00
img14_nt_at3
	hex 01027a 01 c13e 41 c16a 02 c145 41 c116 c148 41 c185 c17f
	hex 41 c16c c119 01 c1a6 02 c146 41 c162 0b c181 81 c12b
	hex c110 c1b4 c1b1 c158 c1a1 c177 02 c155 c1a0 81 c12c c1b7 c110
	hex c126 c158 c187 0c c142 c19b 44 c19c c16f 04 c14b c199 44
	hex c19e c167 0d c13c c17e c198 c1ba c1ac 08 c14f c1b9 c198 c184
	hex c15f 11 c1a5 c103 04 00
img14_nt_at4
	hex 0145a6 05 81 14 41 c102 09 81 14 41 c102 09 81
	hex 14 41 c102 09 81 14 41 c102 09 81 06 00
img14_nt_at5
	hex 000155 4e c145 c102 49 c1a6 54 c145 c102 49 c1a6 4a 0a
	hex c1c0 c250 c190 c2a0 02 c1cc 82 c199 c2aa 03 82 c199 c2aa
	hex 02 c1cc 82 c199 c2aa 03 82 c199 c2aa 02 c1cc 82 c199
	hex c2aa 02 c10c c205 c109 c20a 00
img14_pal
	db 15
	hex 0f16301a 0f1a3012 0f12300f 0f161a
img14_txt
	db 14
	hex da ee ed e2 ec e6 ef ec ed eb e2 e9 de ec

	; auto-_sexual
img15_nt_at0
	hex 000002 bf bf 8e 00
img15_nt_at1
	hex 000002 bf bf 8e 00
img15_nt_at2
	hex 000102 bf a9 64 00
img15_nt_at3
	hex 000001 bf bf 8e 00
img15_nt_at4
	hex 000001 bf bf 8e 00
img15_nt_at5
	hex 000001 bf 85 3f 01 00
img15_pal
	db 3
	hex 0f0031
img15_txt
	db 13
	hex da ee ed e8 f5 00 00 ec de f1 ee da e5

	; bear
img16_nt_at0
	hex 00016d 65 c137 c134 c132 5d c11c 02 c126 c12e c12f c136 54
	hex 82 c191 01 c190 c18f c184 c13a c189 c18b 01 c112 c192 93
	hex c302 c13f 01 c14b c15d c15b c15e c155 c13c 01 00
img16_nt_at1
	hex 000280 c14c c161 55 c15a c13e c149 03 c14a c156 c144 c159 c145
	hex c15f 51 83 c160 c19b c19a 07 c197 c199 91 c303 c164 01
	hex c169 c10a 05 c162 c166 d203 c301 c11d c105 c114 c123 03 c104
	hex c10c c118 cb01 00
img16_nt_at2
	hex 00016e 4b c135 c122 c138 c120 02 c108 c115 55 83 c18c 01
	hex c188 c18e 01 c13b c186 96 c402 c140 c143 c154 c139 c147 d702
	hex c703 c167 d803 c482 00
img16_nt_at3
	hex 027a82 9c 3f 21 50 00
img16_nt_at4
	hex 01317a 90 3f 01 60 dc00 00
img16_nt_at5
	hex 0050a5 3f 0d 48 c855 81 c1a9 c1a0 85 c80a 18 00
img16_pal
	db 11
	hex 0f003037 0f071727 0f2737
img16_txt
	db 4
	hex db de da eb

	; bigender
img17_nt_at0
	hex 01025e 3f 21 a0 4c 00
img17_nt_at1
	hex 02037c 34 a0 60 18 00
img17_nt_at2
	hex 01026e 68 a0 3f 01 c458 00
img17_nt_at3
	hex 020358 9c 3f 01 60 d081 00
img17_nt_at4
	hex 027281 90 3f 01 60 dc01 00
img17_nt_at5
	hex 000150 7f 45 08 88 c855 c8a5 c8aa c80a 10 00
img17_pal
	db 11
	hex 0f112133 0f142433 0f3033
img17_txt
	db 8
	hex db e2 e0 de e7 dd de eb

	; bisexual
img18_nt_at0
	hex 000003 bf bf 8e 00
img18_nt_at1
	hex 000003 bf bf 8e 00
img18_nt_at2
	hex 020383 48 a0 3f 25 00
img18_nt_at3
	hex 010262 5c a0 3f 11 00
img18_nt_at4
	hex 000001 bf bf 8e 00
img18_nt_at5
	hex 000001 bf 85 3f 01 00
img18_pal
	db 4
	hex 0f121315
img18_txt
	db 8
	hex db e2 ec de f1 ee da e5

	; bisexual_furry1
img19_nt_at0
	hex 000001 bf bf 8e 00
img19_nt_at1
	hex 000102 7f 42 c147 c13f c140 c142 c13e c145 59 c143 c12b 01
	hex c11d c131 01 c117 c141 4c 8c c152 02 c14e c151 02 c14f
	hex 84 00
img19_nt_at2
	hex 000172 c802 8a c199 c196 c195 02 c187 c194 02 c189 c198 c197
	hex 8a 4a c12c 01 c125 c10e c106 c122 c136 c108 c10b c123 01
	hex c118 54 02 c11a 41 c14a c13c c13b c149 41 c12e 02 54
	hex c111 02 c14c c132 02 c11e c14b 02 c110 4e 00
img19_nt_at3
	hex 00015e 46 c130 c105 c113 c138 04 c128 c115 c104 c11c 4a 8b
	hex c18f c18c 06 c18b c18a 8b cb02 c153 08 c150 cb02 4b c13a
	hex c10d 06 c10a c12a 57 c134 c10f c107 c114 00
img19_nt_at4
	hex 010916 81 41 c10c c120 3f 3f 0a 00
img19_nt_at5
	hex 0001fa 7f 45 18 c850 c855 83 c1f2 c1f8 83 c8ff c80f 00
img19_pal
	db 14
	hex 0f150f0f 0f13150f 0f13120f 0f12
img19_txt
	db 16
	hex db e2 ec de f1 ee da e5 00 00 df ee eb eb f2 d1

	; bisexual_furry2
img20_nt_at0
	hex 02b5be 3f 2d 81 41 c198 c201 c169 c1b2 c1b9 16 c1f2 c1ec
	hex 00
img20_nt_at1
	hex 0102e5 c121 c134 c142 c248 c147 c138 c124 c1e2 c1f0 53 c1b7 81
	hex c141 c168 41 c1cf 42 c1cd 41 c197 c146 c1db c1b4 51 c1f3
	hex 81 c150 42 c1ae 01 c177 c1a2 01 c1aa 42 c17f c1db c1f1
	hex 50 c1e7 c14a 42 c1a4 02 c15c c18b 02 c179 42 c14d c1dd
	hex 48 c703 c1ed c12d c172 42 c191 02 c154 c183 02 c162 42
	hex c1a0 c12f 00
img20_nt_at2
	hex 0102f7 c1e3 c703 87 c1fe c157 41 c1bf c1b8 c193 02 c15d c18c
	hex 02 c164 c1bd c1ba 41 c186 c1f9 87 47 c17e c16b 41 c182
	hex 01 c174 c135 c12e c16c c19b c130 c131 c16d 01 c153 41 c19a
	hex c14f 4e 01 c171 41 02 c15b 41 c1c7 c1ad c1a9 c1c4 41
	hex c18a 02 41 c19f 01 4e 01 c17c 41 c13b 02 c1d0 c192
	hex 02 c163 c1ce 02 c139 41 c1a7 01 4b 00
img20_nt_at3
	hex 0102f5 43 c143 c170 41 c18d c124 c13f c1a3 04 c178 c144 c121
	hex c15e 41 c19e c13e 47 87 c1fb c16a 42 c1a1 c176 06 c175
	hex c173 42 c199 c1f8 87 c703 c1e9 c152 c1c5 41 c1a6 08 c17b
	hex 41 c1c8 c181 c1df c703 48 c1d9 c16f 41 c1a8 c129 06 c126
	hex c17d 41 c19d c1d8 50 c1eb c1d2 c1ac 41 c188 c12b c120 c133
	hex 00
img20_nt_at4
	hex 0237d1 41 c123 c128 c159 01 c1b0 81 c1e1 11 c187 c1d2 c1ab
	hex c1ca 06 c1cc c1af 81 c158 13 c1ea c1d4 c15a c1b3 c1c3 c1c9
	hex c1cb c1c6 c1b6 c189 c1d3 c1e0 16 c14e c138 c125 c201 c122 c134
	hex c14b 28 00
img20_nt_at5
	hex 00020a 7f 45 08 c8a0 c2aa c12a 82 c18a c2aa 82 04 82
	hex 08 c2f5 c110 02 c140 c2f5 c2ff c1f7 c2f0 c1fd c2ff c80f 00
img20_pal
	db 15
	hex 0f301315 0f301312 0f30150f 0f3012
img20_txt
	db 16
	hex db e2 ec de f1 ee da e5 00 00 df ee eb eb f2 d2

	; butch_lesbian
img21_nt_at0
	hex 01025e 3f 21 a0 4c 00
img21_nt_at1
	hex 02037c 34 a0 60 d801 00
img21_nt_at2
	hex 010378 28 a0 7f 41 c484 00
img21_nt_at3
	hex 020384 9c 3f 01 60 d081 00
img21_nt_at4
	hex 027281 90 3f 01 60 dc01 00
img21_nt_at5
	hex 0001a0 7f 45 18 88 c8aa c85a c855 c805 00
img21_pal
	db 12
	hex 0f011121 0f031323 0f212330
img21_txt
	db 13
	hex db ee ed dc e1 00 e5 de ec db e2 da e7

	; demi-_fluid
img22_nt_at0
	hex 00015e 7f 61 a0 4c 00
img22_nt_at1
	hex 010203 34 c85a d077 c87e 48 98 48 90 00
img22_nt_at2
	hex 000203 88 48 98 7f 65 00
img22_nt_at3
	hex 02036f 24 58 08 58 08 58 88 c87a 00
img22_nt_at4
	hex 017a83 48 88 3f 01 e072 1c 00
img22_nt_at5
	hex 0001aa 7f 45 10 c850 c455 82 02 88 c455 82 02 c805
	hex 08 00
img22_pal
	db 12
	hex 0f001031 0f103538 0f10303b
img22_txt
	db 13
	hex dd de e6 e2 f5 00 00 00 df e5 ee e2 dd

	; demiflux
img23_nt_at0
	hex 00015e 7f 61 a0 4c 00
img23_nt_at1
	hex 010257 34 a0 78 00
img23_nt_at2
	hex 02037f 28 a0 60 20 c474 00
img23_nt_at3
	hex 010374 9c 3f 01 60 d081 00
img23_nt_at4
	hex 017281 90 3f 01 60 1c 00
img23_nt_at5
	hex 000150 7f 45 10 88 c855 c8a5 c80a c805 08 00
img23_pal
	db 11
	hex 0f001031 0f103638 0f3138
img23_txt
	db 8
	hex dd de e6 e2 df e5 ee f1

	; demi-_gender
img24_nt_at0
	hex 01025e 3f 21 a0 4c 00
img24_nt_at1
	hex 02037c 34 a0 60 18 00
img24_nt_at2
	hex 01026e 68 a0 3f 01 c458 00
img24_nt_at3
	hex 020358 9c 3f 01 60 d081 00
img24_nt_at4
	hex 027281 90 3f 01 60 dc01 00
img24_nt_at5
	hex 000150 7f 45 18 88 c855 c805 10 00
img24_pal
	db 7
	hex 0f001038 0f3038
img24_txt
	db 13
	hex dd de e6 e2 f5 00 00 e0 de e7 dd de eb

	; demigirl
img25_nt_at0
	hex 01025e 3f 21 a0 4c 00
img25_nt_at1
	hex 02037c 34 a0 60 18 00
img25_nt_at2
	hex 01026e 68 a0 3f 01 c458 00
img25_nt_at3
	hex 020358 9c 3f 01 60 d081 00
img25_nt_at4
	hex 027281 90 3f 01 60 dc01 00
img25_nt_at5
	hex 000150 7f 45 18 88 c855 c805 10 00
img25_pal
	db 7
	hex 0f001035 0f3035
img25_txt
	db 8
	hex dd de e6 e2 e0 e2 eb e5

	; demiguy
img26_nt_at0
	hex 01025e 3f 21 a0 4c 00
img26_nt_at1
	hex 02037c 34 a0 60 18 00
img26_nt_at2
	hex 01026e 68 a0 3f 01 c458 00
img26_nt_at3
	hex 020358 9c 3f 01 60 d081 00
img26_nt_at4
	hex 027281 90 3f 01 60 dc01 00
img26_nt_at5
	hex 000150 7f 45 18 88 c855 c805 10 00
img26_pal
	db 7
	hex 0f001031 0f3031
img26_txt
	db 7
	hex dd de e6 e2 e0 ee f2

	; demi-_sexual
img27_nt_at0
	hex 00030d 81 5f 01 81 5e 02 81 5d 03 81 5c 04
	hex 81 47 00
img27_nt_at1
	hex 00030d 54 05 81 5a 06 81 59 07 81 58 08 81
	hex 4f 00
img27_nt_at2
	hex 000103 88 09 c10d 96 0a c106 55 0b c106 54 0b c104
	hex 54 04 00
img27_nt_at3
	hex 00020a 06 c104 d501 09 81 56 08 81 57 07 81 58
	hex 06 81 49 00
img27_nt_at4
	hex 00020a 50 05 81 5a 04 81 5b 03 81 5c 02 81
	hex 59 00
img27_nt_at5
	hex 00020a 44 01 81 5e 81 5f 3f 01 00
img27_pal
	db 4
	hex 0f041030
img27_txt
	db 13
	hex dd de e6 e2 f5 00 00 ec de f1 ee da e5

	; dis-_ability
img28_nt_at0
	hex 01025e 81 41 c182 c103 c17c 01 81 41 c10c d700 01 81
	hex 41 c182 c103 c17c 01 81 41 c10c d600 c106 01 81 41
	hex c182 c103 c17c 01 81 41 c10c d600 c106 01 81 41 c182
	hex c103 c17c 01 81 41 c10c d600 c106 01 81 41 c182 c103
	hex c17c 01 81 41 00
img28_nt_at1
	hex 01025e c10c d600 c106 01 81 41 c182 c103 c17c 01 81 41
	hex c10c d600 c106 01 81 41 c182 c103 c17c 01 81 41 c10c
	hex d600 c106 01 81 41 c182 c103 c17c 01 81 41 c10c d600
	hex c106 01 81 41 c182 c103 c17c 01 81 41 c10c c700 00
img28_nt_at2
	hex 01025e cf00 c106 01 81 41 c182 c103 c17c 01 81 41 c10c
	hex d600 c106 01 81 41 c182 c103 c17c 01 81 41 c10c d600
	hex c106 01 81 41 c182 c103 c17c 01 81 41 c10c d600 c106
	hex 01 81 41 c182 c103 c17c 01 81 41 c10c cf00 00
img28_nt_at3
	hex 01025e c700 c106 01 81 41 c182 c103 c17c 01 81 41 c10c
	hex d600 c106 01 81 41 c182 c103 c17c 01 81 41 c10c d600
	hex c106 01 81 41 c182 c103 c17c 01 81 41 c10c d600 c106
	hex 01 81 41 c182 c103 c17c 01 81 41 c10c d600 c106 00
img28_nt_at4
	hex 01025e 01 81 41 c182 c103 c17c 01 81 41 c10c d600 c106
	hex 01 81 41 c182 c103 c17c 01 81 41 c10c d600 c106 01
	hex 81 41 c182 c103 c17c 01 81 41 c10c d600 c106 01 81
	hex 41 c182 c103 c17c 01 81 41 c10c d600 c106 01 81 41
	hex c182 c103 c17c 01 81 00
img28_nt_at5
	hex 000102 81 c10c 16 c106 41 c15e 81 c182 c103 c17c 41 c15e
	hex 81 c10c 16 c106 41 c15e 81 c182 c103 c17c 41 c15e 81
	hex c10c 08 c150 07 c145 c151 07 c145 c151 07 c145 c151 07
	hex c145 c151 07 c145 c151 07 c105 41 01 00
img28_pal
	db 8
	hex 0f212a30 0f262830
img28_txt
	db 12
	hex dd e2 ec f5 00 da db e2 e5 e2 ed f2

	; fray-_sexual
img29_nt_at0
	hex 000002 bf bf 8e 00
img29_nt_at1
	hex 000102 b4 7f 59 00
img29_nt_at2
	hex 000103 7f 69 a4 00
img29_nt_at3
	hex 000003 bf bf 8e 00
img29_nt_at4
	hex 000103 90 7f 7d 00
img29_nt_at5
	hex 000155 7f 45 18 88 c805 18 00
img29_pal
	db 6
	hex 0f001130 0f3c
img29_txt
	db 13
	hex df eb da f2 f5 00 00 ec de f1 ee da e5

	; gay_men
img30_nt_at0
	hex 01025e 3f 21 a0 4c 00
img30_nt_at1
	hex 02037c 34 a0 60 18 00
img30_nt_at2
	hex 02037f 28 a0 7f 41 c47b 00
img30_nt_at3
	hex 01037b 9c 3f 01 60 d081 00
img30_nt_at4
	hex 027281 90 3f 01 60 dc01 00
img30_nt_at5
	hex 000150 7f 45 08 88 c855 c8a5 c8aa c80a 10 00
img30_pal
	db 12
	hex 0f031222 0f0b1b2b 0f222b30
img30_txt
	db 11
	hex e0 da f2 00 00 00 00 00 e6 de e7

	; gender-_fluid
img31_nt_at0
	hex 000280 7f 7f 42 8c 00
img31_nt_at1
	hex 000380 94 7f 79 00
img31_nt_at2
	hex 01037f 48 a0 3f 25 00
img31_nt_at3
	hex 000107 5c a0 3f 11 00
img31_nt_at4
	hex 000105 30 a0 7c 00
img31_nt_at5
	hex 000155 7f 45 30 88 c805 00
img31_pal
	db 6
	hex 0f142530 0f02
img31_txt
	db 15
	hex e0 de e7 dd de eb f5 00 00 00 df e5 ee e2 dd

	; gender-_queer
img32_nt_at0
	hex 000001 bf bf 8e 00
img32_nt_at1
	hex 000103 7f 75 98 00
img32_nt_at2
	hex 000003 bf bf 8e 00
img32_nt_at3
	hex 000203 bf 9d 70 00
img32_nt_at4
	hex 000002 bf bf 8e 00
img32_nt_at5
	hex 000002 bf 85 3f 01 00
img32_pal
	db 4
	hex 0f131930
img32_txt
	db 15
	hex e0 de e7 dd de eb f5 00 00 00 ea ee de de eb

	; grey-_sexual
img33_nt_at0
	hex 000274 7f 7f 42 8c 00
img33_nt_at1
	hex 000174 94 7f 79 00
img33_nt_at2
	hex 010377 08 a0 7f 65 00
img33_nt_at3
	hex 01037a 5c a0 3f 11 00
img33_nt_at4
	hex 01025f 30 a0 7c 00
img33_nt_at5
	hex 000002 bf 85 3f 01 00
img33_pal
	db 4
	hex 0f101330
img33_txt
	db 13
	hex e0 eb de f2 f5 00 00 ec de f1 ee da e5

	; intersex
img34_nt_at0
	hex 000001 bf bf 8e 00
img34_nt_at1
	hex 010219 3f 22 81 c126 c13e c157 c128 c11c 19 c12b 41 c16d
	hex c166 c163 c16b 41 c144 04 00
img34_nt_at2
	hex 010243 13 c125 41 c15f 81 02 c129 c15e 41 c127 16 c13a
	hex c161 81 04 c129 c160 c153 16 c142 c150 06 c138 c15c 16
	hex c172 c14c 06 c134 c175 0f 00
img34_nt_at3
	hex 010214 07 c141 c154 81 04 c113 c13b c15a 16 c131 41 c144
	hex 81 02 c113 c12b 41 c149 17 c15e 41 c145 c122 c11e c12e
	hex 41 c15f 19 c13f c168 c178 c179 c16c c158 1d 00
img34_nt_at4
	hex 000001 bf bf 8e 00
img34_nt_at5
	hex 000001 bf 85 3f 01 00
img34_pal
	db 3
	hex 0f2804
img34_txt
	db 8
	hex e2 e7 ed de eb ec de f1

	; leather
img35_nt_at0
	hex 000204 07 c108 c109 c10b c10a 1c c10e 43 c10f 14 86 c184
	hex 45 c185 93 c401 c116 c11a c12d 45 c146 d601 c12a 48 00
img35_nt_at1
	hex 000102 c151 53 c207 c186 c142 88 c187 d307 02 c10d 89 c111
	hex 16 c112 88 c110 13 43 c12c c165 86 c16e 4c 00
img35_nt_at2
	hex 010329 0c 81 c15d c164 c16a c16f c176 c177 c15b 14 e07b 7f
	hex 41 c47e 00
img35_nt_at3
	hex 00017e 9c 7f 41 30 00
img35_nt_at4
	hex 000104 10 a0 7f 41 dc07 00
img35_nt_at5
	hex 000007 84 3f 3f 02 00
img35_pal
	db 4
	hex 0f011530
img35_txt
	db 7
	hex e5 de da ed e1 de eb

	; lesbian_5stripes
img36_nt_at0
	hex 000158 7f 7f 42 8c 00
img36_nt_at1
	hex 000258 94 7f 79 00
img36_nt_at2
	hex 02037e 08 a0 7f 65 00
img36_nt_at3
	hex 020383 5c a0 3f 11 00
img36_nt_at4
	hex 01026e 70 a0 3c 00
img36_nt_at5
	hex 000150 7f 45 08 88 d055 20 00
img36_pal
	db 8
	hex 0f142430 0f172730
img36_txt
	db 15
	hex e5 de ec db e2 da e7 d5 ec ed eb e2 e9 de ec

	; lesbian_5stripes_furry1
img37_nt_at0
	hex 000158 7f 7f 42 8c 00
img37_nt_at1
	hex 000158 94 e002 4d c147 c13f c140 c142 c13e c145 59 c143 c12b
	hex 01 c11d c131 01 c117 c141 58 c135 02 c119 c12d 02 c121
	hex 44 00
img37_nt_at2
	hex 00015a 48 8a c193 c190 c18e 02 c186 c18d 02 c188 c192 c191
	hex 8a 4a c12c 01 c125 c10e c106 c122 c136 c108 c10b c123 01
	hex c118 54 02 c11a 41 c14a c13c c13b c149 41 c12e 02 54
	hex c111 02 c14c c132 02 c11e c14b 02 c110 4e 00
img37_nt_at3
	hex 00015e 46 c130 c105 c113 c138 04 c128 c115 c104 c11c 4a 8b
	hex c18f c18c 06 c18b c18a 8b cb02 c153 08 c150 cb02 4b c13a
	hex c10d 06 c10a c12a 57 c134 c10f c107 c114 00
img37_nt_at4
	hex 090c16 81 01 41 c120 ec01 e05f fc02 00
img37_nt_at5
	hex 0002fa 7f 45 18 c855 c8aa 83 c1f2 c1f8 83 c8ff c80f 00
img37_pal
	db 15
	hex 0f17270f 0f27300f 0f30240f 0f2414
img37_txt
	db 23
	hex e5 de ec db e2 da e7 d5 ec ed eb e2 e9 de ec 00 00 df ee eb eb f2
	hex d1

	; lesbian_5stripes_furry2
img38_nt_at0
	hex 02b5be 3f 2d 81 41 c198 c201 c169 c1b2 c1b9 0c caf4 c1fd
	hex c19c 00
img38_nt_at1
	hex 010203 c121 c134 c142 c248 c147 c138 c124 c16e c1fc caf4 89 c1ef
	hex c1e5 c141 c168 41 c1cf 42 c1cd 41 c197 c146 c1db c1ee 89
	hex 48 c1f3 c1e5 c150 42 c1ae 01 c177 c1a2 01 c1aa 42 c17f
	hex c1db c1f1 50 c1e7 c14a 42 c1a4 02 c15c c18b 02 c179 42
	hex c14d c1dd 4f c1a5 c12d c172 42 c191 02 c154 c183 02 c162
	hex 42 c1a0 c12f 00
img38_nt_at2
	hex 0102c2 c17a 47 87 c18f c157 41 c1bf c1b8 c193 02 c15d c18c
	hex 02 c164 c1bd c1ba 41 c186 c160 87 08 c16b 41 c182 01
	hex c174 c135 c12e c16c c19b c130 c131 c16d 01 c153 41 c19a 10
	hex c171 41 02 c15b 41 c1c7 c1ad c1a9 c1c4 41 c18a 02 41
	hex c19f 10 c17c 41 c13b 02 c1d0 c192 02 c163 c1ce 02 c139
	hex 41 c1a7 0c 00
img38_nt_at3
	hex 010203 04 c170 41 c18d c124 c13f c1a3 04 c178 c144 c121 c15e
	hex 41 c19e 08 c7d7 c1d6 c16a 42 c1a1 c176 06 c175 c173 42
	hex c199 c1d5 c7d7 87 c1e9 c152 c1c5 41 c1a6 08 c17b 41 c1c8
	hex c181 c1df 8f c1d9 c16f 41 c1a8 c129 06 c126 c17d 41 c19d
	hex c1d8 90 c1eb c1d2 c1ac 41 c188 c12b c120 c133 00
img38_nt_at4
	hex 0203d1 c137 c123 c128 c159 01 c1b0 81 c1e1 51 c1e6 c1d2 c1ab
	hex c1ca 06 c1cc c1af 81 c1dc 49 caf6 c1ff c136 c15a c1b3 c1c3
	hex c1c9 c1cb c1c6 c1b6 c189 c132 c1fa caf6 0c c14e c138 c125 c201
	hex c122 c134 c14b 28 00
img38_nt_at5
	hex 0002aa 7f 45 08 c8a0 83 c20a 83 c2ff c101 02 c104 c2ff
	hex 20 00
img38_pal
	db 15
	hex 0f301424 0f301427 0f301727 0f3027
img38_txt
	db 23
	hex e5 de ec db e2 da e7 d5 ec ed eb e2 e9 de ec 00 00 df ee eb eb f2
	hex d2

	; lesbian_7stripes
img39_nt_at0
	hex 01025e 3f 21 a0 4c 00
img39_nt_at1
	hex 02037c 34 a0 60 18 00
img39_nt_at2
	hex 02037f 28 a0 7f 41 c47b 00
img39_nt_at3
	hex 01037b 9c 3f 01 60 d081 00
img39_nt_at4
	hex 027281 90 3f 01 60 dc01 00
img39_nt_at5
	hex 000150 7f 45 08 88 c855 c8a5 c8aa c80a 10 00
img39_pal
	db 12
	hex 0f041424 0f071727 0f242730
img39_txt
	db 15
	hex e5 de ec db e2 da e7 d7 ec ed eb e2 e9 de ec

	; neptunic
img40_nt_at0
	hex 000103 7f 7f 42 8c 00
img40_nt_at1
	hex 000003 bf bf 8e 00
img40_nt_at2
	hex 000103 bf a9 64 00
img40_nt_at3
	hex 000102 7f 5d b0 00
img40_nt_at4
	hex 000002 bf bf 8e 00
img40_nt_at5
	hex 000250 7f 45 18 88 d055 c805 08 00
img40_pal
	db 8
	hex 0f1c222c 0f30323c
img40_txt
	db 8
	hex e7 de e9 ed ee e7 e2 dc

	; non-_binary
img41_nt_at0
	hex 000002 bf bf 8e 00
img41_nt_at1
	hex 000203 74 bf 99 00
img41_nt_at2
	hex 000103 bf a9 64 00
img41_nt_at3
	hex 000001 bf bf 8e 00
img41_nt_at4
	hex 000001 90 3f 3d 00
img41_nt_at5
	hex 000000 3f 3f 06 00
img41_pal
	db 4
	hex 0f132830
img41_txt
	db 12
	hex e7 e8 e7 f5 00 00 db e2 e7 da eb f2

	; non-_binary_furry
img42_nt_at0
	hex 02b5be 3f 2d 81 41 c198 c201 c169 c1b2 c1b9 16 c1f2 c1ec
	hex 00
img42_nt_at1
	hex 010221 81 c134 c142 c248 c147 c138 c124 c1e2 c1f0 53 c1b7 c1e5
	hex c141 c168 41 c1cf 42 c1cd 41 c197 c146 c1db c1b4 49 0a
	hex c150 42 c1ae 01 c177 c1a2 01 c1aa 42 c17f 13 c14a 42
	hex c1a4 02 c15c c18b 02 c179 42 c14d 11 c12d c172 42 c191
	hex 02 c154 c183 02 c162 42 c1a0 c12f 00
img42_nt_at2
	hex 010257 10 81 41 c1bf c1b8 c193 02 c15d c18c 02 c164 c1bd
	hex c1ba 41 c186 10 c16b 41 c182 01 c174 c135 c12e c16c c19b
	hex c130 c131 c16d 01 c153 41 c19a 10 c171 41 02 c15b 41
	hex c1c7 c1ad c1a9 c1c4 41 c18a 02 41 c19f 08 47 01 c17c
	hex 41 c13b 02 c1d0 c192 02 c163 c1ce 02 c139 41 c1a7 01
	hex 4b 00
img42_nt_at3
	hex 01024c 43 81 c170 41 c18d c124 c13f c1a3 04 c178 c144 c121
	hex c15e 41 c19e c149 4e c184 c16a 42 c1a1 c176 06 c175 c173
	hex 42 c199 c155 4e c194 c152 c1c5 41 c1a6 08 c17b 41 c1c8
	hex c181 c165 4f c145 c16f 41 c1a8 c129 06 c126 c17d 41 c19d
	hex c140 50 c195 c12a c1ac 41 c188 c12b c120 c133 00
img42_nt_at4
	hex 000237 81 c123 c128 c159 41 c1b0 c127 c166 48 09 c10f c11c
	hex c1ab c1ca 46 c1cc c1af c11d c114 13 c10e c119 c15a c1b3 c1c3
	hex c1c9 c1cb c1c6 c1b6 c189 c11b c113 16 c116 c118 c11e c201 c11f
	hex c11a c117 28 00
img42_nt_at5
	hex 005055 3f 0d 48 82 c115 c205 c145 82 28 00
img42_pal
	db 7
	hex 0f301328 0f3028
img42_txt
	db 20
	hex e7 e8 e7 f5 00 00 db e2 e7 da eb f2 00 00 00 df ee eb eb f2

	; omni-_sexual
img43_nt_at0
	hex 000274 7f 7f 42 8c 00
img43_nt_at1
	hex 000174 94 7f 79 00
img43_nt_at2
	hex 000148 48 a0 3f 25 00
img43_nt_at3
	hex 000112 1c a0 7f 51 00
img43_nt_at4
	hex 01025f 30 a0 7c 00
img43_nt_at5
	hex 000250 7f 45 08 88 d055 20 00
img43_pal
	db 7
	hex 0f22320f 0f2535
img43_txt
	db 13
	hex e8 e6 e7 e2 f5 00 00 ec de f1 ee da e5

	; pan-_gender1
img44_nt_at0
	hex 01026f 7f 61 a0 0c 00
img44_nt_at1
	hex 010285 34 a0 78 00
img44_nt_at2
	hex 01026e 68 a0 3f 01 c458 00
img44_nt_at3
	hex 025880 5c 3f 21 90 00
img44_nt_at4
	hex 015a80 90 3f 01 60 dc02 00
img44_nt_at5
	hex 000255 7f 45 08 c850 88 18 88 c805 00
img44_pal
	db 7
	hex 0f303537 0f3738
img44_txt
	db 12
	hex e9 da e7 f5 00 e0 de e7 dd de eb d1

	; pan-_gender2
img45_nt_at0
	hex 000158 7f 7f 42 8c 00
img45_nt_at1
	hex 000258 94 7f 79 00
img45_nt_at2
	hex 02037e 08 a0 7f 65 00
img45_nt_at3
	hex 020383 5c a0 3f 11 00
img45_nt_at4
	hex 01026e 70 a0 3c 00
img45_nt_at5
	hex 000001 bf 85 3f 01 00
img45_pal
	db 4
	hex 0f212528
img45_txt
	db 12
	hex e9 da e7 f5 00 e0 de e7 dd de eb d2

	; pan-_sexual
img46_nt_at0
	hex 000001 bf bf 8e 00
img46_nt_at1
	hex 000103 7f 75 98 00
img46_nt_at2
	hex 000003 bf bf 8e 00
img46_nt_at3
	hex 000203 bf 9d 70 00
img46_nt_at4
	hex 000002 bf bf 8e 00
img46_nt_at5
	hex 000002 bf 85 3f 01 00
img46_pal
	db 4
	hex 0f152128
img46_txt
	db 12
	hex e9 da e7 f5 00 00 ec de f1 ee da e5

	; pan-_sexual_furry1
img47_nt_at0
	hex 000001 bf bf 8e 00
img47_nt_at1
	hex 000147 7f 42 81 c13f c140 c142 c13e c145 59 c143 c12b 01
	hex c11d c131 01 c117 c141 58 c135 02 c119 c12d 02 c121 44
	hex 00
img47_nt_at2
	hex 000147 52 81 c144 c133 02 c11b c12f 02 c11f c146 c145 54
	hex c12c 01 c125 c10e c106 c122 c136 c108 c10b c123 01 c118 54
	hex 02 c11a 41 c14a c13c c13b c149 41 c12e 02 54 c111 02
	hex c14c c132 02 c11e c14b 02 c110 4e 00
img47_nt_at3
	hex 000130 46 81 c105 c113 c138 04 c128 c115 c104 c11c 55 c137
	hex c127 06 c126 c124 56 c139 08 c129 56 c13a c10d 06 c10a
	hex c12a 57 c134 c10f c107 c114 00
img47_nt_at4
	hex 010916 81 41 c10c c120 3f 3f 0a 00
img47_nt_at5
	hex 0001a5 7f 45 18 c850 c855 83 c1a1 c1a4 83 c8aa c80a 00
img47_pal
	db 10
	hex 0f150f0f 0f280f0f 0f21
img47_txt
	db 20
	hex e9 da e7 f5 00 00 ec de f1 ee da e5 00 00 df ee eb eb f2 d1

	; pan-_sexual_furry2
img48_nt_at0
	hex 02b5be 3f 2d 81 41 c198 c201 c169 c1b2 c1b9 16 c1c0 c19c
	hex 00
img48_nt_at1
	hex 010280 c121 c134 c142 c248 c147 c138 c124 c16e c1bb 53 c1b7 81
	hex c141 c168 41 c1cf 42 c1cd 41 c197 c146 c151 c1b4 51 c1c1
	hex 81 c150 42 c1ae 01 c177 c1a2 01 c1aa 42 c17f c151 c1bc
	hex 50 c18e c14a 42 c1a4 02 c15c c18b 02 c179 42 c14d c15f
	hex 4f c1a5 c12d c172 42 c191 02 c154 c183 02 c162 42 c1a0
	hex c12f 00
img48_nt_at2
	hex 01027a 81 4e c190 c157 41 c1bf c1b8 c193 02 c15d c18c 02
	hex c164 c1bd c1ba 41 c186 c161 4e c17e c16b 41 c182 01 c174
	hex c135 c12e c16c c19b c130 c131 c16d 01 c153 41 c19a c14f 4e
	hex 01 c171 41 02 c15b 41 c1c7 c1ad c1a9 c1c4 41 c18a 02
	hex 41 c19f 01 4e 01 c17c 41 c13b 02 c1d0 c192 02 c163
	hex c1ce 02 c139 41 c1a7 01 4b 00
img48_nt_at3
	hex 010243 43 81 c170 41 c18d c124 c13f c1a3 04 c178 c144 c121
	hex c15e 41 c19e c13e 4e c185 c16a 42 c1a1 c176 06 c175 c173
	hex 42 c199 c156 4e c194 c152 c1c5 41 c1a6 08 c17b 41 c1c8
	hex c181 c165 4f c1d9 c16f 41 c1a8 c129 06 c126 c17d 41 c19d
	hex c1d8 50 c1eb c1d2 c1ac 41 c188 c12b c120 c133 00
img48_nt_at4
	hex 0237d1 41 c123 c128 c159 01 c1b0 81 c1e1 11 c187 c1d2 c1ab
	hex c1ca 06 c1cc c1af 81 c158 13 c1ea c1d4 c15a c1b3 c1c3 c1c9
	hex c1cb c1c6 c1b6 c189 c1d3 c1e0 16 c14e c138 c125 c201 c122 c134
	hex c14b 28 00
img48_nt_at5
	hex 0002a0 7f 45 18 82 04 82 c2aa 04 c2aa c25a 04 c25a
	hex c255 c151 c250 c154 c255 c805 00
img48_pal
	db 11
	hex 0f301521 0f30210f 0f3028
img48_txt
	db 20
	hex e9 da e7 f5 00 00 ec de f1 ee da e5 00 00 df ee eb eb f2 d2

	; poly-_amory1
img49_nt_at0
	hex 000001 bf bf 8e 00
img49_nt_at1
	hex 000001 bf bf 8e 00
img49_nt_at2
	hex 011322 15 41 81 c124 c123 c120 c128 c135 19 c14e c18d c18a
	hex c188 c195 c18f c159 19 c154 c121 c170 c12d c168 1c c140 c163
	hex c13f c164 12 00
img49_nt_at3
	hex 014c5b 0a 41 81 c144 c165 c129 1b c152 c15a c13b c193 c160
	hex 2d f000 00
img49_nt_at4
	hex 000000 3f 3f 0e 00
img49_nt_at5
	hex 005055 3f 0d 48 88 c805 20 00
img49_pal
	db 6
	hex 0f16280f 0f02
img49_txt
	db 13
	hex e9 e8 e5 f2 f5 00 00 da e6 e8 eb f2 d1

	; poly-_amory2
img50_nt_at0
	hex 012032 3f 3f 0b 41 81 c13a 00
img50_nt_at1
	hex 0102a7 c139 c12b 04 c127 c133 c13a c138 c122 11 c124 c14f 41
	hex 81 c1a9 c18c c142 c129 c125 c140 c166 c1ae 81 41 c174 c128
	hex 10 c148 41 c17e 01 c14a c192 c1a8 c17a c154 c1ad c196 c16f
	hex 01 c158 41 c16c 10 c153 c18a c123 03 c156 c19e c1a1 c17c
	hex 03 c123 c164 c179 0f c131 c15c 42 c17b c13e c12a 01 c151
	hex c177 01 c126 c13d c155 42 c182 00
img50_nt_at2
	hex 0102ab c137 0d c12e c162 81 41 c191 c199 c1a8 c184 c13c 02
	hex c13b c15e c1ad c19a c195 41 81 c188 c134 0c c14d c1a6 c175
	hex 41 c16b 01 c150 c19b 41 c141 c13f 41 c19c c176 01 c147
	hex 41 c16e c1a4 c172 0c c15a c189 01 c18e c181 02 c143 c193
	hex 42 c197 c167 02 c15b c190 01 c163 c180 0c c160 c187 01
	hex c152 41 c168 01 c11f c145 42 c169 c121 01 c144 41 c178
	hex 01 c161 c186 0a 00
img50_nt_at3
	hex 000102 42 c159 c18b c135 41 c194 c183 c12c c149 81 c18f c18d
	hex 81 c16d c12d c15d c198 41 c12f c165 c17f 4c c146 c19f c173
	hex c136 c14c 82 c1a5 c185 42 c15f c1a3 82 c171 c130 c14e c1a2
	hex c16a 4d c157 c19d 82 c1ac 81 c170 44 c14b 81 c1aa 82
	hex c1a0 c17d 47 09 c216 01 c117 c115 c107 02 c106 c10e c118
	hex 01 c216 15 c108 c119 c114 c105 00
img50_nt_at4
	hex 00040d 41 81 c11a c10f 19 c109 c11b c113 c10c c11c c110 1b
	hex c10a c11d c11e c111 1d c10b c112 2b 00
img50_nt_at5
	hex 000550 3f 1d 88 c855 42 c4a5 42 03 c18a c12a 0b 00
img50_pal
	db 10
	hex 0f02280f 0f16280f 0f28
img50_txt
	db 13
	hex e9 e8 e5 f2 f5 00 00 da e6 e8 eb f2 d2

	; poly-_amory3
img51_nt_at0
	hex 01026d 08 81 57 09 81 56 0a 81 55 04 c15b c15e
	hex c15d c159 03 81 54 03 c161 43 c16b c15c 03 00
img51_nt_at1
	hex 01026d 81 53 03 c165 44 c16b c15c 03 81 52 03 c166
	hex 45 c16b c15c 03 81 51 03 c163 46 c16b c15c 03 81
	hex 50 03 c160 46 c171 c169 03 c162 48 00
img51_nt_at2
	hex 010262 48 03 c165 45 c173 c169 03 81 51 03 c167 44
	hex c173 c16a 03 81 52 03 c164 43 c173 c16a 03 81 53
	hex 04 c16c c172 c170 c168 03 81 54 04 00
img51_nt_at3
	hex 010262 06 81 55 09 81 56 08 81 57 07 81 58
	hex 06 81 49 00
img51_nt_at4
	hex 010262 50 05 81 5a 04 81 5b 03 81 5c 02 81
	hex 59 00
img51_nt_at5
	hex 000262 44 c101 81 5e 81 5f 0a c650 02 c104 c555 03
	hex c184 c4a5 02 c180 c5aa 01 c1c0 c6fa c1c0 c7ff c80f 00
img51_pal
	db 15
	hex 0f30280f 0f30210f 0f30150f 0f3003
img51_txt
	db 13
	hex e9 e8 e5 f2 f5 00 00 da e6 e8 eb f2 d3

	; poly-_sexual
img52_nt_at0
	hex 000001 bf bf 8e 00
img52_nt_at1
	hex 000103 7f 75 98 00
img52_nt_at2
	hex 000003 bf bf 8e 00
img52_nt_at3
	hex 000203 bf 9d 70 00
img52_nt_at4
	hex 000002 bf bf 8e 00
img52_nt_at5
	hex 000002 bf 85 3f 01 00
img52_pal
	db 4
	hex 0f14212b
img52_txt
	db 13
	hex e9 e8 e5 f2 f5 00 00 ec de f1 ee da e5

	; queer
img53_nt_at0
	hex 00024d 3f 01 a0 6c 00
img53_nt_at1
	hex 01026f 54 a0 3f 01 58 00
img53_nt_at2
	hex 02037e 28 a0 7f 41 c47a 00
img53_nt_at3
	hex 00017a 9c 7f 71 00
img53_nt_at4
	hex 01025a 10 a0 7f 41 dc54 00
img53_nt_at5
	hex 0054a0 44 3f 19 88 c8aa c85a c855 08 00
img53_pal
	db 12
	hex 0f21310f 0f26350f 0f282930
img53_txt
	db 5
	hex ea ee de de eb

	; rainbow_6stripes
img54_nt_at0
	hex 000203 bf bf 82 4c 00
img54_nt_at1
	hex 000203 7f 75 98 00
img54_nt_at2
	hex 000103 bf a9 64 00
img54_nt_at3
	hex 000102 7f 5d b0 00
img54_nt_at4
	hex 000102 bf 91 7c 00
img54_nt_at5
	hex 000150 7f 45 10 88 d055 c805 10 00
img54_pal
	db 8
	hex 0f041216 0f192728
img54_txt
	db 15
	hex eb da e2 e7 db e8 f0 d6 ec ed eb e2 e9 de ec

	; rainbow_7stripes
img55_nt_at0
	hex 01025e 3f 21 a0 4c 00
img55_nt_at1
	hex 02037c 34 a0 60 18 00
img55_nt_at2
	hex 01026e 68 a0 3f 01 c476 00
img55_nt_at3
	hex 037679 5c 3f 21 90 00
img55_nt_at4
	hex 015a79 90 3f 01 60 dc02 00
img55_nt_at5
	hex 000250 7f 45 08 88 c855 c8a5 c8aa 18 00
img55_pal
	db 12
	hex 0f03042c 0f162728 0f19282c
img55_txt
	db 15
	hex eb da e2 e7 db e8 f0 d7 ec ed eb e2 e9 de ec

	; rainbow_8stripes
img56_nt_at0
	hex 000102 bf a1 6c 00
img56_nt_at1
	hex 000001 bf bf 8e 00
img56_nt_at2
	hex 000102 48 bf a1 64 00
img56_nt_at3
	hex 000102 7c bf 91 00
img56_nt_at4
	hex 000102 90 7f 61 9c 00
img56_nt_at5
	hex 000250 7f 45 08 88 c855 c8ff c8af c8aa 10 00
img56_pal
	db 15
	hex 0f03040f 0f16250f 0f192c0f 0f2728
img56_txt
	db 15
	hex eb da e2 e7 db e8 f0 d8 ec ed eb e2 e9 de ec

	; rainbow_furry1
img57_nt_at0
	hex 01027b 81 41 81 41 c181 41 c170 01 c170 01 c10d d500
	hex 01 81 01 81 c103 c181 41 c170 41 c170 01 c10d d400
	hex c127 01 81 41 81 41 c181 41 c170 01 c170 01 c125
	hex c10e c10b c105 d100 c127 01 81 01 81 c103 c181 41 c170
	hex 41 c171 c16c c16b 01 c11e c109 d100 c127 01 81 41 81
	hex 41 c181 41 c193 c129 00
img57_nt_at1
	hex 000127 c12a c12b c176 c16a c121 c106 11 81 41 c17b 41 c17b
	hex c103 c181 c153 c185 c18d c113 c102 c178 41 c11b 12 81 41
	hex c17b c102 c196 c15c c163 c142 c150 c13d c195 c12c c16f c124 13
	hex 81 41 c17d c11f c141 c168 c198 c157 c148 c14f c116 c177 c125
	hex 14 c138 c174 c11a c13b c14e 02 c14d c13c c111 c179 41 c10d
	hex 05 00
img57_nt_at2
	hex 000102 0e c119 c173 c125 c187 c151 02 c145 c158 c18a 81 c170
	hex 41 c10d 12 c117 41 c17c c152 04 c146 81 c170 41 c170
	hex 41 c10d 11 c10f c12d c172 c194 c307 c183 c165 c181 81 c170
	hex 81 c170 41 c10d 11 c112 c130 41 c175 c17e c17f 81 c17b
	hex 81 c181 81 c170 41 c170 41 c10d 0d 00
img57_nt_at3
	hex 01027b c400 c110 c128 c133 c138 01 81 01 81 c103 c181 41
	hex c170 41 c170 01 c10d d400 c127 01 81 41 81 41 c181
	hex 41 c170 01 c170 01 c10d d400 c127 01 81 01 81 c103
	hex c181 41 c170 41 c170 01 c10d d400 c127 01 81 41 81
	hex 41 c181 41 c170 01 c170 01 c10d d400 c127 00
img57_nt_at4
	hex 01027b 01 81 01 81 c103 c181 41 c170 41 c170 01 c10d
	hex d400 c127 01 81 41 81 41 c181 41 c170 01 c170 01
	hex c10d d400 c127 01 81 01 81 c103 c181 41 c170 41 c170
	hex 01 c10d d400 c127 01 81 41 81 41 c181 41 c170 01
	hex c170 01 c10d d400 c127 01 81 01 81 c103 c181 41 c170
	hex 00
img57_nt_at5
	hex 000102 81 c170 41 c10d 14 c127 41 c17b 81 c17b 81 c181
	hex 81 c170 41 c170 41 15 c127 41 c17b 41 c17b c103 c181
	hex 81 c170 81 c170 08 c1b0 c150 06 c1cf c1b6 c151 c110 05
	hex c1cf c1a6 c155 05 c1cc c1fb c1b6 c151 06 c1cf c1b6 c151 06
	hex c1cf c1b6 c151 06 c10f c106 41 00
img57_pal
	db 15
	hex 0f16270f 0f27281b 0f111b0f 0f0411
img57_txt
	db 15
	hex eb da e2 e7 db e8 f0 00 00 df ee eb eb f2 d1

	; rainbow_furry2
img58_nt_at0
	hex 02b5be 3f 2d 81 41 c198 c201 c169 c1b2 c1b9 0c ca03 c1f2
	hex c1ec 00
img58_nt_at1
	hex 010203 c121 c134 c142 c248 c147 c138 c124 c1e2 c1f0 93 c1ef c1e5
	hex c141 c168 41 c1cf 42 c1cd 41 c197 c146 c1db c1ee 91 c1f3
	hex c1e5 c150 42 c1ae 01 c177 c1a2 01 c1aa 42 c17f c1db c1f1
	hex 90 c1e7 c14a 42 c1a4 02 c15c c18b 02 c179 42 c14d c1dd
	hex 8f c1ed c12d c172 42 c191 02 c154 c183 02 c162 42 c1a0
	hex c12f 00
img58_nt_at2
	hex 010203 c1e3 8e c1e8 c157 41 c1bf c1b8 c193 02 c15d c18c 02
	hex c164 c1bd c1ba 41 c186 c1de 8e c1e4 c16b 41 c182 01 c174
	hex c135 c12e c16c c19b c130 c131 c16d 01 c153 41 c19a c1da 8e
	hex 01 c171 41 02 c15b 41 c1c7 c1ad c1a9 c1c4 41 c18a 02
	hex 41 c19f 01 87 47 01 c17c 41 c13b 02 c1d0 c192 02
	hex c163 c1ce 02 c139 41 c1a7 01 4b 00
img58_nt_at3
	hex 010203 43 c143 c170 41 c18d c124 c13f c1a3 04 c178 c144 c121
	hex c15e 41 c19e c13e 4e c185 c16a 42 c1a1 c176 06 c175 c173
	hex 42 c199 c156 4e c194 c152 c1c5 41 c1a6 08 c17b 41 c1c8
	hex c181 c165 47 88 c1d9 c16f 41 c1a8 c129 06 c126 c17d 41
	hex c19d c1d8 90 c1eb c1d2 c1ac 41 c188 c12b c120 c133 00
img58_nt_at4
	hex 0203d1 c137 c123 c128 c159 01 c1b0 81 c1e1 51 c1e6 c1d2 c1ab
	hex c1ca 06 c1cc c1af 81 c1dc 53 c1ea c1d4 c15a c1b3 c1c3 c1c9
	hex c1cb c1c6 c1b6 c189 c1d3 c1e0 4a 0c c14e c138 c125 c201 c122
	hex c134 c14b 28 00
img58_nt_at5
	hex 0002a0 7f 45 08 88 c80a 82 04 82 c2fa 04 c2fa c25f
	hex c110 02 c140 c25f c305 02 c305 08 00
img58_pal
	db 15
	hex 0f300427 0f300412 0f301628 0f3019
img58_txt
	db 15
	hex eb da e2 e7 db e8 f0 00 00 df ee eb eb f2 d2

	; rainbow_progress
img59_nt_at0
	hex 01025c 81 01 c107 c100 c10b 5c 81 01 c107 c100 c10b 5a
	hex c1ae 41 81 01 c107 c100 c10b 59 c103 c1ae 41 81 01
	hex c107 c100 c10b 58 c1ae 41 c1ae 41 81 01 c107 c100 c106
	hex 03 00
img59_nt_at1
	hex 0102ae 14 c103 81 c103 81 41 c15c 01 c107 c100 c106 16
	hex c203 81 41 81 41 c15c 01 c107 c100 c106 15 c303 81
	hex c103 81 41 c15c 01 c107 c100 c106 14 c403 81 41 81
	hex 41 c15c 01 c107 c100 c10b 4b 00
img59_nt_at2
	hex 0203ae 08 45 81 41 81 01 c15c c101 c107 c100 c10b 12
	hex 46 81 01 81 01 c15c c101 c107 c100 c10b 11 47 81
	hex 41 81 01 c15c c101 c107 c100 c10b 10 47 c1b0 41 c1b0
	hex 01 c186 c101 c109 c100 c10c 54 00
img59_nt_at3
	hex 0203b0 42 81 01 81 01 c186 c101 c109 c100 c10c 56 81
	hex 41 81 01 c186 c101 c109 c100 c10c 56 81 01 81 01
	hex c186 c101 c109 c100 c10c 56 81 41 81 01 c186 c101 c109
	hex c100 c104 d401 42 81 01 81 01 c186 c101 c109 c100 c104
	hex c501 00
img59_nt_at4
	hex 0102b0 10 c103 81 c103 81 41 c186 01 c109 c100 c104 16
	hex 81 41 81 41 c186 01 c109 c100 c104 17 c103 81 41
	hex c186 01 c109 c100 c104 18 81 41 c186 01 c109 c100 c104
	hex 15 00
img59_nt_at5
	hex 000155 44 c102 c186 41 c109 01 c104 5a c186 41 c109 01
	hex c104 5b 09 c7a0 c110 c108 c6fa 81 c110 c10c c5ff 82 01
	hex c18c c4af 81 41 c180 c5aa 41 c140 c65a 01 c705 00
img59_pal
	db 15
	hex 0f082125 0f042530 0f121619 0f2728
img59_txt
	db 15
	hex eb da e2 e7 db e8 f0 e9 eb e8 e0 eb de ec ec

	; rainbow_progress_intersex
img60_nt_at0
	hex 0102ae 81 41 81 41 c15c 01 c107 c100 c106 17 c103 81
	hex c103 81 41 c15c 01 c107 c100 c106 16 c1ad c103 81 41
	hex 81 41 c15c 01 c107 c100 c106 15 41 c1ad c103 81 c103
	hex 81 41 c15c 01 c107 c100 c106 14 42 c1ad c103 81 41
	hex 81 41 c15c 01 c107 c100 00
img60_nt_at1
	hex 0203ae c10d 53 03 c1ad 41 81 41 81 01 c15c c101 c107
	hex c100 c10d 52 04 c1ad 41 81 01 81 01 c15c c101 c107
	hex c100 c10d 51 05 c1ad 41 81 41 81 01 c15c c101 c107
	hex c100 c10d 50 06 c1ad 41 81 01 81 01 c15c c101 c107
	hex c100 c10b 07 00
img60_nt_at2
	hex 0203ae 0a c196 c182 c17c c192 01 c1ad 41 81 41 81 01
	hex c15c c101 c107 c100 c10b 0f c179 c130 c158 c17a c137 c157 01
	hex c1ad 41 81 01 81 01 c15c c101 c107 c100 c10b 0e c161
	hex c158 02 c17a c13d 02 c1ad 41 81 41 81 01 c15c c101
	hex c107 c100 c10b 0d c15e c1a2 02 c1a3 c15d 02 c1ab 41 c1b0
	hex 41 c1b0 01 c186 c101 c109 c100 c10a 0d c16b c156 c1a2 00
img60_nt_at3
	hex 0203b0 c1a3 c178 c147 01 c1ab 41 81 01 81 01 c186 c101
	hex c109 c100 c10a 0f c138 c14a c16e c131 01 c1ab 41 81 41
	hex 81 01 c186 c101 c109 c100 c10a 14 c1ab 41 81 01 81
	hex 01 c186 c101 c109 c100 c10a 14 c1ab 41 81 41 81 01
	hex c186 c101 c109 c100 c104 d001 04 c1ab 41 81 01 81 01
	hex c186 c101 c109 c100 c104 c101 00
img60_nt_at4
	hex 0102b0 10 43 c1ab c103 81 c103 81 41 c186 01 c109 c100
	hex c104 12 42 c1ab c103 81 41 81 41 c186 01 c109 c100
	hex c104 13 41 c1ab c103 81 c103 81 41 c186 01 c109 c100
	hex c104 14 c1ab c103 81 41 81 41 c186 01 c109 c100 c104
	hex 11 00
img60_nt_at5
	hex 0001b0 44 c103 81 c103 81 c102 c186 41 c109 01 c104 56
	hex 81 c102 81 c102 c186 41 c109 01 c104 57 08 c160 c150
	hex c6f0 c108 c165 c15d c5ff 01 c108 c165 c15d c40f 02 c188 c155
	hex c1d1 c3f0 01 c180 c156 c195 c4af c180 c156 c115 c50a c106 c105
	hex 06 00
img60_pal
	db 16
	hex 0f042830 0f082125 0f122530 0f161927
img60_txt
	db 23
	hex eb da e2 e7 db e8 f0 e9 eb e8 e0 eb de ec ec e2 e7 ed de eb ec de
	hex f1

	; sapio-_sexual1
img61_nt_at0
	hex 000003 bf bf 8e 00
img61_nt_at1
	hex 000203 bf b5 58 00
img61_nt_at2
	hex 000002 bf bf 8e 00
img61_nt_at3
	hex 000102 bf 9d 70 00
img61_nt_at4
	hex 000001 bf bf 8e 00
img61_nt_at5
	hex 000001 bf 85 3f 01 00
img61_pal
	db 4
	hex 0f121819
img61_txt
	db 14
	hex ec da e9 e2 e8 f5 00 ec de f1 ee da e5 d1

	; sapio-_sexual2
img62_nt_at0
	hex 000001 bf bf 8e 00
img62_nt_at1
	hex 000102 7f 75 98 00
img62_nt_at2
	hex 000002 bf bf 8e 00
img62_nt_at3
	hex 000203 7f 5d b0 00
img62_nt_at4
	hex 000003 bf bf 8e 00
img62_nt_at5
	hex 000003 bf 85 3f 01 00
img62_pal
	db 4
	hex 0f101521
img62_txt
	db 14
	hex ec da e9 e2 e8 f5 00 ec de f1 ee da e5 d2

	; sapphic
img63_nt_at0
	hex 000001 bf bf 8e 00
img63_nt_at1
	hex 011523 3f 3f 04 41 81 c124 c117 06 00
img63_nt_at2
	hex 010236 16 81 42 c14e 1a c118 c120 c132 42 c14a c11f c11b
	hex 18 c135 41 c156 c188 c18a c13d 41 c14d 18 c133 c171 c173
	hex c189 c18b c170 c174 c14b 10 00
img63_nt_at3
	hex 01021d 09 81 c12f c155 c13c c147 c121 1a c139 41 c159 c140
	hex 41 c152 1a c137 c169 c148 c130 c167 c14f 3d 00
img63_nt_at4
	hex 000001 bf bf 8e 00
img63_nt_at5
	hex 000150 7f 45 08 88 c855 c805 08 88 c855 c805 00
img63_pal
	db 6
	hex 0f301327 0f25
img63_txt
	db 7
	hex ec da e9 e9 e1 e2 dc

	; therian,_otherkin
img64_nt_at0
	hex 000002 bf bf 8e 00
img64_nt_at1
	hex 0102a4 41 81 c1a1 c1a8 c1a7 c19f c1a3 58 c1a2 c19a c195 01
	hex c172 c14a 01 c18d c199 c1a0 55 c19d c196 02 c17f c152 c128
	hex c17e 02 c18e c19b 53 c19e c193 02 c17d c16d c12b c155 c144
	hex c17c 02 c18b c19c 49 0c c175 c10b c10f c15a c131 c111 c10d
	hex c174 04 00
img64_nt_at2
	hex 012471 13 81 41 c166 c135 c153 c12a c15e c13d c14f c149 15
	hex c17b c14d c11a c109 c148 c129 c154 c170 c10a c114 c125 c17a 14
	hex c16e c134 c163 c127 c15f c103 c106 c136 c151 c13a c15d c145 14
	hex c15b c146 c123 c162 c107 c13f c168 c104 c139 c14e c16c c132 0e
	hex 00
img64_nt_at3
	hex 010221 06 c15c c142 c110 c140 c159 c13c c165 c12f c169 c112 c130
	hex c133 14 c167 c116 81 c120 c113 c11d c117 c119 c11f 81 c11c
	hex c13e 13 c181 c158 c122 c177 c173 c12e c115 c11b c157 c14b c179
	hex c14c c12d c180 09 48 c197 c1a6 c12c c161 c126 c160 c105 c143
	hex c16b c108 c137 c150 c138 c156 c1a5 c18f 51 c194 02 c16a c10e
	hex c13b c176 00
img64_nt_at4
	hex 010278 81 c164 c10c c141 02 c18c 53 c191 03 c16f c11e c118
	hex c147 03 c189 55 c192 c183 06 c182 c18a 57 c198 c188 c186
	hex c284 c185 c187 c190 68 00
img64_nt_at5
	hex 000250 7f 45 28 82 c110 02 c140 82 c355 c151 c154 c355
	hex c805 00
img64_pal
	db 7
	hex 0f301b0f 0f3003
img64_txt
	db 16
	hex ed e1 de eb e2 da e7 f4 e8 ed e1 de eb e4 e2 e7

	; trans-_gender
img65_nt_at0
	hex 000158 7f 7f 42 8c 00
img65_nt_at1
	hex 000258 94 7f 79 00
img65_nt_at2
	hex 02037e 08 a0 7f 65 00
img65_nt_at3
	hex 020383 5c a0 3f 11 00
img65_nt_at4
	hex 01026e 70 a0 3c 00
img65_nt_at5
	hex 000001 bf 85 3f 01 00
img65_pal
	db 4
	hex 0f212530
img65_txt
	db 14
	hex ed eb da e7 ec f5 00 00 e0 de e7 dd de eb

	; trans-_gender_furry1
img66_nt_at0
	hex 000274 7f 7f 42 8c 00
img66_nt_at1
	hex 000102 d474 6d c147 c13f c140 c142 c13e c145 59 c143 c12b 01
	hex c11d c131 01 c117 c141 4c 8c c152 02 c14e c151 02 c14f
	hex 84 00
img66_nt_at2
	hex 000172 c802 8a c199 c196 c195 02 c187 c194 02 c189 c198 c197
	hex 8a 4a c12c 01 c125 c10e c106 c122 c136 c108 c10b c123 01
	hex c118 54 02 c11a 41 c14a c13c c13b c149 41 c12e 02 54
	hex c111 02 c14c c132 02 c11e c14b 02 c110 4e 00
img66_nt_at3
	hex 00015e 46 c130 c105 c113 c138 04 c128 c115 c104 c11c 4a 8b
	hex c18f c18c 06 c18b c18a 8b cb02 c153 08 c150 cb02 4b c13a
	hex c10d 06 c10a c12a 57 c134 c10f c107 c114 00
img66_nt_at4
	hex 090c16 81 01 41 c120 ec01 e05f fc02 00
img66_nt_at5
	hex 000250 7f 45 08 88 c855 c805 08 88 c855 c805 00
img66_pal
	db 7
	hex 0f30250f 0f2521
img66_txt
	db 22
	hex ed eb da e7 ec f5 00 00 e0 de e7 dd de eb 00 00 df ee eb eb f2 d1

	; trans-_gender_furry2
img67_nt_at0
	hex 0102be 3f 0d 48 18 81 c1b5 c198 02 c169 c1b2 c1b9 0c
	hex c82c c2f4 c1fd c19c 00
img67_nt_at1
	hex 010203 c121 c134 c142 c248 c147 c138 c124 c16e c1fc c2f4 c82c 48
	hex 81 c1ef c1e5 c141 c168 41 c1cf 42 c1cd 41 c197 c146 c1db
	hex c1ee 81 50 c1f3 c1e5 c150 42 c1ae 01 c177 c1a2 01 c1aa
	hex 42 c17f c1db c1f1 50 c1e7 c14a 42 c1a4 02 c15c c18b 02
	hex c179 42 c14d c1dd 4f c1a5 c12d c172 42 c191 02 c154 c183
	hex 02 c162 42 c1a0 c12f 00
img67_nt_at2
	hex 0102c2 c17a 47 87 c18f c157 41 c1bf c1b8 c193 02 c15d c18c
	hex 02 c164 c1bd c1ba 41 c186 c160 87 08 c16b 41 c182 01
	hex c174 c135 c12e c16c c19b c130 c131 c16d 01 c153 41 c19a 10
	hex c171 41 02 c15b 41 c1c7 c1ad c1a9 c1c4 41 c18a 02 41
	hex c19f 10 c17c 41 c13b 02 c1d0 c192 02 c163 c1ce 02 c139
	hex 41 c1a7 0c 00
img67_nt_at3
	hex 01023d 04 c170 41 c18d c124 c13f c1a3 04 c178 c144 c121 c15e
	hex 41 c19e 08 87 c13c c16a 42 c1a1 c176 06 c175 c173 42
	hex c199 c13a 87 47 c194 c152 c1c5 41 c1a6 08 c17b 41 c1c8
	hex c181 c165 4f c1d9 c16f 41 c1a8 c129 06 c126 c17d 41 c19d
	hex c1d8 50 c1eb c1d2 c1ac 41 c188 c12b c120 c133 00
img67_nt_at4
	hex 0102d1 c137 c123 c128 c159 41 c1b0 81 c1e1 50 c103 c1e6 c1d2
	hex c1ab c1ca 46 c1cc c1af 81 c1dc c103 48 c8b1 c2f6 c1ff c136
	hex c15a c1b3 c1c3 c1c9 c1cb c1c6 c1b6 c189 c132 c1fa c2f6 c8b1 0c
	hex c14e c138 c125 02 c122 c134 c14b 18 48 08 00
img67_nt_at5
	hex 0055aa ff01 c501 08 c8a0 82 c10a 02 c10a 82 42 04 42
	hex 08 42 04 42 82 c1a0 02 c1a0 82 c80a 00
img67_pal
	db 11
	hex 0f302125 0f30250f 0f2125
img67_txt
	db 22
	hex ed eb da e7 ec f5 00 00 e0 de e7 dd de eb 00 00 df ee eb eb f2 d2

	; uranic
img68_nt_at0
	hex 000102 7f 7f 42 8c 00
img68_nt_at1
	hex 000203 7f 75 98 00
img68_nt_at2
	hex 000203 bf a9 64 00
img68_nt_at3
	hex 000102 bf 9d 70 00
img68_nt_at4
	hex 000103 7f 51 bc 00
img68_nt_at5
	hex 000350 7f 45 20 88 d055 c805 00
img68_pal
	db 8
	hex 0f011121 0f303138
img68_txt
	db 6
	hex ee eb da e7 e2 dc

